In [29]:
import pymysql
import random
from faker import Faker
fake =Faker('ko_KR')
Faker.seed(3);
db= pymysql.connect(host='localhost',user='root',password='root',db='musinsa')
curs =db.cursor()
seq = 995
for _ in range(6):
    while True:
        ssn=fake.ssn()
        if (ssn[2]=='0' and ssn[3]=='0') or (ssn[4]=='0' and ssn[5]=='0'):
            continue
        break
    if ssn[7]=='1' or ssn[7]=='2':
        birthday= '19'+ssn[0:2]+'-'+ssn[2:4]+'-'+ssn[4:6]
    elif ssn[7]=='3' or ssn[7]=='4':
        birthday= '20'+ssn[0:2]+'-'+ssn[2:4]+'-'+ssn[4:6]
    if ssn[7]=='1' or ssn[7]=='3':
        gender='M'
        height=random.randint(160,190)
        print(gender)
        print(height)
        if height >=190:
            size='2XL'
        elif height >=180:
            size='XL'
        elif height >=170:
            size='L'
        elif height >=170:
            size='M'
        elif height >=170:
            size='S'
        print(size)
    elif ssn[7]=='2' or ssn[7]=='4':
        gender = 'F'
        height=random.randint(150,180)
        print(gender)
        print(height)
        if height >=170:
            size='L'
        elif height >=160:
            size='M'
        elif height >=150:
            size='S'
        print(size)
    query = "INSERT IGNORE INTO users(seq, id, password, name,  cellphone,\
address, ssn, CI, DI, birthday, gender,height, size, join_date) \
VALUES("\
    +str(seq)+",'"+fake.email() +"','"\
    +fake.password(length=8, special_chars=False, upper_case=False)\
    +"','"\
    +fake.name()+"','"\
    +fake.phone_number() +"','"\
    +fake.address() +"','"\
    +ssn +"','-','-','"\
    +birthday+"','"\
    +gender+"','"+str(height)+"','"+size+"', '"\
    +str(fake.date_between(start_date='-10y', end_date='-2m'))+"');"
    ret=curs.execute(query)
    print(query)
    if ret == 1:
        seq += 1
    else:
        print("error",seq,"ret",ret)
db.commit()
db.close()

M
182
XL
INSERT IGNORE INTO users(seq, id, password, name,  cellphone,address, ssn, CI, DI, birthday, gender,height, size, join_date) VALUES(995,'jigyeongsug@bagyungim.kr','qo2rla8m','허영숙','016-725-1027','세종특별자치시 서대문구 논현69길','820519-1791907','-','-','1982-05-19','M','182','XL', '2020-09-26');
M
171
L
INSERT IGNORE INTO users(seq, id, password, name,  cellphone,address, ssn, CI, DI, birthday, gender,height, size, join_date) VALUES(996,'seongjini@live.com','1rdlbxa8','김영진','019-649-4205','제주특별자치도 청주시 청원구 삼성거리','390404-1117715','-','-','1939-04-04','M','171','L', '2020-04-19');
M
167
L
INSERT IGNORE INTO users(seq, id, password, name,  cellphone,address, ssn, CI, DI, birthday, gender,height, size, join_date) VALUES(997,'qmin@yu.kr','cxla5oy0','이은영','041-255-9446','울산광역시 북구 학동43길','840603-1464848','-','-','1984-06-03','M','167','L', '2018-03-10');
F
166
M
INSERT IGNORE INTO users(seq, id, password, name,  cellphone,address, ssn, CI, DI, birthday, gender,height, size, join_date) VALUES(998,'coeyeonghwan@live.com','yb0kvqt3','박준혁','054-646-9606','서울특별시 남구 오금30거리','110905-2537215','-','-','1911-09-05','F','166','M', '2019-08-13');
F
165
M
INSERT IGNORE INTO users(seq, id, password, name,  cellphone,address, ssn, CI, DI, birthday, gender,height, size, join_date) VALUES(999,'jihye69@gmail.com','4i70x1w4','정지원','031-331-8123','제주특별자치도 부여군 압구정60가 (수빈박동)','850321-2941300','-','-','1985-03-21','F','165','M', '2016-04-12');
F
173
L
INSERT IGNORE INTO users(seq, id, password, name,  cellphone,address, ssn, CI, DI, birthday, gender,height, size, join_date) VALUES(1000,'seonghyeongim@hanmail.net','69sf40qs','조종수','052-096-0575','경상북도 광주시 영동대거리','000210-2101701','-','-','1900-02-10','F','173','L', '2012-01-01');

In [18]:
import pymysql
from faker import Faker
fake =Faker('ko_KR')
Faker.seed(1234);
import random
for _ in range(6):
    while True:
        ssn=fake.ssn()
        if (ssn[2]=='0' and ssn[3]=='0') or (ssn[4]=='0' and ssn[5]=='0'):
            continue
        break
    if ssn[7]=='1' or ssn[7]=='2':
        birthday= '19'+ssn[0:2]+'-'+ssn[2:4]+'-'+ssn[4:6]
    elif ssn[7]=='3' or ssn[7]=='4':
        birthday= '20'+ssn[0:2]+'-'+ssn[2:4]+'-'+ssn[4:6]
    if ssn[7]=='1' or ssn[7]=='3':
        gender='M'
        height=random.randint(160,190)
        print(gender)
        print(height)
        if height >=190:
            size='2XL'
        elif height >=180:
            size='XL'
        elif height >=170:
            size='L'
        elif height >=170:
            size='M'
        elif height >=170:
            size='S'
        print(size)
    elif ssn[7]=='2' or ssn[7]=='4':
        gender = 'F'
        height=random.randint(150,180)
        print(gender)
        print(height)
        if height >=170:
            size='L'
        elif height >=160:
            size='M'
        elif height >=150:
            size='S'
        print(size)

M
188
XL
F
<class 'int'>
<class 'str'>
F
<class 'int'>
<class 'str'>
F
<class 'int'>
<class 'str'>
M
177
L
M
177
L