In [2]:
import pymysql
import random
from faker import Faker
import datetime
db= pymysql.connect(host='localhost',user='root',password='wnstjr96',db='musinsa')
curs = db.cursor(pymysql.cursors.DictCursor)
query = "select id, price from products"
curs.execute(query)
rows = curs.fetchall()
query2 = "select seq, users_id from credit_cards"
curs.execute(query2)
rows2 = curs.fetchall()
db.close()

delivery_time_type =['10:00','11:00','14:00','17:00','18:00','23:59']
start = datetime.datetime(2020, 9, 7, 12, 0, 0)
end =datetime.datetime(2020, 11, 7, 12, 0, 0)
fake = Faker('ko_KR')

credit_seq_list=[]
for i in range(1, 1001):
    line= []
    for row2 in rows2:
        if i == row2['users_id']:
            line.append(row2['seq'])
    credit_seq_list.append(line)

orders_id_users_seq= []
orders_id= 1
for i in range(1, 200):
    for _ in range(random.randint(4,12)):
        orders_id_users_seq.append([i, orders_id])
        orders_id +=1
for i in range(201, 1001):
    for _ in range(random.randint(1,4)):
        orders_id_users_seq.append([i, orders_id])
        orders_id +=1
last_orders_id = orders_id-1
print('마지막 주문 번호: ', last_orders_id)
orders_id_list = list(range(1, orders_id))
random.shuffle(orders_id_list)

마지막 주문 번호:  3500

In [1]:
import pymysql
import random
from faker import Faker
import datetime
Faker.seed(3);
db= pymysql.connect(host='localhost',user='root',password='root',db='musinsa')
curs = db.cursor(pymysql.cursors.DictCursor)
query = "select id, price from products"
curs.execute(query)
rows = curs.fetchall()
query2 = "select seq, users_id from credit_cards"
curs.execute(query2)
rows2 = curs.fetchall()
db.close()

import pymysql
import random
from faker import Faker
import datetime
db= pymysql.connect(host='localhost',user='root',password='root',db='mall')
curs = db.cursor(pymysql.cursors.DictCursor)
query = "select id, price from products"
curs.execute(query)
rows = curs.fetchall()
query2 = "select seq, users_id from credit_cards"
curs.execute(query2)
rows2 = curs.fetchall()
db.close()

delivery_time_type =['10:00','11:00','14:00','17:00','18:00','23:59']
start = datetime.datetime(2020, 9, 7, 12, 0, 0)
end =datetime.datetime(2020, 11, 7, 12, 0, 0)
fake = Faker('ko_KR')

credit_seq_list=[]
for i in range(1, 1001):
    line= []
    for row2 in rows2:
        if i == row2['users_id']:
            line.append(row2['seq'])
    credit_seq_list.append(line)

orders_id_users_seq= []
orders_id= 1
for i in range(1, 200):
    for _ in range(random.randint(4,12)):
        orders_id_users_seq.append([i, orders_id])
        orders_id +=1
for i in range(201, 1001):
    for _ in range(random.randint(1,4)):
        orders_id_users_seq.append([i, orders_id])
        orders_id +=1
last_orders_id = orders_id-1
#print('마지막 주문 번호: ', last_orders_id)
orders_id_list = list(range(1, orders_id))
random.shuffle(orders_id_list)

users_id =0
for i in range(0,500):
    for j in range(last_orders_id):
        if orders_id_list[i] == orders_id_users_seq[j][1]:
            users_id = orders_id_users_seq[j][0]
    order_time = fake.date_time_between_dates(datetime_start=start, datetime_end=end)
    min_total_price = random.randint(30000,150000)
    total_price=0
    while total_price < min_total_price:
        products_id = random.randint(1,271)
        products_quantity = random.randint(1,5)
        total_price +=rows[products_id-1]['price']*products_quantity
        query4 = "INSERT INTO carts(orders_id, products_id, products_quantity)"\
                +" VALUES("+str(orders_id_list[i])+","+str(products_id)+","\
                +str(products_quantity)+");";
    credit_cards_seq = random.choice(credit_seq_list[users_id-1])
    delivery_day = random.randint(1,6)
    delivery_time = random.choice(delivery_time_type)
    query3 = "INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time)"\
            +" VALUES("+str(orders_id_list[i])+", "+str(users_id)+", '"+str(order_time)+"', "\
            +str(total_price)+", "+str(credit_cards_seq)+", "+str(delivery_day)+", '"\
            +delivery_time+"');";
for i in range(500,1000):
    for j in range(last_orders_id):
        if orders_id_list[i] == orders_id_users_seq[j][1]:
            users_id = orders_id_users_seq[j][0]
    order_time = fake.date_time_between_dates(datetime_start=start, datetime_end=end)
    min_total_price = random.randint(30000,150000)
    total_price=0
    while total_price < min_total_price:
        products_id = random.randint(721,900)
        products_quantity = random.randint(1,4)
        total_price +=rows[products_id-1]['price']*products_quantity
        query4 = "INSERT INTO carts(orders_id, products_id, products_quantity)"\
                +" VALUES("+str(orders_id_list[i])+","+str(products_id)+","\
                +str(products_quantity)+");";
        print(query4)
    credit_cards_seq = random.choice(credit_seq_list[users_id-1])
    delivery_day = random.randint(1,6)
    delivery_time = random.choice(delivery_time_type)
    query3 = "INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time)"\
            +" VALUES("+str(orders_id_list[i])+", "+str(users_id)+", '"+str(order_time)+"', "\
            +str(total_price)+", "+str(credit_cards_seq)+", "+str(delivery_day)+", '"\
            +delivery_time+"');";
    print(query3)
for i in range(1000,3000):
    for j in range(last_orders_id):
        if orders_id_list[i] == orders_id_users_seq[j][1]:
            users_id = orders_id_users_seq[j][0]
    order_time = fake.date_time_between_dates(datetime_start=start, datetime_end=end)
    min_total_price = random.randint(30000,50000)
    total_price=0
    while total_price < min_total_price:
        products_id = random.randint(1,2430)
        products_quantity = random.randint(1,4)
        total_price +=rows[products_id-1]['price']*products_quantity
        query4 = "INSERT INTO carts(orders_id, products_id, products_quantity)"\
                +" VALUES("+str(orders_id_list[i])+","+str(products_id)+","\
                +str(products_quantity)+");";
        print(query4)
    credit_cards_seq = random.choice(credit_seq_list[users_id-1])
    delivery_day = random.randint(1,6)
    delivery_time = random.choice(delivery_time_type)
    query3 = "INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time)"\
            +" VALUES("+str(orders_id_list[i])+", "+str(users_id)+", '"+str(order_time)+"', "\
            +str(total_price)+", "+str(credit_cards_seq)+", "+str(delivery_day)+", '"\
            +delivery_time+"');";
    print(query3)
for i in range(3000,orders_id-1):
    for j in range(last_orders_id):
        if orders_id_list[i] == orders_id_users_seq[j][1]:
            users_id = orders_id_users_seq[j][0]
            #print("[users_id]", orders_id_users_seq[j][0])
            #print("[orders_id]", orders_id_users_seq[j][1])
    order_time = fake.date_time_between_dates(datetime_start=start, datetime_end=end)
    min_total_price = random.randint(20000,200000)
    #print("\n**",i+1," 주문번호:", orders_id_list[i],"[min_total_price]", min_total_price, "원")
    total_price=0
    while total_price < min_total_price:
        products_id = random.randint(1,2430)
        products_quantity = random.randint(1,6)
       # print("\n상품 번호:", products_id)
        #print("상품 가격:",rows[products_id-1]["price"],"원")
        #print("수량:", priducts_quantity,"개")
        #print("상품 가격 * 수량:", rows[products_id-1]["price"]*priducts_quantity,"원")
        total_price += rows[products_id-1]['price']*products_quantity
        query4 ="INSERT INTO carts(orders_id,products_id,products_quantity)"\
               +"VALUES("+str(orders_id_list[i])+","+str(products_id)+","\
               +str(products_quantity)+");";
        print(query4) 
    #print("\n[총 주문가격]",total_price,"원")
    credit_cards=seq = random.choice(credit_seq_list[users_id-1])
    delivery_day = random.randint(1,6)
    delivery_time = random.choice(delivery_time_type)
    query3="INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)"\
    +"VALUES("+str(orders_id_list[i])+","+str(users_id)+",'"+str(order_time)+"',"\
    +str(total_price)+","+str(credit_cards_seq)+","+str(delivery_day)+",'"\
    +delivery_time+"');";
    print(query3)
#print(orders_id_users_seq)

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2275,882,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2275,795,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2275,769,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2275,852,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2275,866,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2275, 485, '2020-09-29 19:00:37', 87920, 947, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3445,793,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3445,896,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3445,830,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3445,873,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3445,726,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3445, 967, '2020-09-30 07:04:26', 142996, 1912, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(744,819,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(744,754,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(744,851,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(744,875,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(744,853,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(744,849,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(744,755,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(744, 94, '2020-09-14 05:23:51', 135120, 184, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(979,733,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(979,885,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(979, 126, '2020-09-28 14:30:47', 555920, 241, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2250,824,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2250,894,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2250,839,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2250,892,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2250,777,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2250, 473, '2020-10-02 04:15:52', 150400, 923, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1818,807,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1818,725,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1818,819,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1818,749,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1818, 302, '2020-10-01 00:06:53', 55580, 588, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(852,834,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(852,855,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(852,752,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(852, 109, '2020-09-25 21:51:14', 46040, 210, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2523,857,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2523,750,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2523,866,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2523,829,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2523,801,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2523, 583, '2020-10-02 14:38:07', 75240, 1133, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1741,776,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1741,900,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1741, 271, '2020-09-20 20:21:03', 456280, 525, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3342,731,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3342,731,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3342,749,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3342,781,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3342,791,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3342,864,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3342,858,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3342, 920, '2020-09-25 16:10:27', 187350, 1814, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2738,763,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2738,900,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2738, 672, '2020-11-06 21:09:03', 456840, 1311, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2600,796,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2600,800,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2600,843,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2600,888,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2600, 615, '2020-09-11 01:39:21', 497560, 1190, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1536,792,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1536,776,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1536,872,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1536,818,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1536,831,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1536, 196, '2020-10-02 06:12:41', 117740, 373, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1828,827,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1828,838,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1828,860,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1828,872,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1828,888,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1828, 307, '2020-09-23 23:27:06', 594680, 597, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(531,880,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(531,755,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(531, 66, '2020-09-11 20:54:33', 127520, 133, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1716,798,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1716,721,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1716,886,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1716, 264, '2020-10-07 22:18:50', 247380, 510, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2850,806,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2850,749,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2850,774,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2850,826,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2850,852,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2850,826,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2850, 720, '2020-09-25 07:02:35', 161840, 1404, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1296,779,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1296,842,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1296,877,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1296, 165, '2020-10-18 14:20:58', 83460, 318, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1568,896,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1568,735,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1568,824,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1568,770,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1568,772,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1568,767,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1568,767,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1568,816,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1568, 204, '2020-09-16 07:56:51', 144960, 390, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3029,804,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3029,774,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3029,869,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3029,737,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3029,893,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3029, 793, '2020-09-15 20:13:14', 82780, 1555, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3135,830,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3135,799,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3135,724,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3135,898,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3135,768,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3135, 834, '2020-09-18 22:53:03', 67580, 1639, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2357,872,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2357,751,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2357,891,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2357,818,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2357, 520, '2020-09-16 11:52:20', 100760, 1009, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2752,806,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2752,801,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2752,789,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2752,856,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2752,776,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2752,747,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2752, 679, '2020-10-03 03:34:27', 121980, 1326, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3282,815,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3282,724,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3282,788,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3282,846,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3282,865,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3282,741,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3282,789,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3282, 891, '2020-10-05 19:51:28', 84480, 1753, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(847,731,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(847,878,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(847,724,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(847, 108, '2020-09-11 00:10:42', 59380, 208, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(836,824,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(836,784,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(836,755,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(836,773,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(836, 106, '2020-10-12 03:04:50', 94660, 206, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3063,877,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3063,824,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3063,755,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3063,871,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3063,766,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3063,770,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3063,831,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3063, 806, '2020-10-21 10:04:05', 117360, 1582, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3360,778,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3360,780,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3360,768,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3360,887,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3360,900,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3360, 927, '2020-11-02 20:11:49', 179840, 1826, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3424,844,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3424,805,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3424, 954, '2020-10-10 04:25:58', 51560, 1883, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2445,768,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2445,796,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2445,819,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2445,895,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2445,877,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2445,738,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2445,784,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2445,740,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2445,733,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2445,872,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2445, 551, '2020-09-08 04:02:24', 159640, 1068, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2211,739,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2211,738,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2211,832,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2211,889,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2211,762,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2211,746,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2211, 458, '2020-09-10 08:28:12', 126040, 894, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(555,732,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(555,865,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(555,725,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(555,881,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(555,827,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(555,874,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(555, 69, '2020-10-10 00:08:42', 264680, 136, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(55,784,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(55,810,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(55,735,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(55,821,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(55,804,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(55,800,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(55, 8, '2020-10-09 16:22:48', 127880, 13, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2835,840,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2835,870,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2835,721,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2835,778,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2835,731,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2835,802,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2835, 714, '2020-10-19 20:28:09', 105900, 1393, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2666,725,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2666,733,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2666,877,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2666,861,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2666, 642, '2020-10-14 08:42:30', 65900, 1246, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(940,841,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(940,894,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(940,838,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(940,874,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(940, 121, '2020-10-24 16:13:49', 213500, 233, 1, '18:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3070,785,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3070,782,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3070,822,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3070,836,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3070,833,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3070, 809, '2020-09-17 21:42:52', 87180, 1586, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1471,780,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1471,723,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1471,744,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1471,726,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1471, 188, '2020-10-10 08:49:58', 130380, 357, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(400,833,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(400,870,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(400,727,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(400,768,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(400,879,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(400,746,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(400,762,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(400,810,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(400, 50, '2020-11-01 10:59:09', 114940, 101, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3486,869,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3486,804,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3486, 985, '2020-10-29 13:21:37', 46400, 1947, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3484,874,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3484, 984, '2020-10-28 12:55:27', 149400, 1945, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(955,781,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(955,723,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(955,845,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(955,799,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(955,823,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(955,883,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(955, 122, '2020-09-18 11:59:56', 141020, 235, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2118,793,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2118,750,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2118,832,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2118,787,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2118, 426, '2020-10-25 10:49:31', 71718, 834, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1610,879,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1610,815,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1610,772,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1610,898,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1610,841,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1610,790,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1610,796,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1610, 222, '2020-10-26 21:19:01', 134840, 429, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2143,842,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2143,853,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2143,854,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2143,778,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2143,865,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2143, 436, '2020-10-11 16:35:13', 107700, 851, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2816,811,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2816,805,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2816,731,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2816,793,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2816,824,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2816, 705, '2020-09-13 06:41:56', 136198, 1378, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2935,746,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2935,726,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2935,747,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2935,853,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2935, 753, '2020-10-06 02:03:24', 87700, 1467, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2653,728,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2653,806,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2653,875,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2653, 637, '2020-11-01 11:47:15', 53780, 1234, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2637,865,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2637,890,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2637, 629, '2020-09-25 04:02:37', 55100, 1215, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2399,846,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2399,836,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2399,771,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2399,827,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2399,878,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2399,757,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2399, 536, '2020-09-22 00:27:28', 113960, 1033, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1327,815,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1327,900,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1327, 169, '2020-09-24 21:20:36', 230980, 324, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3109,898,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3109,744,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3109,828,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3109, 822, '2020-10-13 11:58:42', 68360, 1613, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(174,832,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(174,883,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(174,842,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(174,724,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(174,760,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(174,748,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(174,890,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(174,812,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(174,795,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(174,815,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(174, 22, '2020-10-21 14:27:02', 151770, 44, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(113,817,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(113,826,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(113,783,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(113, 15, '2020-09-19 10:54:56', 103100, 28, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3014,861,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3014,757,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3014,734,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3014,737,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3014,843,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3014,797,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3014, 786, '2020-09-18 00:09:40', 132300, 1540, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2685,725,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2685,822,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2685,872,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2685,892,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2685,755,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2685,850,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2685, 652, '2020-10-31 20:23:06', 67260, 1267, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3329,867,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3329, 914, '2020-09-21 05:26:57', 107800, 1802, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(72,790,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(72,878,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(72,739,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(72,882,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(72, 9, '2020-10-09 16:31:14', 79140, 17, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1339,749,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1339,883,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1339,891,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1339, 170, '2020-11-04 12:07:09', 89080, 325, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2258,738,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2258,883,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2258,721,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2258, 477, '2020-10-18 06:59:28', 40740, 932, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(805,864,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(805,769,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(805,746,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(805,755,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(805,871,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(805,782,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(805,731,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(805,725,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(805,866,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(805,900,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(805, 102, '2020-10-31 09:03:58', 569140, 201, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(348,846,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(348,831,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(348,799,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(348, 44, '2020-10-06 16:22:12', 72600, 89, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(521,885,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(521, 65, '2020-09-25 15:30:55', 405000, 128, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3067,797,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3067,870,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3067,785,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3067, 807, '2020-10-21 22:31:38', 82280, 1584, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1393,747,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1393,852,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1393,842,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1393,787,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1393,763,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1393,894,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1393, 177, '2020-10-24 08:00:33', 100440, 342, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2320,873,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2320,744,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2320,894,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2320, 502, '2020-10-07 20:02:39', 76220, 983, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2831,781,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2831,816,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2831,776,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2831,859,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2831,780,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2831,881,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2831,810,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2831, 712, '2020-09-24 14:59:52', 97310, 1390, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2165,854,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2165,850,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2165,749,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2165,883,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2165,776,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2165,883,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2165, 442, '2020-09-14 03:50:27', 84860, 863, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(204,730,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(204,784,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(204,858,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(204,877,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(204,753,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(204, 27, '2020-09-17 22:18:32', 116700, 56, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1693,780,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1693,736,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1693, 257, '2020-09-25 02:18:45', 67520, 498, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2858,742,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2858,768,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2858,767,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2858,848,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2858,900,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2858, 724, '2020-10-31 06:17:05', 276640, 1418, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1047,730,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1047,856,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1047,864,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1047,896,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1047, 134, '2020-10-30 05:35:47', 129750, 261, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3113,740,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3113,822,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3113,817,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3113,809,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3113,837,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3113,890,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3113, 823, '2020-11-02 09:50:46', 144640, 1615, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(881,850,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(881,848,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(881,808,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(881,788,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(881,805,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(881,779,4);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(308,789,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(308,754,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(308,797,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(308, 39, '2020-10-14 17:20:21', 58540, 79, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2160,790,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2160,898,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2160,853,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2160,822,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2160, 441, '2020-09-12 16:36:02', 72460, 862, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2905,887,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2905,838,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2905,737,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2905,869,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2905,757,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2905,844,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2905, 741, '2020-09-20 18:07:24', 102920, 1444, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1574,844,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1574,875,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1574,727,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1574,826,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1574, 206, '2020-09-11 14:07:31', 117220, 395, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1191,863,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1191,819,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1191,805,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1191, 154, '2020-10-23 23:26:58', 121440, 296, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1079,724,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1079,844,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1079,879,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1079,771,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1079,820,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1079,771,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1079,849,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1079, 138, '2020-10-26 12:03:49', 151980, 270, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(275,802,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(275,797,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(275, 36, '2020-10-03 20:06:01', 70800, 74, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(522,798,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(522,859,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(522,858,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(522,803,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(522,747,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(522, 65, '2020-10-01 12:00:32', 187440, 128, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1466,820,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1466, 188, '2020-10-27 11:23:14', 49600, 357, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2333,843,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2333,762,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2333,876,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2333,800,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2333,849,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2333,887,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2333, 507, '2020-10-11 21:08:04', 153980, 990, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3479,785,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3479,734,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3479,824,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3479,820,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3479, 982, '2020-10-09 19:37:34', 163640, 1941, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(937,900,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(937, 121, '2020-10-16 15:50:51', 450000, 233, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1882,807,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1882,779,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1882,871,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1882,891,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1882,730,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1882,886,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1882, 328, '2020-10-21 00:27:23', 191380, 639, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(359,784,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(359,836,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(359,774,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(359,844,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(359,880,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(359,895,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(359,810,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(359, 46, '2020-10-30 01:46:55', 138360, 93, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2056,727,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2056,746,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2056,810,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2056,868,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2056,766,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2056,724,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2056, 399, '2020-09-14 05:18:48', 91100, 786, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2861,757,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2861,873,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2861,746,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2861,736,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2861,815,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2861,885,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2861, 725, '2020-10-11 18:16:50', 209420, 1419, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1633,891,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1633,772,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1633,786,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1633,875,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1633,900,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1633, 232, '2020-10-25 20:26:14', 393780, 454, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,878,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,725,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,763,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,752,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,760,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,723,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,797,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,819,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,847,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,809,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2447,785,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2447, 552, '2020-09-18 09:17:02', 148650, 1070, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3180,729,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3180,757,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3180,789,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3180,728,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3180,836,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3180,897,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3180, 851, '2020-09-22 05:12:46', 143720, 1672, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(32,804,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(32,825,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(32,748,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(32,795,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(32,831,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(32, 5, '2020-10-03 18:16:53', 132100, 9, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2712,787,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2712,857,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2712,820,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2712, 662, '2020-11-03 19:04:35', 118280, 1287, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3042,899,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3042, 798, '2020-09-17 04:11:53', 239600, 1565, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(353,866,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(353,853,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(353,841,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(353,884,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(353,802,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(353,828,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(353, 45, '2020-09-18 10:34:28', 146120, 91, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1110,760,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1110,866,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1110,737,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1110,829,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1110,860,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1110,752,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1110,789,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1110, 143, '2020-11-01 07:03:02', 114910, 280, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(894,788,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(894,736,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(894,897,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(894, 116, '2020-09-18 09:11:42', 70980, 225, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1311,861,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1311,733,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1311,798,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1311, 166, '2020-09-25 10:43:20', 49600, 319, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1909,762,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1909,766,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1909,784,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1909,776,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1909, 339, '2020-09-25 20:47:48', 57520, 661, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3229,783,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3229,823,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3229,721,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3229,823,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3229,887,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3229,897,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3229, 871, '2020-11-01 13:25:10', 135760, 1711, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2059,724,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2059,766,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2059,811,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2059,830,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2059,826,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2059, 400, '2020-10-17 22:52:38', 142280, 788, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2009,855,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2009,758,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2009,726,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2009, 378, '2020-10-15 11:31:35', 87520, 741, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3216,869,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3216,793,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3216,819,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3216,875,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3216,728,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3216, 864, '2020-09-19 23:22:16', 85856, 1696, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1711,787,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1711,812,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1711,767,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1711,749,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1711,869,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1711,797,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1711, 263, '2020-11-03 23:15:53', 126920, 508, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2919,726,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2919,837,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2919,849,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2919, 747, '2020-11-05 12:29:44', 73700, 1455, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3392,843,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3392,892,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3392,871,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3392,889,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3392,832,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3392,739,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3392,893,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3392,850,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3392,857,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3392, 942, '2020-09-21 17:18:09', 149640, 1858, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(898,872,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(898,774,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(898,767,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(898,754,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(898,733,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(898,873,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(898,723,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(898,806,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(898,864,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(898,755,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(898, 116, '2020-10-16 04:23:04', 119470, 224, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1503,812,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1503,736,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1503,823,3);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1367,849,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1367,882,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1367,815,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1367,852,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1367,746,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1367,873,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1367,789,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1367, 173, '2020-11-04 21:16:46', 139080, 332, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2758,887,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2758,841,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2758,728,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2758,849,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2758,896,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2758, 682, '2020-09-25 23:51:46', 90120, 1335, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(553,834,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(553,799,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(553,746,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(553,856,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(553,811,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(553, 69, '2020-09-07 17:31:45', 122800, 136, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3417,769,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3417,886,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3417, 952, '2020-09-17 22:27:10', 232000, 1879, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2734,745,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2734,760,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2734,829,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2734,870,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2734,832,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2734,758,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2734,809,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2734,736,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2734,824,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2734, 671, '2020-09-30 04:47:02', 114650, 1309, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1172,815,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1172,879,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1172,735,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1172,892,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1172,783,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1172,843,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1172, 152, '2020-10-25 06:08:45', 104160, 294, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2965,894,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2965,892,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2965,739,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2965,826,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2965,794,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2965,726,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2965, 764, '2020-09-24 07:22:14', 147100, 1491, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1921,815,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1921,749,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1921,792,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1921,792,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1921,889,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1921, 345, '2020-10-28 08:10:08', 85540, 674, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(10,729,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(10,880,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(10,881,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(10,871,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(10,856,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(10,830,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(10, 2, '2020-11-07 04:24:08', 126980, 3, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1896,742,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1896,800,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1896,810,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1896,742,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1896,766,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1896,733,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1896,758,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1896,762,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1896,870,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1896, 333, '2020-10-22 05:07:14', 116080, 647, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2589,729,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2589,765,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2589,850,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2589,794,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2589,885,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2589, 609, '2020-09-26 19:29:13', 449860, 1177, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3353,847,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3353,731,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3353,786,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3353,827,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3353,808,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3353,784,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3353,872,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3353,898,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3353, 924, '2020-09-26 06:44:22', 133700, 1823, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3461,749,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3461,833,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3461,856,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3461, 972, '2020-10-28 21:56:09', 86720, 1920, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1482,758,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1482,781,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1482,831,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1482,835,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1482,771,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1482,790,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1482,734,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1482, 190, '2020-09-28 01:44:26', 129040, 360, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2990,788,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2990,727,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2990,776,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2990,787,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2990,757,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2990,878,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2990,852,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2990,849,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2990,806,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2990, 777, '2020-09-11 02:21:40', 162980, 1518, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1483,888,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1483, 190, '2020-10-26 02:07:34', 270000, 360, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1548,856,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1548,779,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1548,893,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1548,788,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1548,852,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1548,731,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1548,823,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1548,845,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1548, 198, '2020-10-20 15:06:46', 148900, 379, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2611,899,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2611,891,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2611,721,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2611,869,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2611, 619, '2020-09-18 07:59:07', 143540, 1198, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2979,817,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2979,765,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2979,742,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2979,783,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2979,862,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2979,768,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2979,737,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2979, 769, '2020-11-01 10:53:10', 134580, 1504, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3399,784,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3399,875,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3399,768,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3399,780,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3399,811,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3399, 944, '2020-10-05 00:01:38', 135080, 1862, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(300,863,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(300,723,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(300,814,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(300,864,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(300,894,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(300,735,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(300,844,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(300,795,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(300,793,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(300,749,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(300, 39, '2020-09-22 07:36:18', 144802, 79, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2862,834,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2862,804,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2862,749,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2862,828,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2862,780,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2862,757,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2862, 726, '2020-09-20 15:56:32', 121980, 1420, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(299,893,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(299,795,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(299,811,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(299,753,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(299, 38, '2020-10-22 20:44:55', 147920, 77, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3173,897,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3173,835,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3173,892,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3173,734,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3173,721,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3173,807,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3173, 848, '2020-09-16 02:46:05', 155160, 1667, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2491,819,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2491,835,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2491,867,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2491, 571, '2020-11-07 00:20:33', 245260, 1113, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(183,818,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(183,831,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(183,749,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(183,750,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(183,883,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(183, 24, '2020-09-12 09:55:22', 151800, 49, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3280,807,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3280,764,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3280,739,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3280,832,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3280,783,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3280,742,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3280, 890, '2020-09-09 23:27:33', 91800, 1751, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2847,776,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2847,886,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2847, 719, '2020-10-12 10:37:48', 472560, 1402, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3388,756,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3388,807,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3388,727,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3388, 941, '2020-11-06 12:50:35', 62640, 1856, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3170,817,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3170,852,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3170,792,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3170,768,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3170,830,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3170,897,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3170, 847, '2020-09-30 03:53:36', 135040, 1666, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1583,731,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1583,813,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1583, 209, '2020-10-26 14:57:28', 58340, 401, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(977,895,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(977,821,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(977,783,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(977,895,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(977,783,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(977,834,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(977,885,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(977, 126, '2020-09-15 01:22:18', 637960, 241, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(882,723,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(882,799,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(882,765,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(882,799,3);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3267,791,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3267,770,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3267,808,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3267,791,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3267,771,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3267,726,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3267, 886, '2020-09-25 00:48:10', 126440, 1744, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(518,754,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(518,896,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(518,760,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(518,741,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(518,865,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(518,868,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(518,833,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(518, 64, '2020-10-21 17:06:10', 153640, 127, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2784,871,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2784,810,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2784,784,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2784,788,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2784,884,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2784,877,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2784,753,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2784, 694, '2020-09-11 02:46:32', 133460, 1355, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2625,794,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2625,755,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2625,756,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2625,742,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2625, 625, '2020-10-02 09:59:13', 69760, 1208, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2595,884,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2595,759,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2595,757,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2595,833,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2595,762,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2595,819,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2595,786,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2595, 612, '2020-10-13 03:00:55', 128720, 1182, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(289,757,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(289,732,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(289,768,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(289,729,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(289,865,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(289,843,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(289,864,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(289,811,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(289,814,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(289, 38, '2020-10-13 12:25:48', 119690, 76, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(261,750,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(261,873,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(261,828,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(261,852,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(261,749,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(261, 34, '2020-10-20 23:19:20', 122040, 71, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(920,881,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(920,837,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(920,723,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(920,865,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(920,868,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(920,860,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(920,873,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(920,786,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(920,805,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(920, 118, '2020-10-28 21:25:51', 174440, 229, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(679,891,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(679,874,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(679,867,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(679, 84, '2020-10-12 14:25:24', 179200, 168, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(806,748,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(806,861,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(806,792,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(806,735,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(806,900,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(806, 102, '2020-11-04 09:53:08', 162780, 201, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(832,818,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(832,810,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(832,895,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(832,812,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(832,802,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(832, 106, '2020-10-16 12:17:00', 107140, 206, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1591,794,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1591,729,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1591,834,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1591, 214, '2020-09-29 05:36:04', 64600, 407, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(797,864,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(797,782,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(797,881,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(797,865,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(797,842,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(797, 101, '2020-09-07 18:17:33', 87910, 200, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2121,732,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2121,800,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2121,771,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2121, 428, '2020-09-27 18:59:37', 55540, 837, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2745,891,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2745,773,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2745, 676, '2020-10-02 14:45:09', 68320, 1319, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1953,802,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1953,732,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1953,754,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1953, 356, '2020-10-13 09:18:01', 64040, 693, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3401,885,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3401, 944, '2020-09-21 10:19:33', 540000, 1861, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1733,748,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1733,736,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1733,895,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1733,757,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1733,846,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1733,814,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1733, 269, '2020-10-22 03:50:56', 122320, 520, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3298,730,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3298,770,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3298,809,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3298,883,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3298,813,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3298, 896, '2020-10-29 07:53:39', 93340, 1765, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(43,883,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(43,801,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(43,777,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(43,781,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(43, 6, '2020-09-26 11:04:51', 108600, 10, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(576,807,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(576,874,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(576,847,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(576, 72, '2020-09-22 22:42:48', 112420, 140, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2713,874,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2713, 662, '2020-09-27 19:40:30', 199200, 1287, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(396,730,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(396,837,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(396,737,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(396,845,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(396, 50, '2020-09-09 15:47:34', 106000, 101, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(164,730,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(164,790,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(164,762,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(164,792,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(164,808,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(164,799,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(164,807,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(164,836,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(164, 21, '2020-09-24 01:54:31', 158120, 42, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2214,826,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2214,795,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2214,723,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2214,827,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2214, 459, '2020-11-03 06:03:01', 83460, 896, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1682,848,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1682,803,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1682,799,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1682,860,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1682,797,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1682,760,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1682,811,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1682, 253, '2020-10-16 16:47:57', 137380, 492, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2327,815,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2327,786,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2327,796,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2327,737,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2327,736,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2327,746,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2327,889,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2327, 505, '2020-10-26 09:35:44', 113900, 986, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1626,779,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1626,772,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1626,868,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1626,878,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1626,868,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1626,799,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1626,770,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1626,802,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1626, 230, '2020-09-23 20:06:39', 135360, 447, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2329,805,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2329,797,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2329,761,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2329,750,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2329, 506, '2020-09-10 04:02:21', 123080, 988, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2556,797,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2556,783,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2556,810,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2556,817,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2556,729,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2556,872,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2556,747,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2556, 595, '2020-09-21 00:29:47', 157440, 1154, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1989,856,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1989,844,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1989,829,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1989,863,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1989,824,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1989,758,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1989,788,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1989,871,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1989,728,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1989,896,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1989, 372, '2020-09-18 04:28:48', 151800, 728, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1280,845,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1280,736,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1280,771,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1280,826,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1280, 163, '2020-11-05 14:19:49', 117680, 314, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1722,848,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1722,832,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1722,770,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1722,726,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1722, 266, '2020-09-23 20:00:40', 139140, 515, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3301,765,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3301,798,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3301,814,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3301, 898, '2020-10-20 11:39:37', 85060, 1770, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3374,897,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3374, 935, '2020-10-25 02:25:26', 45600, 1845, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2129,883,1);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3451,758,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3451, 969, '2020-09-25 20:38:47', 60420, 1917, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(730,900,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(730, 91, '2020-10-26 23:45:08', 450000, 180, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1658,758,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1658,829,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1658,879,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1658,757,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1658,867,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1658, 242, '2020-10-09 15:51:13', 199920, 468, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1291,732,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1291,861,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1291,868,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1291,800,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1291,840,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1291,767,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1291,776,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1291,776,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1291, 164, '2020-09-26 23:38:17', 142260, 317, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2668,746,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2668,851,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2668,869,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2668,828,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2668,849,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2668, 644, '2020-10-23 19:12:21', 152880, 1250, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(16,882,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(16, 3, '2020-10-10 12:13:04', 47600, 5, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1586,838,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1586,831,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1586,787,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1586,815,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1586, 210, '2020-10-23 23:18:01', 79700, 403, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(358,842,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(358,877,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(358,767,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(358,837,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(358,850,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(358,812,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(358,838,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(358,779,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(358, 46, '2020-10-11 15:09:04', 138680, 93, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1717,767,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1717,854,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1717,881,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1717,755,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1717,788,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1717,745,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1717,806,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1717, 264, '2020-09-10 19:43:09', 131840, 510, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(599,792,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(599,789,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(599,739,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(599,840,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(599,782,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(599,871,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(599,861,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(599, 76, '2020-10-14 14:51:12', 98660, 149, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3447,745,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3447,828,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3447,815,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3447,778,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3447, 968, '2020-10-07 02:03:21', 65440, 1915, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(462,728,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(462,854,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(462,840,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(462,876,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(462,884,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(462,859,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(462, 58, '2020-11-05 10:15:18', 106440, 118, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2311,803,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2311,767,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2311,760,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2311,835,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2311,865,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2311,855,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2311,736,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2311,798,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2311, 498, '2020-10-15 18:54:53', 152460, 972, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(489,845,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(489, 60, '2020-09-16 00:32:27', 41700, 122, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(467,736,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(467,732,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(467,724,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(467,744,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(467,753,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(467,787,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(467,772,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(467, 58, '2020-10-05 23:44:58', 164720, 118, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2974,829,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2974,807,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2974,788,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2974,733,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2974,807,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2974,762,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2974,850,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2974, 767, '2020-09-25 09:00:31', 96240, 1499, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(59,789,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(59,809,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(59,731,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(59,736,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(59, 8, '2020-10-17 14:30:24', 73620, 14, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2651,721,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2651,734,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2651,755,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2651,761,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2651,801,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2651, 636, '2020-09-18 15:12:32', 57920, 1232, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1005,892,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1005,734,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1005,734,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1005,754,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1005,746,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1005, 129, '2020-10-26 18:30:37', 86640, 248, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3257,783,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3257,847,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3257,854,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3257,844,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3257,789,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3257, 882, '2020-10-15 08:26:51', 97100, 1736, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(716,764,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(716,873,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(716,886,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(716, 89, '2020-10-30 15:12:55', 494880, 178, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3330,741,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3330,828,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3330,757,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3330,868,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3330,792,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3330,749,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3330, 915, '2020-10-09 22:42:02', 91340, 1803, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(828,815,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(828,792,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(828,897,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(828,835,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(828,799,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(828,877,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(828,825,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(828,810,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(828,868,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(828,811,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(828, 105, '2020-10-29 14:10:26', 165500, 205, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(191,881,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(191,758,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(191,727,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(191,885,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(191, 25, '2020-10-16 14:36:16', 359100, 52, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2952,864,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2952,803,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2952,834,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2952, 760, '2020-09-24 10:55:10', 53380, 1480, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1454,747,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1454, 186, '2020-10-14 23:07:41', 59700, 354, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1977,838,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1977,795,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1977,760,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1977,794,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1977,851,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1977,889,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1977,856,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1977, 366, '2020-10-31 05:22:03', 96410, 714, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3288,839,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3288,832,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3288,730,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3288,837,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3288,801,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3288,879,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3288,786,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3288,723,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3288,900,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3288, 893, '2020-10-12 09:04:53', 450900, 1758, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1983,739,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1983,796,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1983,819,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1983, 370, '2020-09-25 08:35:04', 45420, 723, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2340,895,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2340,797,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2340,795,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2340,832,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2340,814,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2340,890,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2340, 512, '2020-10-12 17:26:40', 150920, 996, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1876,883,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1876,759,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1876,806,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1876,791,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1876,888,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1876, 326, '2020-10-17 18:22:27', 331820, 636, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(776,850,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(776,897,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(776, 98, '2020-10-20 01:39:32', 89340, 195, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3460,803,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3460,896,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3460,788,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3460,879,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3460,729,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3460, 972, '2020-09-29 18:33:07', 133920, 1920, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1286,851,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1286,851,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1286,736,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1286,795,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1286,754,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1286,835,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1286,754,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1286,830,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1286,862,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1286,835,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1286, 164, '2020-10-20 15:42:40', 124040, 316, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1006,806,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1006,752,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1006,792,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1006,802,3);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(258,745,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(258,738,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(258,787,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(258,828,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(258, 34, '2020-10-18 05:47:20', 109640, 71, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1859,865,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1859,827,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1859,852,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1859,790,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1859,738,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1859,772,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1859,739,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1859,865,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1859,772,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1859, 320, '2020-10-26 12:35:57', 149280, 623, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2137,873,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2137,865,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2137,879,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2137,823,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2137,849,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2137,839,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2137,816,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2137,737,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2137,838,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2137, 434, '2020-11-05 04:14:41', 164420, 849, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1490,755,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1490,732,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1490,789,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1490,839,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1490,884,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1490,884,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1490,752,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1490,730,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1490,770,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1490, 191, '2020-10-08 11:07:43', 147760, 363, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1310,872,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1310,857,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1310,864,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1310,761,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1310,900,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1310, 166, '2020-10-29 11:09:09', 283380, 319, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3469,864,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3469,834,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3469,841,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3469,900,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3469, 976, '2020-09-25 18:26:39', 475150, 1927, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3171,776,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3171,883,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3171,801,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3171,838,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3171, 847, '2020-10-22 21:19:07', 70920, 1665, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,833,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,887,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,803,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,782,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,731,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,849,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,839,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,830,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,760,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,877,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,819,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1675,742,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1675, 249, '2020-09-24 17:51:38', 143240, 482, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1651,854,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1651,854,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1651,883,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1651,872,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1651,744,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1651,865,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1651,864,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1651,866,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1651, 239, '2020-11-06 22:16:43', 161160, 465, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2131,854,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2131,734,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2131,851,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2131,809,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2131,766,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2131,892,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2131,808,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2131,805,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2131, 432, '2020-09-15 04:22:54', 173860, 845, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(283,817,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(283,790,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(283,799,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(283,836,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(283,882,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(283,748,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(283, 37, '2020-09-11 12:16:41', 115500, 75, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(422,802,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(422,858,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(422,864,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(422,857,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(422,810,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(422, 53, '2020-09-18 10:13:07', 116930, 108, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(818,887,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(818,785,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(818,889,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(818,784,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(818,850,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(818,784,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(818,724,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(818,869,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(818, 104, '2020-11-04 13:47:30', 156000, 203, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2705,851,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2705,849,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2705,849,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2705,759,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2705,891,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2705, 659, '2020-09-09 19:54:40', 137780, 1279, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3087,870,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3087,883,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3087,896,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3087,741,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3087,742,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3087, 815, '2020-09-17 08:17:20', 61180, 1594, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3118,759,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3118,828,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3118,843,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3118, 825, '2020-09-26 20:18:07', 75000, 1620, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3208,761,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3208,862,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3208,832,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3208,863,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3208,880,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3208, 861, '2020-10-02 06:16:31', 96980, 1689, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2325,900,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2325, 504, '2020-09-15 19:51:50', 337500, 985, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3199,781,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3199,771,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3199,822,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3199,876,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3199,798,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3199,735,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3199, 858, '2020-09-18 02:06:28', 90520, 1684, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1026,819,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1026,796,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1026,870,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1026,819,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1026,817,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1026,876,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1026,815,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1026,882,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1026, 132, '2020-10-22 16:04:31', 108520, 257, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2601,897,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2601, 616, '2020-10-16 06:02:07', 45600, 1192, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(800,846,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(800,866,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(800,820,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(800,802,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(800,737,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(800, 101, '2020-09-29 03:03:04', 149500, 200, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1069,829,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1069,877,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1069,822,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1069,858,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1069, 137, '2020-11-06 06:02:08', 129260, 268, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(739,884,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(739,793,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(739,796,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(739, 92, '2020-09-18 01:37:22', 64636, 181, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(609,788,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(609,759,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(609,819,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(609,737,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(609, 77, '2020-10-24 15:29:30', 60580, 152, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3091,721,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3091,731,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3091,846,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3091,897,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3091,899,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3091, 816, '2020-10-11 02:21:06', 203720, 1597, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(202,847,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(202, 27, '2020-10-16 14:43:53', 51600, 56, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2166,823,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2166,745,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2166,827,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2166,845,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2166,848,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2166, 443, '2020-11-05 01:20:25', 118960, 864, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3276,797,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3276,768,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3276,828,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3276,789,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3276,887,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3276, 889, '2020-10-20 18:18:54', 117240, 1750, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2010,817,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2010,886,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2010, 378, '2020-09-18 06:31:09', 269520, 740, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2106,810,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2106,884,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2106,847,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2106,804,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2106,767,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2106,889,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2106, 421, '2020-10-05 20:05:53', 101540, 826, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2066,823,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2066,725,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2066,726,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2066,878,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2066,729,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2066,738,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2066,814,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2066,842,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2066, 405, '2020-11-04 05:02:36', 158140, 796, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(992,774,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(992,759,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(992,804,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(992,875,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(992,876,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(992, 128, '2020-10-20 13:54:22', 97000, 245, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3271,888,2);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3310,725,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3310,738,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3310,845,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3310,892,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3310,809,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3310, 904, '2020-10-23 01:45:48', 118880, 1781, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3441,744,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3441,853,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3441, 965, '2020-11-03 13:08:30', 49360, 1907, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1969,808,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1969,781,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1969,739,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1969,814,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1969,824,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1969, 363, '2020-09-10 21:28:32', 126500, 709, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(221,844,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(221,867,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(221,792,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(221,839,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(221,748,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(221, 29, '2020-10-05 20:30:40', 134940, 63, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(817,787,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(817,850,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(817,760,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(817,765,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(817,817,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(817,787,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(817, 104, '2020-09-09 06:13:12', 87430, 203, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1579,868,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1579,733,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1579,833,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1579,805,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1579,894,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1579,759,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1579, 208, '2020-09-25 10:06:54', 118720, 400, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(171,859,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(171,745,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(171,752,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(171,847,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(171,830,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(171,775,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(171, 22, '2020-09-16 19:23:13', 114100, 45, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3292,790,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3292,863,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3292,795,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3292,787,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3292,765,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3292, 895, '2020-09-10 05:52:29', 87180, 1763, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2081,809,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2081,895,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2081,790,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2081,844,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2081,877,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2081, 411, '2020-09-22 03:07:22', 119360, 807, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1450,753,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1450,872,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1450,748,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1450,768,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1450,800,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1450,726,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1450, 185, '2020-10-06 01:45:45', 130780, 353, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2078,831,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2078,855,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2078,866,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2078,812,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2078,786,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2078,871,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2078, 409, '2020-10-26 09:17:27', 122880, 805, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2649,743,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2649,779,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2649,875,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2649,838,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2649,721,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2649, 635, '2020-10-27 22:25:19', 107400, 1230, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(179,736,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(179,865,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(179,726,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(179, 23, '2020-09-13 10:59:38', 76560, 47, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(592,775,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(592,755,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(592,773,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(592,845,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(592,829,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(592,781,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(592,770,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(592, 75, '2020-10-23 08:03:59', 141680, 146, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(715,756,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(715,893,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(715, 88, '2020-09-11 10:30:58', 175600, 175, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2857,735,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2857,841,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2857,767,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2857,846,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2857,738,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2857,849,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2857,760,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2857,896,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2857, 724, '2020-09-26 09:57:07', 89820, 1417, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2800,1820,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2800,1720,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2800,4,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2800, 699, '2020-09-27 15:07:53', 81580, 1365, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(834,1110,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(834,1375,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(834,2056,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(834,1138,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(834,489,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(834, 106, '2020-10-04 07:05:15', 55785, 206, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1355,1885,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1355, 172, '2020-10-25 05:52:13', 91068, 331, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1368,1620,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1368,742,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1368,688,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1368, 173, '2020-10-19 11:33:07', 48700, 332, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2916,1492,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2916,1358,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2916,1040,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2916, 745, '2020-09-11 03:40:19', 48060, 1450, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2113,143,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2113, 424, '2020-10-10 23:24:55', 79900, 831, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3334,774,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3334,1831,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3334,1361,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3334,129,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3334, 917, '2020-10-22 22:57:59', 110496, 1808, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2671,906,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2671,947,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2671, 644, '2020-09-26 14:25:56', 32940, 1250, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(713,2263,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(713,2266,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(713,1916,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(713, 88, '2020-10-05 09:27:53', 51760, 177, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2554,330,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2554, 595, '2020-09-21 09:06:52', 55520, 1154, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2628,744,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2628,1216,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2628,955,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2628,1721,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2628, 626, '2020-09-17 12:51:00', 73020, 1210, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1162,1974,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1162,1117,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1162, 150, '2020-10-20 14:45:16', 98220, 291, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3179,2425,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3179,1759,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3179, 850, '2020-10-06 13:29:50', 64200, 1670, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(339,1207,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(339,323,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(339, 43, '2020-10-17 09:53:13', 171960, 87, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3368,959,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3368,2004,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3368,2343,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3368, 932, '2020-10-20 14:14:18', 77670, 1840, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1809,1146,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1809,578,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1809,2335,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1809,1692,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1809, 299, '2020-09-15 00:43:20', 54880, 585, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1395,85,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1395,1775,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1395,1400,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1395,2399,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1395,1073,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1395, 178, '2020-09-27 11:06:01', 46900, 343, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2788,1267,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2788,211,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2788, 695, '2020-09-22 09:00:31', 52780, 1357, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2863,757,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2863,507,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2863, 726, '2020-10-24 19:30:43', 45040, 1420, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(765,2350,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(765,1809,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(765,2370,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(765,2296,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(765, 96, '2020-10-05 02:34:12', 63360, 191, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1278,1641,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1278,973,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1278,1364,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1278,565,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1278, 163, '2020-10-13 21:49:38', 57040, 313, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1654,1204,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1654,1212,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1654,1378,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1654,1083,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1654, 240, '2020-10-13 16:10:33', 37500, 466, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1421,824,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1421,1237,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1421,1600,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1421, 181, '2020-09-23 03:57:45', 46820, 347, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(914,1631,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(914,2401,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(914,398,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(914,1035,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(914, 118, '2020-10-19 08:59:16', 51760, 229, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3237,1729,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3237,1309,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3237,1598,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3237, 875, '2020-10-07 18:52:21', 71360, 1717, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1447,1500,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1447,2233,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1447,1,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1447,630,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1447,780,1);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2486,1537,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2486,1114,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2486,1334,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2486,2009,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2486,319,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2486,1547,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2486, 568, '2020-10-01 12:05:38', 44780, 1105, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(931,2137,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(931,361,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(931, 120, '2020-10-25 21:50:36', 54900, 232, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2301,2040,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2301,1926,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2301,967,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2301,1128,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2301, 494, '2020-10-18 02:31:12', 108860, 964, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2392,157,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2392,1804,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2392,396,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2392,1685,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2392, 534, '2020-10-02 18:40:15', 64640, 1029, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1785,1699,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1785, 288, '2020-10-10 11:10:11', 71800, 562, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1081,1982,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1081,968,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1081,2108,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1081,761,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1081,1010,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1081,457,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1081, 139, '2020-09-11 18:32:41', 100950, 271, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2851,1372,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2851,1980,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2851,555,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2851, 720, '2020-09-10 08:22:33', 35080, 1405, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(383,2005,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(383,1020,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(383,572,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(383,1645,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(383, 49, '2020-10-19 04:57:16', 59400, 99, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(865,1024,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(865,227,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(865, 110, '2020-09-11 02:57:01', 40980, 213, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(536,223,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(536, 67, '2020-11-07 10:08:38', 116700, 134, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(591,679,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(591, 75, '2020-09-23 13:52:02', 41400, 146, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2747,1456,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2747,2343,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2747,1031,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2747, 677, '2020-11-01 05:36:16', 62920, 1322, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(276,889,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(276,603,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(276,856,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(276, 36, '2020-10-01 12:25:19', 49760, 74, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3355,1143,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3355,977,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3355,2050,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3355,442,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3355, 925, '2020-09-20 16:07:24', 163500, 1824, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(343,874,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(343, 43, '2020-10-17 13:01:21', 199200, 87, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1151,1503,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1151,1079,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1151, 149, '2020-10-26 21:39:36', 53760, 290, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(557,817,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(557,2379,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(557,1577,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(557, 69, '2020-10-10 06:18:12', 62140, 136, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3337,35,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3337,1137,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3337,854,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3337,1357,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3337,1052,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3337, 918, '2020-10-31 01:55:18', 52780, 1809, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2640,1989,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2640,2297,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2640,387,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2640, 630, '2020-09-20 11:35:52', 51940, 1219, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2212,1219,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2212,1308,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2212,1522,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2212, 458, '2020-10-04 15:29:59', 42840, 894, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2161,1961,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2161,1849,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2161,1816,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2161,1929,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2161,1073,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2161,1065,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2161, 441, '2020-09-09 02:43:24', 50800, 862, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1995,303,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1995,246,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1995,1824,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1995, 374, '2020-09-23 21:11:16', 55220, 732, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1060,1615,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1060, 136, '2020-09-11 21:42:06', 163200, 267, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2101,2188,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2101,1698,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2101, 419, '2020-09-09 03:43:18', 171960, 824, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2830,139,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2830, 712, '2020-10-24 16:02:42', 53400, 1391, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1435,1603,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1435, 183, '2020-09-13 08:48:05', 61174, 350, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1823,1015,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1823,325,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1823, 305, '2020-10-22 04:03:29', 73740, 593, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3154,2271,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3154,1841,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3154,1367,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3154,748,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3154, 840, '2020-10-22 21:19:24', 46080, 1650, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(110,341,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(110,1170,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(110,2086,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(110, 14, '2020-10-28 02:20:05', 44740, 24, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3435,1592,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3435,1988,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3435,1435,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3435,872,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3435,2302,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3435, 962, '2020-11-05 00:16:15', 75700, 1900, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3056,1203,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3056,1239,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3056,1472,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3056, 803, '2020-10-27 12:36:15', 55440, 1577, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1525,347,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1525,796,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1525, 195, '2020-10-17 17:41:10', 59580, 371, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(719,71,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(719, 89, '2020-10-13 12:37:12', 198000, 178, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2997,741,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2997,2003,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2997,2021,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2997,847,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2997, 779, '2020-10-27 19:58:54', 76500, 1525, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3222,62,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3222, 866, '2020-09-24 01:58:17', 164400, 1701, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3344,626,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3344,153,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3344,1106,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3344,1254,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3344, 921, '2020-10-06 00:28:30', 51880, 1816, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2363,225,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2363, 523, '2020-09-25 06:18:10', 74800, 1013, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(63,1728,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(63, 8, '2020-09-14 15:48:36', 178245, 13, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(216,1207,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(216,1472,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(216,1775,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(216,1295,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(216,192,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(216, 29, '2020-09-21 01:12:53', 92130, 62, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1986,1797,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1986,1383,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1986,687,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1986, 371, '2020-10-30 14:45:26', 46140, 726, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2138,264,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2138,1405,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2138, 434, '2020-09-17 08:40:03', 36560, 849, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2890,1354,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2890,1275,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2890,1194,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2890, 735, '2020-10-17 03:02:53', 36880, 1434, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1615,462,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1615,1337,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1615,1815,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1615, 223, '2020-10-11 15:59:21', 55440, 432, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1121,2071,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1121,1800,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1121, 145, '2020-10-20 14:51:17', 48200, 282, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1760,465,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1760, 277, '2020-10-21 15:58:28', 48900, 539, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1767,1302,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1767,318,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1767, 281, '2020-10-04 12:48:30', 59860, 549, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3522,806,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3522,1740,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3522,1076,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3522,1509,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3522, 998, '2020-10-02 07:31:49', 37320, 1975, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1138,2343,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1138,2343,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1138, 147, '2020-10-21 10:26:19', 62000, 286, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1819,990,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1819,1845,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1819, 303, '2020-10-04 23:31:26', 59490, 589, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1830,2030,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1830, 308, '2020-10-28 22:31:20', 73440, 602, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(269,1930,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(269,202,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(269,2013,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(269, 35, '2020-09-22 13:53:11', 45720, 73, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1940,526,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1940,556,1);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3296,1587,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3296,1238,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3296,463,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3296,1518,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3296,502,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3296, 896, '2020-10-30 21:00:20', 131620, 1765, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1726,877,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1726,1877,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1726,1480,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1726, 267, '2020-09-18 18:25:22', 36690, 517, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1661,203,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1661,2399,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1661, 243, '2020-10-24 20:09:38', 45620, 471, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2279,1483,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2279,1763,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2279, 486, '2020-09-19 15:47:43', 42780, 950, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1681,839,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1681,2392,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1681,16,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1681, 253, '2020-10-04 16:05:47', 66180, 491, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2424,2421,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2424,2286,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2424, 546, '2020-10-03 11:39:08', 55300, 1057, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3503,1975,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3503,237,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3503,2365,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3503,1748,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3503, 991, '2020-09-17 10:44:35', 94340, 1962, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2278,335,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2278,2219,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2278, 486, '2020-10-19 18:03:28', 82000, 950, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2629,770,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2629,1392,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2629,791,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2629, 626, '2020-09-14 20:44:27', 36880, 1210, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1018,1893,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1018,1483,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1018,1139,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1018,12,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1018, 131, '2020-10-13 13:11:50', 63920, 254, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(868,761,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(868,858,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(868, 111, '2020-09-10 18:24:42', 89980, 216, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1700,1579,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1700,549,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1700,921,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1700, 259, '2020-10-27 11:33:16', 340020, 501, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3307,5,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3307, 903, '2020-10-24 18:47:56', 37920, 1779, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2698,1175,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2698,1871,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2698,294,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2698, 656, '2020-10-20 23:33:10', 53740, 1275, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3071,105,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3071,1630,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3071,517,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3071, 809, '2020-09-26 10:35:08', 47280, 1586, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(115,2057,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(115,331,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(115,172,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(115,1807,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(115,2422,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(115, 15, '2020-10-07 17:33:33', 50840, 27, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2940,2245,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2940,1563,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2940,1205,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2940,232,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2940, 755, '2020-10-11 01:46:37', 388780, 1472, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2270,977,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2270,311,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2270,728,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2270, 482, '2020-09-25 02:03:44', 63740, 940, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1460,846,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1460,1417,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1460,1851,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1460, 186, '2020-10-14 17:09:40', 35500, 355, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2466,1265,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2466,728,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2466,23,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2466, 559, '2020-10-16 00:05:23', 54420, 1085, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1582,1160,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1582,1483,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1582,1133,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1582, 209, '2020-10-08 04:47:25', 57720, 401, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1982,1489,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1982, 369, '2020-09-12 06:52:31', 37800, 720, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3431,308,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3431, 960, '2020-10-03 19:12:49', 199600, 1897, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2318,1294,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2318,748,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2318, 501, '2020-09-28 07:10:04', 36480, 980, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(761,2133,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(761,917,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(761, 96, '2020-09-11 04:16:43', 55600, 189, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3144,2274,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3144,943,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3144,2273,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3144,1118,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3144, 837, '2020-10-08 06:03:35', 50780, 1642, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(403,1184,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(403,266,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(403, 50, '2020-10-08 07:34:57', 42620, 100, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(954,2408,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(954,1133,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(954,1814,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(954,2311,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(954, 122, '2020-11-05 18:43:13', 48500, 235, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2302,1559,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2302,353,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2302,1674,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2302, 495, '2020-10-15 14:40:22', 50040, 966, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2350,768,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2350,356,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2350, 517, '2020-10-31 09:39:24', 131960, 1005, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(466,1492,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(466,870,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(466,312,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(466,1236,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(466, 58, '2020-10-04 20:59:07', 45940, 118, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(610,2400,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(610,2408,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(610,2181,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(610,732,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(610,166,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(610, 77, '2020-09-10 22:50:27', 106500, 152, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(279,516,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(279,1844,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(279,2302,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(279, 36, '2020-09-20 06:27:04', 43520, 74, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(130,959,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(130,379,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(130, 18, '2020-10-18 00:31:25', 32360, 35, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(65,1582,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(65,618,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(65, 9, '2020-10-01 19:03:50', 75140, 16, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1256,896,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1256,2203,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1256,326,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1256, 161, '2020-10-17 15:10:15', 206664, 308, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3045,802,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3045,1610,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3045, 799, '2020-09-15 04:41:34', 51540, 1567, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2433,618,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2433, 548, '2020-10-25 13:54:25', 38400, 1063, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(505,1861,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(505,557,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(505,308,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(505, 62, '2020-09-29 19:21:39', 221880, 125, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(516,930,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(516,1100,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(516,2344,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(516, 64, '2020-09-26 22:01:16', 77690, 127, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3259,2402,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3259,943,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3259,1133,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3259,896,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3259, 883, '2020-09-15 05:19:22', 67360, 1737, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(121,1819,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(121,603,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(121,799,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(121, 16, '2020-10-28 14:15:02', 43020, 29, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(97,307,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(97, 12, '2020-09-18 16:16:52', 101800, 22, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2682,282,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2682, 651, '2020-09-19 12:02:52', 67520, 1262, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1312,128,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1312, 166, '2020-09-08 00:30:12', 99600, 319, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1248,1924,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1248,1307,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1248,1434,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1248, 160, '2020-10-04 21:33:48', 57900, 307, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(815,2107,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(815,1765,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(815, 104, '2020-09-14 05:39:56', 124560, 203, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(628,1048,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(628,1103,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(628,1698,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(628, 79, '2020-10-19 08:53:11', 163400, 157, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3454,752,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3454,2044,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3454,185,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3454, 970, '2020-10-03 11:36:23', 248640, 1918, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2768,5,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2768,785,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2768,990,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2768, 687, '2020-10-24 09:06:18', 58200, 1344, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(520,404,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(520,2139,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(520, 65, '2020-10-22 07:59:31', 49950, 129, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1639,378,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1639, 234, '2020-10-03 12:09:59', 73600, 456, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2388,1551,4);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3162,224,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3162,2135,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3162, 843, '2020-09-20 04:41:15', 54200, 1655, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(186,1637,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(186,746,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(186,1437,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(186, 24, '2020-09-21 17:56:28', 50180, 50, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1422,428,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1422,756,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1422,2120,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1422, 181, '2020-09-12 05:42:43', 101600, 347, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(689,2328,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(689,409,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(689,364,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(689,1977,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(689,670,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(689, 85, '2020-10-28 09:06:23', 84420, 170, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2683,786,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2683,2020,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2683,2027,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2683, 652, '2020-09-22 06:14:01', 58060, 1265, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3350,1316,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3350,1155,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3350,408,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3350,482,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3350, 923, '2020-10-29 09:58:48', 331080, 1819, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(158,176,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(158,2161,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(158, 21, '2020-09-28 07:17:05', 49580, 43, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1353,1806,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1353,1259,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1353,387,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1353,2077,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1353, 172, '2020-10-14 15:01:20', 47280, 331, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(342,684,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(342, 43, '2020-09-17 21:28:09', 198000, 88, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1374,105,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1374,1529,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1374,910,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1374, 174, '2020-10-19 13:36:39', 59280, 333, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3249,1542,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3249, 879, '2020-10-15 08:27:05', 56400, 1728, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2598,2401,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2598,192,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2598, 613, '2020-09-25 03:34:36', 181620, 1185, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(167,2236,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(167,2362,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(167,1600,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(167, 21, '2020-09-10 01:16:13', 39960, 42, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3177,1022,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3177,384,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3177,979,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3177, 850, '2020-10-04 18:14:10', 38460, 1670, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2398,2119,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2398,1962,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2398, 536, '2020-09-17 15:27:16', 81400, 1035, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1331,377,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1331, 170, '2020-09-20 05:58:56', 151200, 325, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1325,1485,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1325,1946,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1325,638,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1325,88,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1325, 169, '2020-09-18 16:11:23', 86540, 324, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1873,1870,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1873,220,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1873,722,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1873, 325, '2020-09-21 14:27:49', 47500, 634, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2627,668,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2627,201,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2627, 625, '2020-10-06 03:28:23', 328700, 1208, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1617,2292,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1617,1697,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1617, 225, '2020-09-19 19:42:55', 75560, 436, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2646,1279,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2646,952,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2646,682,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2646,1003,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2646, 634, '2020-10-14 17:49:21', 56712, 1227, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1784,1635,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1784, 287, '2020-10-11 17:11:41', 44700, 561, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(366,2355,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(366,907,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(366,2067,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(366, 46, '2020-11-05 02:39:52', 59880, 93, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2027,1327,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2027,1309,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2027,1216,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2027, 386, '2020-09-14 23:20:17', 65820, 755, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1260,1152,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1260,896,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1260, 161, '2020-09-26 03:20:25', 95560, 308, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2543,420,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2543,1793,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2543,207,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2543, 592, '2020-09-08 05:18:02', 64680, 1149, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1562,373,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1562,1179,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1562,2354,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1562, 202, '2020-10-13 12:14:44', 56020, 385, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(664,162,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(664,37,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(664,801,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(664, 82, '2020-09-21 08:03:50', 64580, 163, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2170,547,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2170,1435,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2170,997,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2170, 444, '2020-10-23 22:43:18', 33960, 867, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1163,215,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1163,1082,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1163,1667,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1163, 151, '2020-10-01 09:05:54', 76290, 292, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(989,1859,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(989,25,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(989,2357,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(989, 127, '2020-09-13 17:48:43', 61340, 244, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(149,110,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(149,675,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(149, 20, '2020-10-11 21:44:43', 98800, 40, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1093,1076,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1093, 140, '2020-10-30 12:21:23', 34000, 274, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(587,189,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(587,2187,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(587,1285,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(587,1110,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(587,710,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(587, 74, '2020-10-24 14:18:33', 57280, 145, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3326,737,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3326,2,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3326,43,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3326, 913, '2020-09-17 13:53:10', 46680, 1800, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3338,615,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3338,1096,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3338, 918, '2020-10-07 21:58:34', 52960, 1809, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(675,68,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(675, 83, '2020-10-23 09:31:02', 119600, 166, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(347,2267,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(347,729,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(347,1621,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(347, 44, '2020-09-09 13:43:52', 177880, 89, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1476,1571,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1476,580,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1476,1737,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1476, 189, '2020-10-11 00:46:20', 76920, 359, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2463,1588,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2463,1361,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2463, 558, '2020-10-29 01:02:07', 54552, 1084, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(62,1921,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(62,474,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(62,2283,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(62,623,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(62, 8, '2020-10-20 10:57:48', 41702, 13, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2716,1886,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2716,1751,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2716, 664, '2020-11-01 17:33:41', 71580, 1293, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2610,685,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2610, 618, '2020-10-17 01:18:38', 43600, 1196, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3239,507,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3239,30,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3239,1533,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3239, 876, '2020-10-22 13:21:25', 35800, 1719, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2775,30,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2775,1181,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2775,1899,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2775, 690, '2020-10-29 17:34:15', 81900, 1347, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2822,843,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2822,1299,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2822, 707, '2020-10-29 17:56:12', 67840, 1381, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(357,1633,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(357,581,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(357, 46, '2020-10-07 03:31:44', 43900, 94, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3107,1339,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3107,2130,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3107,1759,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3107, 822, '2020-10-20 10:36:14', 93520, 1611, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(419,227,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(419,2358,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(419, 52, '2020-09-21 23:27:10', 45400, 104, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(128,129,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(128, 17, '2020-10-29 09:19:33', 59700, 34, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(127,210,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(127, 17, '2020-10-21 19:08:16', 237000, 34, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3317,2401,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3317,1106,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3317,1682,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3317,1036,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3317, 908, '2020-10-14 18:36:31', 58180, 1788, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3452,2005,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3452,810,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3452,1481,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3452,747,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3452, 969, '2020-09-26 23:05:54', 90000, 1916, 3, '14:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2411,2322,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2411,83,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2411, 540, '2020-09-22 20:04:15', 91300, 1042, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(326,2290,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(326, 42, '2020-09-19 09:28:00', 35600, 86, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1755,266,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1755,883,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1755,921,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1755, 275, '2020-10-16 15:59:03', 340860, 536, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3248,216,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3248, 879, '2020-11-01 17:43:26', 47700, 1726, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(762,171,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(762,1023,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(762,882,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(762,1631,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(762, 96, '2020-10-13 19:56:49', 74860, 191, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1148,2386,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1148,775,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1148, 149, '2020-10-28 11:52:46', 89520, 288, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3453,2155,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3453,750,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3453, 970, '2020-10-04 05:06:23', 44620, 1918, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1244,1211,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1244,2060,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1244,1212,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1244,2052,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1244,277,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1244,2378,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1244, 159, '2020-09-16 11:36:27', 58550, 304, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1423,761,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1423,741,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1423,584,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1423,670,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1423, 181, '2020-10-22 11:50:32', 52300, 347, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(563,1710,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(563, 69, '2020-10-29 23:10:46', 83600, 136, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1778,31,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1778,2346,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1778,427,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1778, 285, '2020-11-02 21:34:36', 88200, 557, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3196,1677,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3196,1694,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3196,1744,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3196, 857, '2020-10-20 08:02:58', 40560, 1683, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2829,1514,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2829,513,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2829,616,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2829,942,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2829,339,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2829, 711, '2020-10-09 03:17:47', 49120, 1389, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(85,1874,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(85,2331,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(85,468,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(85, 10, '2020-09-21 16:59:32', 48340, 18, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1161,203,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1161, 150, '2020-11-03 19:53:07', 73500, 291, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(264,657,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(264,1534,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(264, 35, '2020-11-04 18:59:56', 43380, 73, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1470,688,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1470,1184,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1470,2276,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1470, 188, '2020-09-28 17:13:13', 118760, 357, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3476,2415,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3476,1849,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3476,910,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3476,2223,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3476, 979, '2020-10-08 21:01:39', 87750, 1934, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(593,173,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(593,1106,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(593,215,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(593, 75, '2020-10-21 19:06:24', 98040, 147, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2667,2206,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2667,1869,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2667,331,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2667, 643, '2020-10-26 15:58:08', 45100, 1247, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1731,365,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1731,2258,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1731,885,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1731, 268, '2020-11-01 05:28:37', 431920, 518, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2040,293,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2040, 392, '2020-10-13 18:20:26', 51200, 771, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3379,2186,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3379,967,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3379,356,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3379, 938, '2020-10-08 09:17:32', 75056, 1852, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(654,2028,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(654,2416,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(654,478,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(654, 81, '2020-11-03 21:15:26', 81920, 161, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1054,980,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1054,345,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1054,1032,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1054,2401,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1054,414,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1054, 135, '2020-10-12 07:13:31', 59220, 265, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2531,1564,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2531, 585, '2020-11-04 20:31:01', 74000, 1137, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2843,1903,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2843,1563,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2843,688,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2843,2298,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2843, 718, '2020-10-10 21:36:39', 72640, 1399, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3516,2225,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3516, 995, '2020-10-10 15:23:47', 321600, 1969, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1527,1827,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1527,2013,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1527,589,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1527,2101,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1527,2390,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1527, 196, '2020-10-05 08:16:40', 73080, 373, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1105,1772,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1105,1661,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1105,1573,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1105, 143, '2020-10-06 09:26:54', 39980, 280, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3299,1895,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3299,940,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3299,1873,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3299,2294,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3299,2275,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3299, 897, '2020-10-03 16:34:22', 44360, 1767, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(27,408,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(27,910,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(27, 4, '2020-09-25 04:56:17', 43740, 6, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(155,788,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(155,1909,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(155,1726,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(155,1411,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(155,16,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(155, 20, '2020-09-19 11:01:41', 64290, 40, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(638,1001,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(638,129,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(638,2296,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(638, 80, '2020-11-04 22:55:25', 70480, 160, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1509,1077,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1509,1380,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1509,1665,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1509,1803,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1509, 193, '2020-10-26 02:57:52', 73240, 367, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1849,1326,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1849,639,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1849,756,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1849,1901,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1849,38,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1849, 316, '2020-09-28 23:40:37', 44660, 617, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(899,722,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(899,1289,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(899,2216,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(899, 116, '2020-10-10 14:37:07', 37240, 225, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2602,2285,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2602,1195,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2602,1243,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2602,2186,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2602,976,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2602, 616, '2020-10-01 15:19:46', 48792, 1191, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2188,616,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2188,2222,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2188, 450, '2020-10-04 22:01:19', 45860, 882, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3001,2023,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3001,1968,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3001,143,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3001, 780, '2020-10-19 16:56:52', 180320, 1527, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(246,1331,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(246,558,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(246,2122,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(246, 32, '2020-10-03 09:49:51', 67660, 69, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3225,1426,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3225,326,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3225, 869, '2020-10-21 11:20:25', 54052, 1707, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(701,2082,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(701,754,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(701,696,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(701, 86, '2020-09-20 02:37:24', 52200, 172, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2496,340,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2496,1758,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2496, 572, '2020-10-23 21:29:44', 46880, 1115, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(133,1293,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(133,790,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(133,886,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(133, 18, '2020-10-09 23:29:52', 247520, 35, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1343,841,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1343,1417,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1343,664,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1343,158,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1343, 171, '2020-10-29 02:19:23', 101240, 326, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2402,1680,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2402,869,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2402, 537, '2020-09-24 13:50:09', 44560, 1038, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1252,1427,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1252,1685,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1252,670,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1252, 160, '2020-11-06 17:27:24', 88400, 307, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2241,1661,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2241,920,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2241,1049,4);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1516,431,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1516,1992,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1516,1408,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1516, 194, '2020-10-27 09:42:10', 84680, 368, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3136,347,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3136,1823,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3136, 834, '2020-09-28 08:10:17', 38710, 1639, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(364,1202,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(364,986,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(364,2274,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(364, 46, '2020-09-12 20:58:11', 56010, 94, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2154,2088,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2154,2356,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2154,34,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2154,2260,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2154, 439, '2020-10-30 18:34:27', 43950, 857, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2766,128,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2766, 686, '2020-10-25 11:16:30', 49800, 1342, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2168,266,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2168,1183,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2168,430,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2168, 443, '2020-09-18 22:05:56', 71020, 864, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(486,852,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(486,2247,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(486,2092,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(486, 60, '2020-10-19 08:31:20', 55070, 122, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1744,1939,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1744,845,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1744,1715,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1744,1031,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1744, 272, '2020-10-15 07:47:55', 56080, 528, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(28,2368,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(28,1168,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(28,1385,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(28,1550,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(28,2222,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(28,210,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(28, 4, '2020-10-31 21:48:56', 203880, 6, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(755,2040,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(755,1002,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(755,1160,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(755, 95, '2020-10-12 14:24:08', 79040, 188, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1358,2277,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1358,646,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1358, 173, '2020-09-08 15:40:36', 42520, 332, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1445,523,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1445,107,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1445,1281,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1445, 184, '2020-10-06 16:27:32', 47740, 352, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(846,2160,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(846,482,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(846, 108, '2020-10-13 14:59:06', 585940, 209, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3515,257,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3515, 995, '2020-10-26 13:30:33', 235200, 1969, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1007,957,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1007,2393,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1007,1201,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1007,1479,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1007, 129, '2020-10-13 12:38:32', 50860, 248, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(470,1324,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(470,107,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(470, 59, '2020-10-16 05:45:59', 38680, 119, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2494,2177,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2494,1444,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2494,1920,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2494,19,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2494, 572, '2020-10-20 03:32:07', 79360, 1115, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1319,2262,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1319,2217,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1319,681,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1319, 168, '2020-10-13 16:05:11', 39060, 322, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1159,1973,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1159,1023,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1159,1882,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1159,551,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1159,1690,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1159, 150, '2020-09-17 14:50:58', 119660, 291, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1770,1435,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1770,1822,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1770, 282, '2020-11-03 05:47:14', 39200, 552, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2472,2216,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2472,1035,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2472, 562, '2020-10-25 13:40:41', 55440, 1092, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1387,526,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1387,1571,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1387,476,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1387, 177, '2020-09-21 16:39:57', 56100, 340, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3528,2003,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3528,305,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3528, 1000, '2020-10-08 21:29:57', 75160, 1978, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3189,149,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3189, 854, '2020-09-28 20:26:00', 39920, 1678, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2568,2156,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2568,1914,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2568,1040,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2568,1591,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2568, 600, '2020-09-07 12:04:23', 79304, 1160, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(681,883,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(681,382,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(681, 84, '2020-10-13 12:18:34', 43540, 169, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2110,1682,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2110,1273,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2110,1661,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2110, 423, '2020-09-13 17:50:07', 48880, 829, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2566,189,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2566,1770,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2566,500,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2566, 600, '2020-11-06 04:18:37', 60780, 1160, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2293,1766,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2293,1922,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2293,1177,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2293,643,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2293,320,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2293, 491, '2020-09-07 12:29:48', 48900, 960, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3432,1646,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3432,1802,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3432,1225,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3432, 961, '2020-09-21 01:06:03', 52940, 1899, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1255,285,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1255, 160, '2020-09-15 10:01:27', 219200, 307, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2084,2127,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2084,1204,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2084,856,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2084, 412, '2020-09-27 19:17:51', 46260, 810, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2103,1845,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2103,474,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2103, 420, '2020-10-08 15:09:20', 78080, 825, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(229,1773,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(229,2309,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(229, 30, '2020-10-19 18:00:54', 39440, 64, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(736,84,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(736,2141,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(736, 92, '2020-10-04 23:23:24', 51140, 181, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2988,38,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2988,999,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2988, 776, '2020-09-26 14:42:55', 68060, 1517, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(378,1847,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(378,2420,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(378,2341,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(378,699,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(378, 48, '2020-09-10 08:43:04', 423820, 98, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2395,1156,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2395,473,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2395, 535, '2020-09-10 06:10:40', 306170, 1030, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(934,448,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(934, 120, '2020-10-29 19:28:57', 93800, 232, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2105,720,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2105,1756,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2105,1746,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2105, 421, '2020-10-07 23:15:43', 53127, 826, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(122,2156,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(122,2130,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(122,603,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(122,366,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(122, 16, '2020-10-29 09:09:06', 61204, 29, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1512,996,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1512,1728,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1512, 194, '2020-10-20 15:37:48', 188525, 369, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3462,178,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3462, 973, '2020-10-12 20:08:50', 155600, 1921, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1862,2183,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1862,113,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1862, 321, '2020-09-28 04:23:25', 92200, 628, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1108,2054,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1108,43,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1108,1787,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1108, 143, '2020-10-20 08:31:54', 41720, 280, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2341,875,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2341, 512, '2020-10-10 10:27:14', 47200, 996, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1996,32,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1996,113,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1996, 375, '2020-11-03 05:19:15', 305320, 734, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2691,72,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2691, 654, '2020-09-19 05:18:57', 89800, 1270, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1468,1474,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1468,547,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1468,2278,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1468,69,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1468, 188, '2020-10-26 23:11:08', 59812, 357, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2430,2382,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2430,968,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2430,653,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2430, 548, '2020-10-14 05:21:31', 49260, 1064, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3312,497,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3312, 906, '2020-09-29 07:57:14', 104700, 1786, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1552,190,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1552, 199, '2020-10-23 15:39:05', 44700, 381, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1930,463,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1930,1139,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1930,359,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1930,733,3);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2769,203,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2769, 687, '2020-09-21 02:08:58', 98000, 1344, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3316,2198,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3316,766,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3316,222,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3316, 907, '2020-10-15 05:54:36', 151688, 1787, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2968,1504,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2968,1060,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2968, 765, '2020-09-27 06:31:56', 44720, 1493, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3022,264,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3022, 789, '2020-10-27 04:22:53', 41700, 1547, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1409,1007,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1409,2316,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1409,1218,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1409,2321,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1409, 180, '2020-10-19 11:26:44', 54040, 346, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3262,167,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3262, 884, '2020-11-03 09:37:50', 39000, 1740, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2031,1416,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2031,398,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2031,288,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2031,403,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2031, 387, '2020-10-06 10:12:00', 124500, 758, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2707,2244,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2707, 660, '2020-10-19 20:26:28', 35520, 1281, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2064,567,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2064,2253,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2064,2415,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2064,2307,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2064, 404, '2020-10-05 08:35:50', 39340, 794, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1875,1503,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1875,54,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1875, 325, '2020-09-16 22:06:57', 223140, 634, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3217,1535,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3217,416,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3217,1991,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3217,1845,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3217, 865, '2020-09-15 14:40:09', 50800, 1699, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(959,2161,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(959,2147,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(959,2116,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(959,54,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(959, 123, '2020-09-13 17:59:34', 188020, 236, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3046,1214,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3046,13,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3046, 799, '2020-10-20 09:11:55', 99160, 1568, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2306,2344,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2306,1803,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2306, 496, '2020-10-08 16:16:17', 56480, 969, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2449,1777,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2449,1870,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2449,1771,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2449,552,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2449, 553, '2020-09-13 21:48:28', 65060, 1074, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2086,2198,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2086,2165,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2086,1161,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2086, 413, '2020-09-08 10:07:06', 103248, 812, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2385,1895,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2385,1950,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2385,245,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2385, 530, '2020-10-08 23:51:20', 91312, 1023, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(683,847,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(683, 84, '2020-10-24 02:20:26', 51600, 169, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2996,423,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2996,1257,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2996,982,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2996, 779, '2020-10-18 11:34:15', 90830, 1524, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(222,1307,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(222,1199,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(222,2228,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(222, 30, '2020-09-16 15:26:28', 48120, 64, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3017,2357,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3017, 787, '2020-10-09 16:37:28', 91200, 1541, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2744,1717,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2744,1,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2744, 676, '2020-10-18 03:47:09', 79200, 1320, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3025,325,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3025, 792, '2020-11-03 02:09:14', 101700, 1553, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2181,571,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2181,316,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2181, 447, '2020-09-29 10:38:07', 64720, 874, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2576,2255,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2576,1710,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2576, 604, '2020-10-08 19:56:24', 44420, 1167, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2763,46,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2763, 684, '2020-09-27 02:32:26', 59800, 1338, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3195,274,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3195, 857, '2020-10-15 13:07:35', 47200, 1683, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1577,954,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1577,2045,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1577, 207, '2020-09-16 02:07:19', 43920, 397, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2866,2044,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2866,295,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2866,1155,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2866,398,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2866, 727, '2020-09-12 12:55:11', 55840, 1421, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3055,1130,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3055, 803, '2020-10-27 19:06:24', 45600, 1577, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1563,2311,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1563,1182,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1563,2021,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1563, 203, '2020-09-10 01:53:07', 54540, 386, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(332,2071,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(332,677,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(332, 42, '2020-10-26 21:51:07', 411000, 86, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(524,1016,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(524,1484,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(524,458,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(524, 65, '2020-10-28 08:22:11', 109350, 129, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1141,150,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1141, 147, '2020-09-30 17:52:41', 98000, 284, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(447,771,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(447,182,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(447,2254,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(447, 56, '2020-11-02 05:17:29', 66420, 115, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2704,1548,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2704, 658, '2020-09-15 18:43:26', 51600, 1278, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3370,1658,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3370,1084,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3370,2362,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3370,426,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3370, 934, '2020-09-24 23:24:01', 53360, 1844, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1274,94,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1274, 163, '2020-09-30 01:08:49', 199200, 312, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(242,921,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(242, 31, '2020-10-23 00:19:57', 396000, 66, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2219,2158,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2219,1237,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2219,2047,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2219,2014,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2219,537,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2219, 460, '2020-10-29 20:04:49', 55700, 898, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2539,352,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2539,1154,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2539, 590, '2020-10-15 22:49:22', 92020, 1144, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3008,273,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3008,534,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3008, 783, '2020-10-05 03:12:37', 225920, 1533, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1972,1598,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1972,529,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1972, 365, '2020-10-10 21:15:21', 74500, 713, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1576,1074,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1576,2395,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1576,1035,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1576,1724,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1576, 207, '2020-10-21 18:29:28', 90560, 398, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2672,2194,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2672,1123,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2672,407,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2672, 645, '2020-10-28 19:12:58', 45020, 1252, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1404,921,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1404, 179, '2020-09-29 11:59:26', 297000, 345, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2608,80,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2608,1357,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2608,166,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2608, 618, '2020-09-27 03:33:27', 43380, 1196, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(603,1270,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(603,482,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(603, 76, '2020-11-02 03:21:56', 583980, 150, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(4,41,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(4,1960,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(4, 1, '2020-10-06 11:41:29', 80000, 2, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(545,1291,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(545,1760,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(545, 67, '2020-10-10 18:37:48', 59640, 134, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2283,2406,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2283,1305,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2283,1278,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2283,1348,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2283, 487, '2020-11-03 14:12:09', 37320, 952, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1838,725,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1838,1387,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1838,41,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1838, 312, '2020-09-20 09:40:07', 70700, 612, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1473,1963,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1473,992,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1473,256,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1473, 188, '2020-11-02 23:59:15', 72080, 357, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2901,1331,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2901,1643,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2901,1239,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2901,873,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2901, 739, '2020-10-29 02:40:30', 68100, 1441, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(406,1189,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(406,2421,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(406,1008,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(406,2199,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(406,1949,1);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2614,2151,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2614,670,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2614, 620, '2020-11-03 06:26:26', 58900, 1200, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3089,778,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3089,307,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3089, 815, '2020-10-28 13:07:15', 167020, 1595, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1631,1879,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1631,875,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1631,1833,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1631,362,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1631, 231, '2020-09-27 06:22:35', 49640, 450, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(412,190,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(412, 51, '2020-10-20 21:43:42', 44700, 103, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2573,1349,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2573,319,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2573,428,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2573,1072,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2573, 603, '2020-09-13 07:31:16', 38400, 1165, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2234,1192,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2234,2278,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2234, 467, '2020-10-19 12:33:46', 39176, 908, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3150,746,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3150,51,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3150, 839, '2020-10-07 19:13:21', 217840, 1648, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1012,1293,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1012,1412,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1012,235,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1012, 129, '2020-09-26 07:50:27', 96000, 247, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1705,814,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1705,415,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1705, 261, '2020-10-25 09:59:37', 178300, 504, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(184,1950,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(184,2176,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(184,2129,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(184,687,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(184, 24, '2020-09-28 11:28:53', 50492, 50, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1,2177,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1, 1, '2020-09-25 08:05:25', 31920, 1, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1973,1271,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1973,1475,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1973,13,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1973, 365, '2020-09-17 13:22:55', 117412, 713, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(729,772,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(729, 91, '2020-10-21 20:25:41', 55600, 180, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3145,1073,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3145,1175,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3145,648,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3145,1188,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3145,616,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3145,2139,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3145, 837, '2020-09-19 02:59:32', 58270, 1642, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1655,1366,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1655,529,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1655, 240, '2020-10-26 03:59:11', 96350, 466, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(501,930,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(501,2393,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(501, 62, '2020-10-16 01:25:18', 39720, 124, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1008,2207,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1008,1900,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1008, 129, '2020-09-28 01:52:55', 52256, 249, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1091,1107,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1091,1452,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1091,1070,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1091, 140, '2020-10-08 02:57:30', 64470, 274, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1793,2149,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1793,2217,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1793, 292, '2020-09-25 14:30:22', 53340, 570, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2149,2388,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2149,1942,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2149,641,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2149, 438, '2020-09-11 03:52:32', 80250, 854, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1954,190,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1954,1243,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1954, 356, '2020-10-09 05:54:41', 50280, 694, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2526,2381,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2526,688,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2526, 583, '2020-10-25 22:11:17', 40760, 1134, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2273,1979,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2273,703,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2273,133,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2273,2306,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2273, 484, '2020-10-01 11:18:42', 56380, 944, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1710,2279,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1710,758,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1710, 263, '2020-10-14 19:32:40', 50320, 508, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(150,1104,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(150,1326,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(150,1960,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(150, 20, '2020-09-13 00:48:07', 88400, 40, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(288,1984,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(288,2388,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(288,2130,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(288,1927,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(288,768,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(288,2303,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(288, 38, '2020-09-30 11:43:17', 108900, 76, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1739,2401,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1739,40,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1739,879,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1739,671,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1739, 270, '2020-10-16 11:07:57', 53460, 522, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1433,1255,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1433,1175,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1433,1490,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1433,2037,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1433,1545,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1433, 183, '2020-10-13 02:58:55', 65860, 350, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(697,1137,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(697,1294,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(697,1761,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(697, 85, '2020-10-15 06:53:02', 73460, 171, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2382,894,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2382, 530, '2020-09-29 04:39:56', 43600, 1024, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1284,1499,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1284,242,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1284, 163, '2020-09-24 17:54:47', 265320, 314, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1992,406,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1992, 373, '2020-10-05 04:00:59', 88255, 731, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1417,2075,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1417,1078,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1417, 181, '2020-10-01 20:11:07', 73960, 347, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2029,1450,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2029,1423,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2029, 387, '2020-10-11 01:22:36', 47960, 760, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3037,1726,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3037,1680,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3037, 796, '2020-10-03 01:39:13', 60200, 1561, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1262,705,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1262,959,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1262,1732,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1262,266,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1262, 162, '2020-09-12 15:09:16', 114580, 310, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1727,720,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1727,1769,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1727,145,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1727, 267, '2020-10-10 12:44:24', 58080, 516, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1004,715,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1004,2329,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1004,2401,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1004,910,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1004, 129, '2020-09-18 07:00:34', 71720, 247, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(560,833,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(560,247,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(560, 69, '2020-09-27 15:48:39', 79100, 136, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1100,2252,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1100,441,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1100, 142, '2020-09-28 21:36:23', 95940, 278, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2665,521,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2665, 642, '2020-10-06 23:52:15', 135200, 1245, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(294,496,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(294, 38, '2020-10-20 10:20:41', 35700, 76, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(999,2045,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(999, 128, '2020-09-24 06:56:16', 71920, 246, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2922,564,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2922,1710,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2922, 749, '2020-11-01 08:10:04', 47780, 1458, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3047,699,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3047, 800, '2020-09-23 20:09:34', 1520000, 1570, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1850,1439,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1850,933,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1850, 317, '2020-10-01 08:02:11', 43560, 619, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2237,1305,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2237,1489,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2237,332,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2237, 468, '2020-10-24 09:25:06', 49500, 910, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1195,949,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1195,1159,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1195,176,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1195,1018,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1195, 154, '2020-09-27 19:17:00', 32970, 296, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3521,304,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3521, 997, '2020-09-28 09:57:38', 63200, 1973, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(217,1425,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(217,331,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(217,511,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(217, 29, '2020-10-12 21:57:48', 43660, 61, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1432,2416,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1432,828,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1432, 183, '2020-11-05 15:54:27', 69120, 351, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1889,2217,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1889, 330, '2020-09-30 01:21:53', 55200, 642, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2764,2165,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2764,2272,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2764,598,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2764,44,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2764, 685, '2020-09-24 13:33:06', 50720, 1340, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3367,1117,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3367, 932, '2020-10-29 00:35:19', 92700, 1838, 5, '14:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(926,843,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(926,625,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(926, 119, '2020-10-15 18:37:55', 60480, 231, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(942,1379,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(942,1432,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(942,723,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(942,1162,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(942,1143,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(942, 121, '2020-11-04 14:28:50', 54840, 233, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2223,526,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2223,2343,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2223,1425,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2223, 462, '2020-10-29 21:12:28', 38720, 900, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3467,2201,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3467, 976, '2020-10-18 17:14:25', 39200, 1926, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2337,994,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2337,43,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2337,114,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2337, 510, '2020-11-04 12:54:24', 221000, 994, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(759,2315,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(759,2068,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(759, 96, '2020-09-24 17:00:00', 114720, 191, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2808,822,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2808,1547,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2808, 702, '2020-11-07 11:39:30', 53700, 1369, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1184,2120,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1184, 153, '2020-10-06 19:17:13', 61350, 295, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(94,47,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(94,331,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(94,1436,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(94,2041,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(94,673,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(94,1980,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(94,651,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(94, 11, '2020-10-20 10:43:42', 82170, 19, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1945,1844,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1945,1111,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1945,919,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1945,2337,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1945, 353, '2020-10-13 20:25:59', 101192, 688, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(388,120,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(388,996,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(388,152,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(388, 49, '2020-09-12 22:27:12', 267230, 99, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(123,1802,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(123,704,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(123,1278,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(123,108,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(123,1441,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(123, 16, '2020-09-15 03:10:42', 48740, 30, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(137,2294,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(137,1208,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(137,74,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(137,1728,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(137, 18, '2020-10-29 13:43:36', 258840, 35, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1883,2423,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1883,1421,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1883,1318,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1883,790,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1883,739,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1883,1320,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1883,2329,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1883, 328, '2020-10-21 21:10:48', 44920, 640, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2242,277,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2242, 470, '2020-10-25 02:09:52', 59600, 916, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2582,1482,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2582,592,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2582,1493,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2582, 606, '2020-09-09 05:54:02', 36640, 1170, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2777,852,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2777,900,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2777, 690, '2020-11-02 17:09:03', 117060, 1347, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1036,2030,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1036,1220,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1036,316,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1036, 133, '2020-09-24 15:11:47', 96420, 259, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2125,1918,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2125,1490,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2125,1310,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2125,1236,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2125, 430, '2020-10-03 13:35:10', 43140, 842, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2596,2184,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2596,405,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2596, 613, '2020-10-27 23:02:04', 104840, 1187, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(839,1186,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(839,2406,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(839,934,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(839,206,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(839, 106, '2020-10-18 05:44:37', 181440, 206, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2045,2344,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2045, 393, '2020-10-25 13:12:02', 35520, 773, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2803,1632,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2803,2253,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2803,1179,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2803,366,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2803, 700, '2020-09-29 01:01:46', 63960, 1366, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(918,558,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(918,326,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(918, 118, '2020-10-15 06:47:28', 197800, 229, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(766,1615,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(766, 97, '2020-10-26 02:34:12', 40800, 193, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2419,556,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2419,1476,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2419,679,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2419, 544, '2020-10-24 14:51:47', 83920, 1052, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1144,595,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1144,1105,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1144,61,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1144,1329,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1144,522,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1144, 148, '2020-10-11 02:08:04', 73160, 287, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2534,1388,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2534,2266,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2534,326,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2534, 587, '2020-10-16 22:24:55', 70900, 1141, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2955,1584,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2955, 761, '2020-11-06 14:35:17', 51200, 1484, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1584,337,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1584,533,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1584,861,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1584,274,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1584, 210, '2020-10-24 09:46:11', 79340, 403, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2267,2373,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2267,1235,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2267,1606,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2267,1444,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2267,1397,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2267, 481, '2020-09-24 20:27:09', 71670, 937, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1086,2417,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1086,1989,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1086,2326,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1086,1618,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1086, 139, '2020-09-18 15:31:18', 40380, 271, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(78,449,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(78,155,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(78, 10, '2020-10-18 04:45:29', 54720, 18, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1186,766,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1186,1556,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1186,563,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1186,1530,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1186,1833,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1186,70,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1186, 153, '2020-10-10 09:37:44', 294260, 295, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1865,623,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1865,1596,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1865, 322, '2020-09-21 12:07:02', 71364, 629, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2518,2041,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2518,349,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2518, 581, '2020-11-03 03:31:39', 57560, 1131, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1123,31,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1123,1161,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1123, 145, '2020-10-08 16:46:23', 83680, 282, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2586,1533,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2586,1332,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2586,1483,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2586, 608, '2020-09-17 22:50:46', 47920, 1174, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(129,480,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(129, 18, '2020-10-11 09:16:17', 58900, 37, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1676,667,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1676, 250, '2020-10-28 18:30:25', 417000, 485, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2676,2399,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2676,1711,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2676,298,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2676, 648, '2020-09-21 17:33:31', 99060, 1257, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1164,1677,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1164,1869,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1164,335,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1164,665,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1164, 151, '2020-10-06 10:13:31', 46480, 293, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3291,2104,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3291,1473,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3291,527,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3291,437,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3291,2409,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3291, 894, '2020-10-23 21:21:04', 65690, 1761, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3489,1521,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3489,816,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3489,1839,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3489, 987, '2020-10-29 20:42:34', 45040, 1952, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(879,2015,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(879,1529,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(879,735,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(879,908,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(879, 113, '2020-09-22 06:02:19', 69840, 219, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(182,1000,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(182,11,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(182,26,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(182, 23, '2020-10-20 20:46:46', 42500, 47, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(457,1902,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(457,2041,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(457,162,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(457, 57, '2020-10-13 21:24:09', 56540, 116, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1398,1205,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1398,972,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1398,378,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1398, 178, '2020-10-25 08:02:57', 53100, 343, 2, '14:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3423,621,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3423,1693,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3423,1347,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3423,838,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3423, 954, '2020-10-30 01:43:26', 60720, 1883, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(349,1802,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(349,645,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(349,978,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(349,2352,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(349, 44, '2020-10-08 21:40:27', 36560, 89, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2951,1513,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2951,548,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2951, 759, '2020-10-17 07:44:22', 56340, 1478, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1198,1276,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1198,857,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1198,1291,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1198,2286,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1198, 154, '2020-10-05 18:44:10', 77480, 296, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2025,754,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2025,1786,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2025,38,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2025,1165,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2025,2267,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2025, 385, '2020-09-08 13:12:44', 56890, 753, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(408,2185,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(408,2017,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(408,2093,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(408, 51, '2020-10-18 13:35:06', 42340, 103, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(334,1763,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(334,194,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(334,1859,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(334, 43, '2020-10-31 17:45:58', 36140, 87, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2537,360,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2537,1051,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2537,541,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2537,1861,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2537,1408,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2537, 589, '2020-10-11 13:06:46', 62900, 1143, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2953,1686,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2953, 760, '2020-10-18 13:07:08', 125400, 1481, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3427,203,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3427, 956, '2020-10-23 23:35:38', 98000, 1888, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(725,853,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(725,2406,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(725,1134,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(725, 90, '2020-10-13 10:15:15', 138580, 179, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1129,1136,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1129, 146, '2020-11-01 13:36:24', 80560, 283, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2583,1368,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2583,1768,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2583,1592,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2583, 606, '2020-09-25 02:53:27', 48600, 1170, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2436,493,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2436,369,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2436, 549, '2020-10-01 18:09:09', 57400, 1065, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(49,1490,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(49,1155,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(49,1105,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(49,741,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(49,1468,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(49, 6, '2020-10-06 04:13:10', 55160, 10, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2801,1224,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2801,86,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2801,300,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2801,2392,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2801,612,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2801, 700, '2020-09-25 20:34:15', 53940, 1366, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2697,1368,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2697,571,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2697,563,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2697,2323,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2697, 656, '2020-11-01 02:44:31', 75800, 1275, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(570,352,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(570,2221,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(570, 71, '2020-10-14 22:20:44', 81520, 139, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(173,69,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(173,1182,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(173,768,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(173,1239,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(173, 22, '2020-09-18 03:23:44', 37880, 44, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3488,1390,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3488,852,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3488,1138,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3488,963,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3488,964,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3488, 986, '2020-10-08 23:04:37', 52480, 1950, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1415,1293,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1415,1892,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1415,1158,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1415,15,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1415,360,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1415,1316,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1415, 180, '2020-10-31 06:47:25', 48320, 346, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2616,1777,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2616,1450,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2616,1484,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2616, 621, '2020-09-23 05:41:13', 50730, 1201, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(741,649,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(741,1289,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(741, 93, '2020-10-08 12:54:00', 47540, 182, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2794,1226,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2794, 697, '2020-10-24 16:18:36', 92700, 1362, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2427,921,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2427, 547, '2020-09-24 06:02:15', 396000, 1062, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(727,2202,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(727,2204,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(727,657,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(727,1589,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(727, 91, '2020-10-30 01:01:28', 72660, 180, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2383,2211,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2383,125,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2383, 530, '2020-10-15 19:00:16', 68420, 1024, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(433,1285,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(433,6,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(433,1147,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(433,2315,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(433,1313,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(433, 54, '2020-10-22 16:25:57', 45920, 110, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3073,521,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3073, 809, '2020-09-26 13:12:59', 67600, 1586, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1242,1370,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1242,911,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1242,572,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1242,320,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1242, 159, '2020-10-17 03:20:46', 39140, 305, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1543,1894,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1543, 197, '2020-10-31 04:09:09', 43600, 374, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2041,1430,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2041,1647,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2041, 392, '2020-11-02 11:03:29', 217680, 771, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2966,566,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2966,1387,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2966,821,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2966,910,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2966, 764, '2020-10-13 00:10:58', 55520, 1491, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2075,840,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2075,1651,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2075, 409, '2020-09-17 21:06:25', 54960, 805, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1794,1676,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1794,1077,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1794,427,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1794, 292, '2020-09-12 19:41:57', 79700, 570, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3004,1015,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3004,372,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3004,43,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3004, 782, '2020-11-05 09:16:12', 85560, 1531, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1897,1603,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1897,2260,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1897,969,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1897, 333, '2020-10-24 07:45:57', 58167, 647, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(875,2054,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(875,102,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(875,1718,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(875,755,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(875, 112, '2020-09-27 01:37:59', 38420, 217, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1285,1912,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1285,698,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1285,2318,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1285, 164, '2020-09-23 14:22:52', 94400, 316, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1340,1254,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1340,791,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1340,702,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1340, 171, '2020-10-26 12:57:42', 73800, 327, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1293,1613,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1293, 164, '2020-09-23 17:32:45', 39920, 315, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(219,1850,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(219,2075,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(219, 29, '2020-09-19 01:39:07', 64260, 61, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1704,171,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1704,1119,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1704, 260, '2020-09-17 06:51:30', 121140, 503, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3359,1408,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3359, 927, '2020-10-31 02:15:29', 42900, 1827, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1843,1272,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1843,436,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1843, 314, '2020-10-29 16:30:08', 78620, 615, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2162,474,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2162, 441, '2020-09-18 21:18:21', 47400, 862, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2552,691,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2552,683,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2552, 594, '2020-10-15 02:13:10', 241880, 1152, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2785,2304,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2785,1543,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2785,803,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2785,1411,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2785, 694, '2020-10-31 13:34:28', 53060, 1355, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(135,1691,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(135,2224,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(135,2032,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(135, 18, '2020-10-27 13:15:46', 52940, 36, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3523,238,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3523, 998, '2020-10-08 03:19:11', 99600, 1975, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2818,1864,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2818,1436,4);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3106,313,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3106,1816,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3106, 822, '2020-09-25 13:36:19', 41200, 1613, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(416,1456,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(416,697,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(416,1597,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(416, 52, '2020-10-03 04:46:40', 70580, 104, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2736,109,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2736,2083,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2736,2404,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2736,250,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2736, 672, '2020-11-01 23:19:36', 43690, 1310, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(824,818,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(824,1692,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(824,521,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(824, 105, '2020-10-27 02:08:50', 165700, 204, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1058,28,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1058,2106,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1058, 135, '2020-09-26 20:53:35', 78100, 265, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1570,1292,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1570,2363,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1570,861,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1570,1566,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1570, 205, '2020-09-29 03:31:45', 65660, 392, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2773,2232,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2773,409,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2773,1374,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2773, 689, '2020-10-01 11:26:56', 55620, 1346, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3403,867,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3403, 946, '2020-10-02 14:01:47', 161700, 1867, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3261,1150,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3261, 884, '2020-10-11 06:03:00', 131700, 1739, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1401,923,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1401,1186,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1401,1077,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1401,1130,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1401, 178, '2020-10-10 19:44:10', 64140, 343, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1446,1250,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1446, 184, '2020-09-17 21:17:10', 34320, 352, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3446,1677,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3446,1786,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3446,2088,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3446,467,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3446, 968, '2020-09-17 01:38:58', 49690, 1915, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1272,1196,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1272,2387,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1272,436,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1272, 162, '2020-09-20 15:32:07', 65070, 311, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1520,1987,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1520,694,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1520,1213,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1520,2108,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1520, 195, '2020-09-15 14:20:42', 44720, 372, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2842,2394,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2842,981,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2842,1754,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2842,2249,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2842, 718, '2020-09-29 09:08:56', 82730, 1400, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1808,2077,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1808,576,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1808, 298, '2020-10-21 21:01:09', 43200, 584, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3074,2066,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3074,793,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3074,87,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3074, 810, '2020-10-09 22:13:31', 58174, 1588, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2082,1243,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2082,2386,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2082,947,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2082,2119,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2082, 411, '2020-09-18 15:35:48', 43120, 807, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1754,461,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1754,428,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1754,477,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1754,568,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1754, 274, '2020-10-09 05:25:31', 49740, 533, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2153,1728,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2153, 439, '2020-09-21 06:39:52', 118830, 856, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1559,741,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1559,2020,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1559,416,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1559, 201, '2020-09-23 13:07:42', 58300, 383, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3193,2144,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3193,110,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3193,2420,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3193, 856, '2020-09-11 15:19:45', 61780, 1680, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(145,18,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(145,903,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(145,1318,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(145,668,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(145, 19, '2020-10-25 03:50:46', 47170, 39, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(968,1333,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(968,1651,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(968,2112,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(968, 124, '2020-10-03 15:51:04', 52630, 238, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2488,607,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2488,1111,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2488,367,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2488, 569, '2020-10-26 21:35:17', 44584, 1108, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2384,2053,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2384,684,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2384, 530, '2020-09-20 09:56:57', 304480, 1024, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(181,1481,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(181,63,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(181,1461,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(181,445,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(181, 23, '2020-10-13 15:42:20', 110405, 46, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2310,593,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2310,827,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2310,1223,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2310,1428,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2310,1486,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2310, 498, '2020-10-20 07:52:46', 55920, 973, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2887,1598,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2887, 734, '2020-10-19 01:38:29', 43600, 1433, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2815,341,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2815,761,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2815,1789,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2815,238,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2815, 705, '2020-10-26 10:45:28', 49340, 1378, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(791,1889,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(791,2204,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(791,642,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(791, 100, '2020-11-01 10:16:52', 50800, 199, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(848,2002,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(848,894,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(848,978,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(848, 108, '2020-11-02 05:59:05', 74940, 209, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(187,764,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(187,1514,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(187,1290,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(187, 24, '2020-10-19 00:31:36', 51740, 50, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(88,1125,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(88,2191,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(88,772,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(88, 11, '2020-10-19 05:53:37', 40200, 21, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2570,2407,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2570,654,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2570,1110,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2570,2044,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2570,200,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2570, 602, '2020-10-02 11:55:24', 107380, 1164, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3420,1544,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3420, 953, '2020-10-06 04:10:44', 53700, 1880, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1134,1831,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1134,1398,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1134,1600,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1134, 147, '2020-10-30 07:57:30', 49660, 285, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2793,1424,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2793,246,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2793,2090,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2793,1893,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2793,1855,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2793,1062,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2793, 697, '2020-10-03 22:32:03', 55960, 1362, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1090,895,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1090,497,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1090, 140, '2020-11-03 08:38:40', 128500, 274, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1442,2059,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1442,2288,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1442,2322,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1442, 184, '2020-10-15 04:17:04', 73580, 352, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2889,508,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2889, 735, '2020-09-22 10:25:34', 149700, 1435, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1860,635,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1860,835,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1860,441,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1860, 320, '2020-09-12 00:33:54', 134660, 624, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2429,1087,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2429,2093,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2429, 547, '2020-09-10 13:20:28', 59560, 1060, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1177,654,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1177,1260,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1177, 152, '2020-09-24 00:01:49', 48840, 294, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2135,2018,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2135,654,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2135,1778,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2135,2272,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2135, 433, '2020-10-19 09:13:06', 53920, 847, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1480,375,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1480,4,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1480, 190, '2020-09-07 15:26:05', 67900, 360, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1625,1881,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1625,1596,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1625, 229, '2020-09-28 00:28:45', 56190, 446, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2647,470,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2647, 635, '2020-09-20 05:31:56', 188700, 1230, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1674,1533,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1674,1388,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1674,26,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1674,1228,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1674, 249, '2020-10-26 12:30:23', 114200, 481, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(624,765,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(624,462,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(624,2047,1);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3103,1035,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3103, 820, '2020-10-02 15:43:59', 69500, 1607, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1798,1226,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1798,1183,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1798, 294, '2020-09-20 18:44:04', 39840, 576, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2191,77,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2191,1751,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2191, 451, '2020-09-15 22:12:38', 41760, 883, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(696,1445,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(696,1820,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(696,1391,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(696, 85, '2020-11-07 03:57:32', 50720, 171, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2269,677,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2269, 482, '2020-09-15 06:13:03', 98000, 939, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1216,675,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1216, 157, '2020-09-20 21:50:04', 300000, 302, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(90,2073,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(90,1016,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(90,637,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(90,1518,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(90,1009,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(90, 11, '2020-09-16 18:12:40', 50380, 19, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2563,1727,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2563, 597, '2020-09-08 04:32:40', 279600, 1157, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2322,57,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2322,632,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2322,1954,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2322, 502, '2020-09-15 12:57:30', 61840, 983, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2787,2263,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2787,2204,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2787,2351,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2787, 694, '2020-10-27 20:19:58', 63080, 1355, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(410,1253,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(410,643,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(410,1933,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(410,1946,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(410,108,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(410, 51, '2020-10-15 10:35:02', 63410, 103, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2624,633,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2624,2089,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2624,1453,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2624, 625, '2020-10-21 18:02:54', 60520, 1208, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1816,2111,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1816,2266,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1816, 301, '2020-10-31 04:18:59', 47600, 587, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1240,962,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1240,2123,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1240,1022,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1240, 159, '2020-11-05 20:04:19', 39880, 305, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3290,13,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3290,243,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3290, 894, '2020-10-20 11:34:17', 61400, 1761, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2206,2184,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2206,25,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2206, 456, '2020-10-03 01:34:41', 35360, 892, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(254,946,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(254,2165,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(254,714,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(254, 33, '2020-09-24 14:21:24', 63380, 70, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1929,114,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1929, 347, '2020-09-07 16:36:41', 99600, 679, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3409,349,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3409,1182,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3409,1547,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3409, 949, '2020-09-14 07:01:25', 40820, 1872, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1758,861,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1758,932,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1758, 276, '2020-10-04 20:01:09', 49200, 537, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(541,274,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(541,424,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(541, 67, '2020-10-17 19:42:20', 65340, 134, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2037,1244,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2037,1881,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2037,1704,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2037,2295,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2037,1047,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2037,840,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2037, 390, '2020-09-24 02:03:46', 50660, 766, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(193,1650,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(193,1080,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(193,956,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(193,1330,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(193, 25, '2020-09-08 03:53:53', 51480, 52, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2947,1432,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2947,2156,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2947,2275,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2947,753,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2947, 758, '2020-09-10 16:08:20', 47476, 1476, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(218,1202,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(218,2141,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(218,381,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(218,209,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(218, 29, '2020-10-10 04:17:09', 213360, 62, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1025,380,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1025, 132, '2020-10-27 19:35:06', 146700, 258, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(796,1050,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(796,1796,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(796,718,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(796, 101, '2020-10-09 07:51:44', 74680, 200, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(922,309,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(922,274,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(922, 118, '2020-10-12 15:04:34', 79960, 229, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2498,391,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2498, 573, '2020-09-17 08:46:25', 164400, 1116, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1742,1486,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1742,105,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1742, 271, '2020-09-11 19:09:47', 42180, 525, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2501,1145,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2501,9,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2501, 575, '2020-09-28 00:36:52', 35640, 1120, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2482,377,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2482, 567, '2020-10-15 05:13:13', 113400, 1104, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(472,1419,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(472,1809,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(472,887,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(472, 59, '2020-09-08 15:04:01', 68840, 119, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1905,1335,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1905,1290,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1905,1287,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1905, 337, '2020-10-29 12:03:57', 38880, 655, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1043,906,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1043,1445,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1043,956,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1043,1893,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1043,2315,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1043,840,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1043, 134, '2020-10-20 17:09:34', 52520, 262, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1761,1492,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1761,149,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1761, 277, '2020-10-09 05:04:57', 54860, 539, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(106,792,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(106,921,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(106, 14, '2020-11-07 09:35:31', 198620, 24, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2087,1189,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2087,33,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2087, 413, '2020-09-29 07:19:19', 45600, 811, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(25,2339,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(25, 4, '2020-10-20 07:50:46', 45900, 6, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3408,2375,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3408,1973,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3408,1349,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3408,142,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3408, 948, '2020-10-21 10:13:34', 173330, 1870, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(778,1950,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(778,978,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(778,2328,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(778,1958,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(778,2251,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(778,1134,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(778, 98, '2020-09-30 11:19:07', 57588, 195, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2053,637,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2053,583,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2053,2046,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2053,2013,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2053,2208,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2053, 397, '2020-09-08 01:26:13', 46520, 781, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2612,127,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2612, 620, '2020-10-11 00:37:17', 59600, 1199, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3480,1910,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3480,2400,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3480,880,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3480, 983, '2020-09-28 08:42:22', 68460, 1942, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(670,622,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(670,381,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(670,1002,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(670, 83, '2020-09-29 19:42:38', 52880, 166, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(938,1033,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(938,1237,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(938,1663,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(938, 121, '2020-09-22 19:30:09', 178580, 233, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1211,1220,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1211,1125,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1211,2026,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1211,2089,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1211, 156, '2020-10-17 21:02:08', 46460, 300, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3458,1010,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3458,1286,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3458,619,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3458,1449,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3458, 972, '2020-10-15 14:01:45', 44130, 1920, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1346,2424,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1346,955,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1346,360,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1346, 171, '2020-09-16 19:26:40', 45100, 328, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(190,1812,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(190,2376,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(190,1997,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(190,920,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(190, 25, '2020-10-15 21:29:19', 54000, 52, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3526,2323,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3526,321,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3526,2295,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3526, 1000, '2020-10-08 03:42:10', 39600, 1977, 4, '11:00');

INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1558, 201, '2020-10-07 10:40:47', 41460, 383, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1270,1004,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1270,984,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1270,2348,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1270, 162, '2020-09-13 14:37:48', 64520, 311, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2781,1258,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2781,367,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2781, 692, '2020-09-24 18:11:25', 37900, 1351, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(71,1878,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(71,1014,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(71,592,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(71,2027,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(71, 9, '2020-10-21 09:18:12', 54220, 17, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(494,22,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(494,690,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(494,849,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(494, 61, '2020-10-26 01:19:32', 53000, 123, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2621,40,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2621,1346,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2621, 623, '2020-10-29 00:04:45', 57840, 1206, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(924,332,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(924,1918,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(924,1306,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(924, 119, '2020-09-17 04:22:29', 56160, 230, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1601,2259,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1601,1833,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1601,1875,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1601,1927,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1601,1978,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1601,639,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1601,2077,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1601,509,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1601, 218, '2020-10-05 02:01:27', 85080, 417, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3362,337,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3362,547,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3362,949,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3362, 929, '2020-11-03 00:09:49', 48080, 1832, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(774,1536,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(774, 97, '2020-11-07 00:59:40', 103200, 193, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2228,82,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2228,1957,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2228,207,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2228, 464, '2020-09-21 20:52:57', 109520, 904, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2848,1259,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2848,632,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2848, 719, '2020-10-20 02:07:54', 31960, 1403, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3172,1468,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3172,505,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3172, 847, '2020-10-27 22:23:34', 53960, 1666, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3448,682,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3448,1972,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3448,1397,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3448,576,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3448,1421,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3448, 968, '2020-09-19 17:53:07', 47820, 1913, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(833,1198,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(833,327,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(833, 106, '2020-10-07 10:50:18', 35400, 206, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(468,1480,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(468,247,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(468, 58, '2020-10-28 04:06:47', 109630, 118, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1814,536,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1814, 300, '2020-09-23 19:52:46', 216000, 586, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(785,1727,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(785, 100, '2020-09-29 10:28:51', 139800, 199, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1795,1650,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1795,40,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1795,1747,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1795, 292, '2020-10-13 01:24:55', 72780, 572, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2547,1911,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2547,1110,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2547,303,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2547, 593, '2020-10-28 13:56:21', 37140, 1150, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3096,2023,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3096,699,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3096, 818, '2020-10-06 03:59:29', 762970, 1602, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2169,2406,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2169,40,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2169,1566,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2169,1303,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2169,56,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2169, 443, '2020-09-19 08:31:15', 59180, 865, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(953,808,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(953,2324,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(953,19,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(953, 122, '2020-09-14 14:23:47', 50600, 235, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1500,1974,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1500,876,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1500,364,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1500,1664,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1500, 192, '2020-10-25 23:54:15', 72505, 366, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2356,1929,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2356,1575,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2356,2001,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2356,2285,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2356, 520, '2020-09-14 02:50:25', 39080, 1009, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(714,1087,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(714,113,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(714, 88, '2020-10-24 01:41:02', 379120, 176, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1243,1839,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1243,1707,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1243,1729,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1243, 159, '2020-10-01 13:02:31', 42540, 304, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1074,2073,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1074,156,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1074, 138, '2020-10-17 17:07:54', 157280, 270, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1845,2273,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1845,1373,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1845,1880,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1845, 314, '2020-09-09 11:24:43', 83380, 615, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1653,845,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1653, 240, '2020-09-08 15:00:06', 41700, 466, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1715,2251,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1715, 264, '2020-09-09 17:39:10', 31600, 510, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1699,1659,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1699, 258, '2020-10-23 11:27:07', 63200, 499, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2387,2272,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2387,524,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2387,1089,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2387, 532, '2020-11-06 20:11:32', 68160, 1026, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(236,2142,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(236,845,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(236,237,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(236,357,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(236, 31, '2020-09-07 22:58:17', 51680, 66, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2281,1955,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2281,2068,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2281, 487, '2020-09-13 03:36:34', 54900, 952, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(837,39,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(837,2099,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(837,1651,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(837, 106, '2020-10-26 20:11:54', 82560, 206, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2681,1955,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2681,981,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2681,1315,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2681,1893,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2681,1846,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2681,1785,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2681,2237,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2681,179,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2681, 651, '2020-10-24 02:36:18', 50570, 1263, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(70,2343,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(70,1744,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(70, 9, '2020-09-08 19:11:55', 63900, 16, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2702,2053,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2702,1592,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2702,1453,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2702, 658, '2020-09-12 03:41:28', 49220, 1278, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2213,696,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2213, 459, '2020-10-10 22:35:57', 47700, 895, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3116,489,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3116, 825, '2020-10-06 06:31:27', 105260, 1620, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(453,2080,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(453,912,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(453,2101,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(453, 57, '2020-10-07 02:03:48', 50920, 116, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2522,686,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2522,513,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2522,1844,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2522,380,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2522, 582, '2020-10-23 09:19:41', 162820, 1132, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(286,1782,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(286,271,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(286, 37, '2020-10-25 05:05:25', 66720, 75, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1126,1178,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1126, 146, '2020-10-06 16:05:20', 46350, 283, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(262,1538,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(262,2352,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(262, 34, '2020-10-07 02:43:49', 37700, 71, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3252,1502,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3252,1154,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3252, 881, '2020-09-20 09:18:15', 84140, 1732, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1096,1981,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1096,2355,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1096, 141, '2020-10-07 12:02:32', 79600, 275, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2827,684,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2827, 710, '2020-11-07 06:02:59', 99000, 1387, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2844,1153,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2844,2139,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2844, 718, '2020-11-01 04:21:35', 51000, 1400, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1789,989,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1789,241,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1789, 289, '2020-09-16 02:22:40', 85600, 563, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1805,1564,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1805, 297, '2020-10-16 21:31:19', 74000, 582, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2334,1506,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2334,515,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2334,1470,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2334, 508, '2020-09-11 18:07:07', 47400, 991, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2900,461,4);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1402,634,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1402,2320,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1402, 179, '2020-09-30 22:41:07', 63000, 344, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3078,1365,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3078,1246,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3078,532,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3078, 812, '2020-10-14 22:07:41', 60660, 1590, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2074,600,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2074,2415,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2074,59,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2074, 408, '2020-09-25 03:08:37', 158720, 802, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1499,1407,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1499,1194,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1499,111,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1499, 192, '2020-10-08 11:47:23', 183180, 366, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2958,533,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2958,1724,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2958, 762, '2020-09-17 00:28:52', 68300, 1485, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1095,1566,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1095,1406,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1095,935,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1095, 141, '2020-09-24 20:15:59', 43180, 276, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2879,406,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2879, 732, '2020-10-26 04:22:17', 264765, 1429, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(147,2022,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(147,1989,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(147,2002,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(147,2196,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(147, 20, '2020-10-21 09:40:32', 46632, 40, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2594,976,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2594,537,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2594, 611, '2020-10-02 06:36:08', 71940, 1180, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2264,61,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2264,1291,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2264,2327,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2264,1076,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2264, 479, '2020-10-19 09:08:23', 56420, 934, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2961,298,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2961, 763, '2020-10-18 10:00:17', 45800, 1489, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(668,1944,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(668,1367,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(668,1807,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(668,129,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(668, 83, '2020-11-01 08:11:36', 56900, 166, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(946,917,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(946,1436,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(946, 121, '2020-11-02 12:24:31', 52360, 234, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(717,668,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(717,990,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(717,775,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(717, 89, '2020-10-10 12:38:54', 107700, 178, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2931,214,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2931, 752, '2020-10-14 02:47:18', 55600, 1465, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1410,1274,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1410,114,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1410, 180, '2020-10-19 08:28:46', 208180, 346, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3511,80,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3511,1762,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3511, 994, '2020-09-11 09:11:32', 41160, 1967, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2022,1730,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2022, 383, '2020-10-12 21:25:48', 79200, 748, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2432,517,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2432,991,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2432,973,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2432,381,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2432, 548, '2020-10-15 18:47:06', 62390, 1064, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3277,2330,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3277,690,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3277,2203,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3277,820,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3277, 889, '2020-10-12 19:19:42', 48836, 1749, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1009,1152,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1009, 129, '2020-10-15 12:04:41', 35940, 248, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1803,2357,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1803,80,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1803, 296, '2020-10-03 22:55:24', 56640, 578, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2428,884,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2428,1112,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2428,341,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2428, 547, '2020-10-28 13:32:54', 59660, 1061, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1502,209,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1502, 192, '2020-09-28 19:28:19', 267000, 365, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(75,579,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(75,1348,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(75,1748,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(75, 9, '2020-09-20 21:41:37', 79870, 17, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1370,1368,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1370,166,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1370, 174, '2020-09-29 15:49:35', 67620, 334, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1232,440,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1232, 158, '2020-09-26 14:18:21', 150000, 303, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1318,521,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1318, 167, '2020-11-05 07:45:34', 135200, 321, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1698,642,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1698,222,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1698, 258, '2020-09-10 12:11:47', 150660, 499, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3485,2187,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3485,1043,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3485,2227,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3485, 985, '2020-10-17 15:03:24', 47900, 1948, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(393,631,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(393,1780,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(393,1946,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(393,952,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(393,689,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(393,2291,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(393, 49, '2020-09-17 13:47:40', 62840, 99, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2986,1804,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2986,149,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2986,2100,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2986,237,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2986,1820,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2986, 774, '2020-11-05 04:24:27', 65480, 1512, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2370,728,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2370,394,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2370,11,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2370,904,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2370, 526, '2020-10-16 10:34:10', 56440, 1019, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3284,373,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3284,427,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3284, 892, '2020-10-23 22:27:28', 91760, 1755, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(172,665,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(172,1250,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(172, 22, '2020-10-23 21:59:55', 39180, 44, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2528,936,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2528,841,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2528,710,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2528,2066,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2528, 584, '2020-10-14 05:55:14', 55060, 1135, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(605,1092,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(605,1161,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(605, 76, '2020-10-26 07:43:10', 81680, 150, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3332,763,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3332,183,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3332, 916, '2020-10-26 08:15:01', 93880, 1807, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(722,2327,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(722,145,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(722, 90, '2020-10-31 17:29:13', 55420, 179, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2012,380,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2012, 379, '2020-10-19 12:25:06', 195600, 742, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(39,1788,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(39,448,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(39, 6, '2020-11-05 23:52:49', 47780, 10, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2378,350,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2378,1659,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2378,424,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2378, 528, '2020-09-26 22:14:17', 61700, 1021, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(458,527,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(458,1263,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(458,767,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(458, 58, '2020-10-23 13:15:11', 38780, 117, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2569,417,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2569,1581,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2569,1221,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2569, 601, '2020-10-15 20:27:27', 50500, 1162, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1097,1763,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1097, 141, '2020-09-13 03:48:21', 75600, 275, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(321,1469,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(321,1521,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(321, 41, '2020-10-31 20:32:42', 49680, 84, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1734,818,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1734,1950,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1734,1943,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1734,246,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1734, 269, '2020-09-23 04:19:05', 47304, 521, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(700,1495,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(700,1092,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(700,2376,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(700,1080,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(700,2395,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(700, 86, '2020-09-09 15:07:28', 40320, 172, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(883,968,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(883,2003,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(883,483,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(883, 113, '2020-09-26 08:56:51', 266080, 219, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2177,1024,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2177,858,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2177, 446, '2020-11-01 11:49:16', 132340, 871, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2286,1327,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2286,653,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2286, 489, '2020-09-16 22:55:49', 56720, 956, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1738,970,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1738,227,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1738, 270, '2020-09-20 21:17:09', 48360, 522, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1109,1601,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1109, 143, '2020-10-15 23:01:55', 34500, 280, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2684,1008,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2684,878,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2684,2402,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2684, 652, '2020-10-27 06:45:41', 47380, 1265, 6, '14:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1857,2281,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1857, 319, '2020-09-28 10:54:51', 60760, 622, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3230,723,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3230,1259,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3230,2210,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3230, 872, '2020-10-30 03:39:43', 49000, 1713, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3187,1325,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3187,332,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3187,537,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3187, 854, '2020-09-27 15:18:03', 114400, 1678, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(474,957,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(474,120,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(474,1817,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(474, 59, '2020-10-31 21:11:58', 45800, 120, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(445,1634,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(445,1663,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(445, 56, '2020-10-16 04:12:16', 237200, 115, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1070,1789,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1070,1082,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1070,827,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1070,1146,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1070, 137, '2020-09-07 15:52:24', 37690, 269, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2508,308,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2508, 577, '2020-10-26 18:23:36', 99800, 1125, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(710,154,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(710, 88, '2020-10-06 10:37:18', 41700, 175, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2207,327,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2207, 456, '2020-09-30 19:20:46', 45600, 891, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3322,1339,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3322,1904,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3322,126,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3322, 912, '2020-09-21 14:34:40', 54300, 1796, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2921,439,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2921, 748, '2020-10-04 11:24:13', 93800, 1457, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1359,1819,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1359,850,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1359,1204,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1359,1270,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1359, 173, '2020-11-03 08:20:34', 45820, 332, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1510,1234,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1510,1464,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1510,2219,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1510, 193, '2020-09-14 08:49:28', 86820, 367, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2006,184,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2006, 377, '2020-10-01 19:21:11', 64800, 739, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2469,2120,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2469, 561, '2020-10-10 21:21:15', 81800, 1089, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(905,1545,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(905, 117, '2020-09-27 06:39:52', 41400, 226, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2998,226,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2998, 779, '2020-10-05 17:28:16', 114540, 1524, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2825,2232,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2825,342,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2825, 710, '2020-09-22 12:46:21', 57580, 1387, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(584,713,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(584,1863,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(584,2077,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(584,2034,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(584, 73, '2020-10-10 22:46:42', 47980, 142, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1913,1186,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1913,2166,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1913,285,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1913, 340, '2020-09-28 11:55:20', 75740, 664, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(136,2280,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(136,265,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(136, 18, '2020-09-26 21:58:52', 69516, 37, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2157,2049,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2157,212,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2157, 440, '2020-11-07 05:19:13', 103200, 860, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(552,6,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(552, 68, '2020-10-31 15:50:35', 39920, 135, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2257,1738,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2257, 477, '2020-09-18 19:28:34', 43600, 932, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2811,202,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2811, 704, '2020-10-21 14:30:53', 89700, 1377, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(549,667,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(549, 68, '2020-10-18 23:03:50', 417000, 135, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1869,770,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1869,2061,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1869, 323, '2020-10-01 21:03:16', 44300, 631, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3142,1712,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3142,911,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3142,495,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3142,1029,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3142,516,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3142, 836, '2020-09-12 23:00:51', 71880, 1641, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1575,1471,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1575,1914,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1575,2179,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1575, 207, '2020-10-29 06:41:52', 42616, 396, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2335,4,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2335,1196,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2335,2388,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2335,1726,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2335, 509, '2020-10-15 20:39:02', 43910, 993, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2617,2302,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2617,613,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2617,247,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2617, 622, '2020-10-03 06:40:30', 243340, 1203, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1188,2403,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1188,188,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1188, 153, '2020-11-02 15:35:34', 61150, 295, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2670,604,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2670,1632,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2670,1339,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2670,2238,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2670,494,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2670, 644, '2020-10-05 11:25:08', 43800, 1250, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3130,1994,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3130,798,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3130,1506,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3130,1242,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3130, 832, '2020-10-28 13:29:57', 61600, 1635, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(79,2343,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(79,1336,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(79,1175,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(79,1205,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(79,2105,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(79, 10, '2020-09-26 23:12:55', 69080, 18, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3471,366,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3471,503,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3471, 977, '2020-10-21 07:01:30', 155400, 1929, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1679,2329,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1679,1362,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1679,204,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1679, 251, '2020-09-27 07:31:21', 120580, 486, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3210,1133,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3210,33,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3210, 862, '2020-10-07 17:01:31', 49960, 1693, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2897,1719,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2897, 738, '2020-10-11 10:03:09', 39800, 1440, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2324,929,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2324,2278,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2324, 503, '2020-09-16 02:34:24', 51552, 984, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(941,2053,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(941,1538,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(941,448,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(941, 121, '2020-09-17 20:38:16', 63780, 233, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(305,486,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(305,231,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(305, 39, '2020-10-18 10:54:59', 62600, 79, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2748,211,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2748, 678, '2020-10-16 04:52:17', 49800, 1323, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1931,629,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1931,803,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1931, 348, '2020-10-11 00:01:18', 43200, 681, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2538,1953,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2538,129,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2538, 589, '2020-11-04 02:42:14', 62080, 1143, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(426,2033,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(426,703,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(426,916,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(426,139,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(426, 53, '2020-09-30 14:23:06', 89820, 107, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1740,801,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1740,21,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1740, 271, '2020-10-01 20:48:57', 89100, 527, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2972,1582,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2972,1158,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2972,2399,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2972,1647,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2972, 766, '2020-09-19 13:21:37', 177880, 1496, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2454,2251,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2454,1511,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2454, 554, '2020-11-05 12:29:27', 42440, 1075, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1599,395,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1599,1927,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1599, 217, '2020-11-02 08:56:55', 53340, 415, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1885,1704,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1885,1523,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1885,2284,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1885,1075,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1885,872,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1885, 329, '2020-09-19 08:47:17', 46750, 641, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3108,627,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3108,718,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3108, 822, '2020-09-09 21:29:27', 37420, 1613, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1032,16,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1032,2028,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1032,984,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1032,1708,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1032, 132, '2020-09-24 07:39:39', 96870, 256, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(192,485,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(192,2191,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(192,340,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(192,1232,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(192, 25, '2020-10-08 14:00:19', 53940, 51, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(799,1543,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(799,2414,2);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2587,849,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2587,216,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2587,1235,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2587, 608, '2020-09-15 02:17:39', 51300, 1174, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3134,2304,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3134,555,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3134,160,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3134, 833, '2020-10-12 17:10:30', 70600, 1636, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1390,1743,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1390, 177, '2020-10-29 23:52:19', 47700, 340, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1487,935,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1487,1246,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1487,2172,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1487,2078,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1487, 191, '2020-09-07 22:18:09', 113060, 361, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2119,1533,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2119,727,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2119,2180,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2119,2362,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2119, 426, '2020-09-28 23:31:05', 53480, 834, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(659,1483,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(659,128,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(659, 82, '2020-10-09 20:22:35', 119520, 165, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3064,1311,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3064,1606,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3064,1515,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3064, 807, '2020-09-08 22:18:24', 65210, 1584, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1451,472,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1451, 185, '2020-11-05 19:13:58', 319600, 353, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1180,611,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1180,239,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1180, 153, '2020-09-12 15:51:52', 84580, 295, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1662,126,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1662,793,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1662,1932,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1662,1246,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1662,2225,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1662, 244, '2020-10-14 07:13:14', 359296, 472, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(385,121,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(385,776,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(385,994,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(385,1135,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(385, 49, '2020-09-23 12:38:27', 74900, 99, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1221,1025,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1221,2406,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1221,1848,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1221,662,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1221, 157, '2020-09-17 21:07:56', 300770, 302, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(336,916,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(336,838,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(336,1900,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(336,111,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(336, 43, '2020-10-26 05:44:00', 186180, 87, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1234,588,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1234,1038,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1234,286,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1234, 159, '2020-10-21 08:04:26', 57420, 305, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2054,74,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2054,494,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2054,1096,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2054,1140,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2054, 398, '2020-10-11 08:05:43', 50880, 783, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(620,11,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(620, 78, '2020-10-24 13:30:57', 43600, 154, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(788,1084,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(788,1467,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(788, 100, '2020-09-08 07:58:51', 44640, 199, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3215,1639,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3215,1421,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3215, 864, '2020-10-22 04:13:08', 42920, 1696, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3363,797,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3363, 930, '2020-10-19 15:45:43', 41400, 1834, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(809,1227,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(809,2009,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(809,182,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(809, 103, '2020-10-30 18:03:58', 48660, 202, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1462,1291,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1462,567,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1462,8,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1462,2167,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1462, 187, '2020-09-15 07:59:50', 45820, 356, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1413,2005,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1413,1288,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1413,2101,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1413,1223,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1413, 180, '2020-09-18 01:56:19', 83740, 346, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(477,889,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(477, 59, '2020-09-16 08:11:32', 35200, 119, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1247,485,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1247,208,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1247, 160, '2020-09-15 19:51:10', 35560, 307, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3178,123,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3178,1346,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3178,228,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3178, 850, '2020-09-27 01:41:15', 122980, 1670, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3383,25,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3383,1736,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3383,1794,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3383, 939, '2020-09-17 15:02:24', 50610, 1854, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1985,1963,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1985,10,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1985,583,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1985,413,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1985, 371, '2020-10-04 17:45:17', 57080, 726, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(702,2369,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(702,1206,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(702,497,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(702, 86, '2020-09-15 13:56:44', 129750, 172, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(994,1783,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(994,111,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(994, 128, '2020-10-09 19:25:43', 73880, 246, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(189,88,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(189,246,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(189,2095,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(189, 25, '2020-09-10 06:41:14', 33000, 51, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2366,1559,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2366,1193,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2366,1537,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2366, 524, '2020-09-27 23:11:11', 49840, 1016, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3003,2157,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3003,967,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3003,312,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3003,1306,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3003, 782, '2020-09-12 07:07:33', 61710, 1531, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2690,1546,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2690,505,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2690,1750,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2690, 654, '2020-10-20 05:53:56', 62520, 1270, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2375,1607,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2375,1584,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2375,1264,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2375, 528, '2020-09-11 03:44:41', 38780, 1021, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3040,354,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3040,741,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3040,2346,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3040,1717,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3040,904,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3040,760,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3040,1225,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3040, 797, '2020-09-19 11:14:44', 81530, 1563, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2420,1840,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2420,1150,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2420, 545, '2020-10-27 01:49:31', 47080, 1056, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3265,1130,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3265, 885, '2020-09-28 07:23:46', 60800, 1741, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1434,952,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1434,649,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1434, 183, '2020-10-09 04:14:40', 59800, 351, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1411,1091,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1411,369,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1411, 180, '2020-10-20 17:06:02', 42620, 346, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2875,599,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2875,813,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2875,918,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2875, 729, '2020-11-06 16:39:06', 52160, 1424, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(642,1271,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(642,1438,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(642,2355,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(642, 80, '2020-10-06 23:46:14', 78824, 158, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2123,1397,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2123,1163,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2123, 429, '2020-10-08 17:35:42', 115720, 840, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1425,1243,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1425,378,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1425, 181, '2020-09-08 21:15:31', 79180, 347, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(849,2390,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(849,1494,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(849,1156,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(849,813,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(849, 108, '2020-09-26 02:58:21', 84240, 208, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(572,1947,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(572,1200,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(572,2219,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(572,682,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(572,1598,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(572, 71, '2020-10-29 13:55:43', 78170, 139, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2263,880,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2263, 479, '2020-09-08 23:23:50', 74700, 934, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(423,2043,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(423,1461,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(423,1274,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(423,2312,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(423, 53, '2020-09-28 13:32:58', 68580, 107, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1440,384,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1440,1592,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1440,1369,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1440,1205,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1440,1656,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1440, 183, '2020-11-03 11:28:37', 59520, 350, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1549,2143,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1549,1191,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1549,2368,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1549,174,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1549, 198, '2020-10-19 17:42:17', 46340, 377, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2091,51,1);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2173,1412,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2173,712,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2173,177,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2173, 445, '2020-10-23 07:08:06', 215860, 870, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1376,2411,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1376,881,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1376,1605,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1376, 174, '2020-09-20 18:07:44', 90760, 334, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1078,1649,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1078,2307,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1078,2244,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1078, 138, '2020-11-06 16:13:43', 48120, 270, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1136,967,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1136,1077,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1136,1889,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1136,2267,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1136,1510,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1136,1891,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1136, 147, '2020-10-06 22:00:01', 46580, 286, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(957,1121,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(957,791,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(957,901,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(957, 122, '2020-10-04 19:46:05', 124150, 235, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3137,137,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3137,320,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3137,880,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3137, 834, '2020-09-15 01:48:11', 119540, 1638, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2468,1820,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2468,391,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2468, 560, '2020-09-30 06:00:21', 136300, 1087, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3346,606,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3346,1487,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3346, 921, '2020-09-23 12:22:35', 35080, 1816, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2032,781,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2032,589,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2032,1497,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2032,1406,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2032, 388, '2020-10-30 09:29:35', 52620, 763, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3146,2165,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3146,1447,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3146,2404,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3146,2177,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3146, 837, '2020-10-09 21:39:02', 51360, 1642, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1459,1775,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1459,1344,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1459,1317,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1459, 186, '2020-10-20 00:41:14', 36960, 354, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2347,2235,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2347,2237,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2347,2007,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2347, 516, '2020-10-15 08:21:42', 59520, 1004, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2529,2150,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2529,1805,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2529, 584, '2020-09-30 22:32:23', 44740, 1136, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2254,1120,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2254,1872,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2254,1459,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2254, 476, '2020-10-28 00:45:41', 31680, 930, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1521,2274,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1521,342,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1521,2406,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1521,1025,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1521, 195, '2020-10-29 11:58:00', 56760, 371, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(733,1505,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(733,1202,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(733,2160,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(733,203,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(733, 92, '2020-10-08 09:11:30', 110520, 181, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1029,1124,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1029,756,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1029,2027,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1029, 132, '2020-10-05 19:54:10', 39540, 256, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(864,1092,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(864,407,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(864,1125,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(864, 110, '2020-10-10 03:39:04', 48640, 213, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3482,1755,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3482, 983, '2020-10-10 23:27:50', 39800, 1944, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2249,2180,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2249,238,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2249, 473, '2020-09-24 04:06:37', 79500, 923, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1855,2304,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1855,1556,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1855,1956,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1855,1087,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1855,1209,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1855, 319, '2020-10-06 05:37:59', 59520, 622, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2728,2090,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2728,1877,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2728,415,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2728, 669, '2020-10-13 16:37:24', 110680, 1303, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3088,1602,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3088, 815, '2020-09-14 15:38:06', 125700, 1595, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2993,1519,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2993,1354,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2993,957,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2993,1931,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2993,1989,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2993,1681,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2993, 778, '2020-09-25 09:14:34', 64700, 1522, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(691,2045,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(691,130,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(691, 85, '2020-10-15 00:48:25', 293960, 171, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2817,663,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2817, 705, '2020-10-06 22:36:52', 299700, 1378, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(935,823,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(935,1546,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(935,788,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(935,1629,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(935, 121, '2020-11-04 04:38:08', 50640, 233, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(706,1393,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(706,144,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(706, 87, '2020-10-21 17:32:55', 143480, 174, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3166,1903,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3166,172,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3166,644,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3166, 845, '2020-10-16 18:54:10', 45540, 1659, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3081,1718,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3081,397,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3081, 812, '2020-10-27 00:55:38', 45570, 1591, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2227,780,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2227,261,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2227, 464, '2020-10-19 07:26:16', 53540, 904, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2266,1720,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2266,1695,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2266,292,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2266,887,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2266, 480, '2020-09-28 12:35:08', 74980, 936, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(533,53,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(533, 66, '2020-09-17 05:49:43', 149400, 132, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1333,1169,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1333,2137,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1333,1228,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1333, 170, '2020-11-07 06:24:28', 94160, 325, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1324,599,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1324,2003,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1324,976,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1324,380,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1324, 168, '2020-10-11 13:59:47', 140520, 322, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2400,368,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2400,303,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2400, 536, '2020-09-08 05:37:59', 31140, 1034, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3314,971,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3314,967,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3314,1350,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3314,2080,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3314, 907, '2020-11-04 19:52:55', 108720, 1787, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1609,535,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1609,416,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1609,2301,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1609,1236,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1609, 221, '2020-10-12 21:25:28', 52500, 427, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2796,1406,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2796,1430,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2796,917,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2796, 698, '2020-10-20 06:52:45', 64660, 1364, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(502,1881,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(502,635,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(502,718,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(502, 62, '2020-09-12 19:28:54', 70390, 124, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(249,1272,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(249,395,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(249, 32, '2020-10-21 23:39:13', 51040, 68, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2696,1710,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2696,1781,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2696,1836,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2696,632,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2696, 656, '2020-10-28 22:26:32', 47880, 1274, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(565,784,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(565,670,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(565, 70, '2020-11-04 22:10:58', 37540, 137, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2497,173,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2497,52,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2497, 573, '2020-10-01 22:40:07', 69320, 1116, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(485,385,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(485,1693,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(485,1435,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(485,1325,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(485, 60, '2020-11-06 11:06:03', 56580, 121, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2950,1197,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2950,1255,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2950,552,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2950, 759, '2020-10-25 13:56:14', 48540, 1478, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(303,872,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(303,1261,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(303,34,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(303, 39, '2020-10-29 10:31:19', 47280, 79, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2746,999,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2746,1098,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2746,1989,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2746,1809,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2746,1986,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2746,2204,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2746, 677, '2020-10-28 06:44:25', 43940, 1322, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1230,1324,3);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2196,4,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2196, 452, '2020-09-19 00:33:42', 47920, 884, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2943,1473,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2943,137,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2943,388,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2943, 756, '2020-10-05 14:55:09', 54320, 1473, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1087,718,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1087,365,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1087,2177,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1087,2026,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1087,510,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1087, 140, '2020-10-13 04:53:09', 72600, 274, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2694,780,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2694,1933,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2694, 655, '2020-09-26 03:22:26', 50400, 1272, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1749,855,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1749,1360,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1749,2106,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1749,722,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1749,1315,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1749, 273, '2020-10-27 16:25:26', 53480, 530, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1643,1035,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1643,1950,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1643,33,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1643, 237, '2020-09-17 07:33:02', 45252, 463, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2323,122,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2323,1361,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2323,152,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2323, 503, '2020-09-07 15:23:11', 89032, 984, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3459,635,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3459,1159,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3459,1475,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3459, 972, '2020-10-09 01:43:38', 43300, 1920, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1725,411,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1725,1074,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1725, 266, '2020-10-20 04:06:55', 46860, 515, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(546,2420,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(546, 67, '2020-10-06 18:50:43', 40000, 134, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1923,1948,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1923,1889,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1923,812,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1923, 346, '2020-10-24 23:03:22', 53080, 678, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2093,1278,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2093,1637,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2093,1777,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2093, 417, '2020-11-04 15:49:25', 76180, 819, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1420,2187,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1420,1891,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1420,792,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1420,1558,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1420,634,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1420, 181, '2020-09-11 19:48:54', 81100, 347, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1088,1307,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1088,477,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1088, 140, '2020-10-08 10:58:22', 47580, 274, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1702,1586,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1702,2060,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1702,159,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1702, 259, '2020-10-05 23:35:08', 55720, 501, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3139,1866,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3139,194,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3139, 835, '2020-09-24 20:07:30', 55520, 1640, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1530,1713,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1530,1570,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1530, 196, '2020-11-07 04:56:29', 37620, 373, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(893,871,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(893,1218,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(893,1349,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(893,1141,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(893, 115, '2020-10-22 03:14:52', 51860, 223, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(721,786,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(721,1103,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(721,16,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(721, 90, '2020-11-03 06:40:51', 37380, 179, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1670,389,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1670,239,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1670, 247, '2020-11-01 07:42:17', 84400, 478, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2609,2142,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2609,919,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2609,1194,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2609, 618, '2020-10-25 16:46:43', 43820, 1197, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2209,2295,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2209,1248,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2209,717,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2209, 458, '2020-10-07 16:00:50', 50600, 894, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1874,20,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1874,1085,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1874,154,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1874, 325, '2020-10-27 21:02:23', 58400, 634, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1207,1625,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1207,2142,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1207,2365,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1207, 156, '2020-10-23 17:20:14', 50320, 300, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2481,2078,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2481, 567, '2020-10-10 19:39:13', 62700, 1103, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2218,1782,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2218,1079,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2218, 460, '2020-09-30 20:40:21', 77820, 897, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(375,264,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(375,980,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(375, 47, '2020-09-13 18:02:10', 38980, 96, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1547,271,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1547,1205,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1547,802,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1547,387,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1547,2178,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1547, 198, '2020-09-27 02:02:11', 49240, 378, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2560,1952,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2560,1240,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2560,1002,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2560,2377,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2560,1468,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2560, 596, '2020-10-31 04:18:30', 49580, 1156, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2039,2149,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2039,1830,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2039,2354,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2039,11,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2039, 391, '2020-09-10 22:07:34', 42100, 769, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(404,411,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(404,690,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(404,946,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(404,1783,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(404,338,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(404,1357,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(404, 50, '2020-10-12 18:58:13', 35500, 102, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1895,853,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1895,1858,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1895,948,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1895,235,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1895, 332, '2020-10-29 14:21:07', 79280, 646, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(627,1795,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(627,2251,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(627,320,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(627,1702,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(627, 79, '2020-09-14 16:44:57', 68640, 156, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(810,942,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(810,586,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(810,326,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(810, 103, '2020-10-11 05:33:01', 57880, 202, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(821,2084,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(821,1205,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(821,290,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(821,83,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(821, 104, '2020-09-08 04:02:17', 95900, 203, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2221,1589,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2221, 461, '2020-09-24 21:19:05', 47700, 899, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2721,1456,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2721,1670,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2721, 665, '2020-09-11 04:04:32', 64060, 1294, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3069,1766,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3069,1796,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3069, 808, '2020-10-23 12:06:01', 46160, 1585, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2416,141,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2416,268,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2416,1527,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2416, 544, '2020-09-22 19:55:04', 72640, 1054, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(60,563,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(60,560,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(60,449,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(60, 8, '2020-10-09 05:11:38', 34780, 14, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(529,142,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(529, 66, '2020-09-16 14:54:36', 79800, 132, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1561,1556,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1561,1324,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1561,744,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1561, 202, '2020-09-24 01:59:55', 53280, 384, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2761,824,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2761,1238,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2761,1938,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2761,1621,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2761, 683, '2020-10-12 21:33:15', 99960, 1336, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2011,61,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2011,2248,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2011,2151,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2011,1834,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2011,993,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2011, 379, '2020-11-02 21:14:06', 48400, 743, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(496,320,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(496,2291,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(496, 61, '2020-09-30 15:46:10', 41900, 123, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(971,2172,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(971,2063,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(971,1109,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(971,1784,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(971, 124, '2020-10-23 18:24:56', 35200, 237, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(319,1638,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(319,911,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(319,1815,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(319, 41, '2020-10-26 21:41:27', 58720, 83, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(622,90,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(622, 78, '2020-10-29 17:34:03', 59900, 154, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(674,124,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(674,2294,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(674,1820,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(674, 83, '2020-09-13 12:30:34', 55120, 166, 5, '18:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2902,904,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2902,1754,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2902,536,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2902, 739, '2020-09-21 23:09:44', 249700, 1441, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3065,2377,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3065,800,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3065, 807, '2020-10-21 14:33:14', 37400, 1583, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2493,2286,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2493, 572, '2020-10-19 02:50:55', 49600, 1115, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3510,410,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3510,1422,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3510, 993, '2020-10-16 19:45:51', 45080, 1964, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2639,2137,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2639,2305,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2639, 630, '2020-09-13 02:56:10', 40980, 1218, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1888,69,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1888, 330, '2020-10-22 12:04:02', 39600, 642, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3313,131,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3313, 907, '2020-10-16 15:00:33', 396000, 1787, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3105,2165,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3105,2069,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3105, 821, '2020-09-09 15:59:36', 113200, 1610, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1623,1567,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1623, 228, '2020-11-06 11:12:13', 155400, 444, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(980,2293,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(980,98,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(980, 126, '2020-09-15 07:53:00', 79460, 242, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(645,1673,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(645,1139,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(645, 81, '2020-10-03 09:56:41', 99954, 162, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2140,231,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2140, 435, '2020-10-18 04:34:48', 50700, 850, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(346,1832,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(346,1634,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(346, 44, '2020-10-07 03:58:56', 55520, 89, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1158,948,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1158,1336,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1158, 150, '2020-10-12 22:29:33', 42820, 291, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2957,28,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2957,1118,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2957,341,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2957, 762, '2020-09-19 11:01:39', 67900, 1485, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2114,671,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2114,415,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2114, 425, '2020-09-08 06:41:29', 157540, 833, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1887,1393,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1887,185,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1887, 329, '2020-09-25 00:20:00', 121160, 641, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(117,1838,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(117,1941,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(117,1423,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(117,1943,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(117, 16, '2020-09-16 17:54:15', 52652, 31, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1214,1488,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1214, 156, '2020-10-17 00:56:03', 33920, 301, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(47,32,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(47,746,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(47, 6, '2020-09-11 18:28:21', 39100, 10, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1495,1383,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1495,2289,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1495,1152,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1495, 192, '2020-10-15 23:22:06', 71360, 366, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(437,962,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(437,556,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(437,39,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(437,2277,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(437,1834,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(437, 54, '2020-10-18 14:18:46', 50580, 110, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1950,862,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1950,447,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1950, 355, '2020-10-01 18:27:46', 174000, 691, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1603,121,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1603,1297,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1603,1995,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1603,1119,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1603,308,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1603, 219, '2020-09-15 00:25:26', 142740, 421, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(738,1425,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(738,1111,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(738,1579,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(738, 92, '2020-10-19 15:54:48', 67136, 181, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3468,930,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3468,1550,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3468, 976, '2020-09-11 15:06:24', 35720, 1927, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(281,1353,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(281,1459,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(281,1943,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(281, 37, '2020-10-03 06:30:07', 47380, 75, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1485,176,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1485,79,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1485,288,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1485,2096,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1485, 190, '2020-10-13 06:52:53', 33900, 360, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(537,1387,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(537,1387,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(537,1424,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(537,2206,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(537, 67, '2020-09-25 08:02:42', 39840, 134, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1542,1609,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1542,1617,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1542,1314,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1542,1531,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1542,131,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1542, 197, '2020-10-19 04:24:38', 229320, 376, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(465,1495,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(465,22,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(465, 58, '2020-10-11 07:22:05', 53840, 118, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(936,829,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(936,268,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(936,661,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(936,1040,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(936, 121, '2020-10-17 14:50:05', 63020, 234, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1858,2102,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1858,2208,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1858,2184,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1858,1350,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1858,896,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1858, 319, '2020-09-09 11:42:23', 95620, 622, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1514,2246,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1514,36,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1514,1884,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1514, 194, '2020-09-30 05:19:59', 74460, 368, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(564,1523,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(564,1878,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(564,2104,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(564,1531,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(564,4,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(564, 70, '2020-11-04 14:12:39', 52700, 138, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(782,1290,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(782,1204,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(782,341,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(782, 99, '2020-10-12 02:39:48', 57840, 197, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2782,950,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2782,945,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2782,1369,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2782, 693, '2020-10-26 19:20:16', 45680, 1354, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2139,1719,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2139,834,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2139, 435, '2020-09-30 02:14:13', 57600, 850, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(48,2089,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(48,2277,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(48,1436,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(48, 6, '2020-10-14 16:59:26', 40040, 10, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2551,628,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2551,646,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2551,22,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2551,474,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2551, 594, '2020-10-13 09:55:53', 95720, 1152, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2689,1896,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2689,2247,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2689,2072,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2689,1817,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2689,160,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2689, 653, '2020-10-12 00:03:03', 47500, 1268, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2062,1846,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2062,661,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2062,1293,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2062,629,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2062, 403, '2020-10-05 10:45:48', 56640, 792, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1590,2262,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1590,2002,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1590,1899,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1590,1920,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1590,1659,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1590, 213, '2020-11-06 03:53:37', 99620, 406, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(475,494,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(475,1945,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(475,1464,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(475, 59, '2020-09-22 22:37:01', 41000, 119, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2558,275,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2558,1496,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2558, 596, '2020-09-29 16:09:47', 52140, 1155, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2044,309,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2044,971,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2044,1264,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2044, 393, '2020-10-12 18:49:52', 35760, 773, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1015,1561,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1015,562,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1015,1474,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1015,850,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1015, 130, '2020-09-07 12:10:19', 63740, 251, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1757,1810,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1757,1604,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1757,235,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1757,2203,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1757, 276, '2020-10-01 06:27:28', 47516, 537, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(519,2129,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(519,2368,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(519,489,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(519, 64, '2020-09-22 18:07:14', 76710, 127, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(884,833,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(884,780,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(884,1052,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(884, 113, '2020-10-24 15:35:37', 51560, 219, 2, '10:00');

INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(838, 106, '2020-10-07 18:38:20', 48780, 206, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3502,1516,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3502,1119,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3502, 991, '2020-11-06 14:54:48', 114760, 1962, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1736,1042,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1736,307,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1736, 270, '2020-10-12 03:16:08', 223520, 523, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2296,11,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2296,1036,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2296, 492, '2020-09-19 16:07:54', 141900, 962, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3366,187,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3366,1675,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3366, 931, '2020-10-28 12:29:45', 83500, 1836, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3357,1699,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3357, 926, '2020-09-20 07:35:12', 107700, 1825, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(163,1263,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(163,1476,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(163,1742,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(163,1087,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(163, 21, '2020-10-02 12:37:57', 51840, 42, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3304,1293,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3304,2074,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3304,2055,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3304,447,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3304, 900, '2020-09-24 06:36:53', 144460, 1774, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(318,416,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(318,1369,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(318,746,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(318, 41, '2020-10-23 09:47:47', 56220, 82, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(352,821,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(352,1217,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(352, 45, '2020-10-14 20:39:12', 75840, 90, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2290,2221,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2290, 490, '2020-10-02 20:21:42', 49920, 959, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(885,1277,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(885,2164,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(885, 114, '2020-10-28 08:05:22', 57520, 222, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1573,489,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1573,417,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1573, 205, '2020-09-30 19:25:22', 54235, 392, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1273,1930,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1273, 162, '2020-09-23 04:19:08', 47600, 310, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1125,1920,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1125,1874,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1125,650,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1125, 146, '2020-11-03 11:34:12', 47520, 283, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2949,762,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2949, 758, '2020-10-24 03:05:30', 39600, 1476, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1204,1012,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1204,1269,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1204,325,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1204, 156, '2020-09-15 14:01:18', 151020, 301, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2492,2264,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2492,2235,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2492, 571, '2020-09-26 07:43:02', 75520, 1113, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1066,2237,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1066,1878,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1066,244,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1066, 137, '2020-10-11 23:05:35', 111720, 269, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(972,47,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(972,2174,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(972, 124, '2020-09-08 16:02:35', 51780, 238, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(597,1000,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(597,1812,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(597,1151,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(597,1028,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(597, 75, '2020-11-01 08:52:09', 39980, 146, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2779,698,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2779,433,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2779, 691, '2020-10-24 20:40:22', 89440, 1349, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1220,2055,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1220,1502,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1220,587,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1220,66,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1220,2092,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1220, 157, '2020-09-13 06:02:20', 66460, 302, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1383,1466,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1383,597,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1383, 176, '2020-10-31 17:29:17', 43440, 339, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(807,2425,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(807,76,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(807, 103, '2020-10-18 10:42:45', 41100, 202, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2572,1901,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2572,60,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2572, 603, '2020-10-19 12:37:51', 82740, 1166, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(233,738,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(233,1951,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(233,1573,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(233, 31, '2020-09-18 18:13:40', 100140, 66, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(835,644,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(835,2213,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(835, 106, '2020-11-07 02:39:02', 32880, 206, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1492,1024,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1492,253,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1492, 191, '2020-10-15 12:13:40', 69120, 362, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3440,2006,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3440, 964, '2020-10-08 00:47:55', 59700, 1904, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1396,6,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1396,2339,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1396, 178, '2020-10-17 09:34:34', 121740, 343, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2701,1448,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2701,1912,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2701,668,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2701, 658, '2020-10-06 17:53:00', 51740, 1277, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2271,91,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2271, 482, '2020-10-12 00:10:39', 80700, 938, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3027,670,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3027,942,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3027,748,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3027,2096,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3027, 792, '2020-11-03 08:57:39', 39020, 1553, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1649,852,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1649,1497,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1649,620,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1649,650,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1649, 238, '2020-10-16 10:05:28', 60100, 464, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2963,1026,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2963,2052,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2963,227,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2963, 764, '2020-09-15 00:49:35', 59300, 1492, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2055,1872,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2055,2215,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2055,953,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2055, 399, '2020-10-22 13:40:47', 43110, 786, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2314,2001,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2314,101,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2314, 500, '2020-09-26 09:14:16', 308120, 977, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2677,1622,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2677, 648, '2020-09-14 09:35:36', 71200, 1257, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2489,1502,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2489,2059,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2489,614,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2489,487,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2489, 570, '2020-10-02 01:41:10', 84620, 1112, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3373,2157,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3373,1724,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3373, 935, '2020-10-20 00:06:28', 73080, 1845, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1266,1507,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1266,1619,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1266, 162, '2020-09-18 16:22:33', 42720, 311, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1938,1087,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1938,171,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1938,180,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1938, 350, '2020-10-03 05:38:35', 41740, 683, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1288,1601,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1288,1301,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1288, 164, '2020-10-30 07:55:44', 46940, 316, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(767,1139,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(767,2326,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(767, 97, '2020-09-14 03:06:52', 49500, 194, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2083,911,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2083,1838,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2083,488,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2083, 412, '2020-09-30 07:06:42', 39640, 809, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1371,1172,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1371,2119,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1371,677,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1371, 174, '2020-11-03 18:42:23', 313360, 334, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2658,939,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2658,724,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2658,382,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2658, 638, '2020-10-29 22:22:32', 53880, 1236, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1350,909,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1350, 172, '2020-10-11 07:11:32', 66000, 331, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2967,738,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2967,2153,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2967,705,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2967,184,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2967, 765, '2020-10-04 11:40:18', 159540, 1493, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1215,2085,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1215,332,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1215, 157, '2020-10-01 13:21:35', 38240, 302, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2364,1719,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2364, 524, '2020-11-02 18:01:49', 79600, 1014, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(758,1556,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(758,1663,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(758, 96, '2020-11-07 08:48:42', 217300, 189, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(649,412,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(649,664,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(649, 81, '2020-10-08 19:09:20', 36680, 161, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2440,1194,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2440,1864,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2440,1343,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2440,481,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2440, 550, '2020-10-17 01:26:58', 48050, 1067, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2256,53,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2256, 477, '2020-09-12 06:10:42', 49800, 932, 3, '17:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2925,1529,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2925,2234,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2925,1609,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2925, 749, '2020-09-14 12:48:33', 45300, 1459, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2315,833,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2315,1374,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2315,1212,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2315,1572,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2315, 500, '2020-10-24 16:35:20', 65140, 976, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(119,970,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(119,2397,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(119,1618,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(119,2061,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(119, 16, '2020-10-26 01:15:36', 72760, 30, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2536,1345,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2536,1674,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2536, 588, '2020-09-22 09:50:19', 118680, 1142, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1115,1453,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1115,555,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1115,1566,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1115,783,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1115, 144, '2020-09-21 06:32:17', 69380, 281, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2376,130,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2376, 528, '2020-09-30 11:12:16', 129000, 1021, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2606,756,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2606,144,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2606, 617, '2020-09-29 09:24:42', 286500, 1193, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3002,194,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3002,2141,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3002,111,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3002, 781, '2020-10-24 14:00:00', 107300, 1529, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2942,955,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2942,1286,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2942,1500,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2942, 756, '2020-10-04 11:09:39', 54400, 1473, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1039,39,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1039,1213,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1039,474,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1039, 133, '2020-10-16 18:25:59', 89100, 259, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(493,5,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(493,183,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(493, 61, '2020-09-13 09:07:44', 74240, 123, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2877,2396,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2877,235,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2877,357,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2877, 731, '2020-09-29 21:52:44', 37640, 1427, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1304,903,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1304,1306,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1304, 166, '2020-11-06 21:13:38', 55860, 319, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(735,1066,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(735,83,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(735,801,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(735, 92, '2020-10-06 16:18:36', 56180, 181, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(743,250,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(743, 93, '2020-10-11 21:23:06', 39920, 183, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(902,1484,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(902,375,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(902, 117, '2020-09-14 05:05:21', 72470, 227, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2304,1139,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2304, 496, '2020-09-24 05:09:47', 47700, 969, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1928,417,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1928,1806,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1928,1040,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1928, 347, '2020-09-22 23:35:41', 68440, 680, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(86,932,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(86,932,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(86, 10, '2020-11-07 08:34:58', 79200, 18, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1949,2018,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1949,907,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1949,2337,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1949, 354, '2020-11-06 18:10:05', 49600, 690, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2799,199,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2799,903,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2799, 699, '2020-09-10 00:22:24', 39860, 1365, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2540,1035,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2540,1648,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2540, 590, '2020-10-21 01:36:21', 87215, 1144, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3083,563,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3083,551,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3083,855,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3083,1258,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3083, 813, '2020-09-18 04:44:57', 46540, 1592, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3416,1668,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3416,260,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3416,445,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3416, 951, '2020-09-30 10:48:03', 84210, 1875, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1768,895,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1768, 281, '2020-09-18 00:18:00', 47600, 549, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(81,1346,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(81,1840,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(81,2378,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(81, 10, '2020-09-24 08:04:10', 68580, 18, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2183,671,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2183,284,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2183, 449, '2020-09-20 12:15:48', 126960, 879, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1140,1441,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1140,759,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1140,861,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1140, 147, '2020-10-31 09:19:52', 38300, 286, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2645,1544,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2645,152,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2645, 634, '2020-10-08 05:12:34', 215500, 1228, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1176,1759,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1176, 152, '2020-09-28 00:52:29', 51600, 294, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3295,1795,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3295,1216,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3295,603,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3295,2010,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3295,1839,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3295, 895, '2020-10-31 14:49:42', 38420, 1764, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1511,1040,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1511,396,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1511, 194, '2020-10-18 19:55:41', 52740, 370, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3384,1594,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3384,11,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3384, 939, '2020-09-09 20:44:12', 38400, 1853, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(24,1194,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(24,1970,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(24, 3, '2020-10-06 02:30:00', 39840, 5, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2251,1904,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2251,285,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2251, 474, '2020-09-16 04:50:51', 167360, 926, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1867,1017,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1867,617,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1867,791,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1867,824,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1867, 322, '2020-10-20 00:21:29', 89760, 630, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1249,63,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1249,2391,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1249,1168,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1249, 160, '2020-10-01 17:45:30', 46240, 307, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(284,2025,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(284,1343,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(284,706,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(284, 37, '2020-10-26 06:08:41', 39340, 75, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1664,2275,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1664,2068,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1664, 245, '2020-10-22 05:59:14', 42140, 475, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(265,2340,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(265,1088,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(265,1861,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(265, 35, '2020-09-30 10:46:03', 32280, 73, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3093,744,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3093,1695,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3093,502,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3093, 817, '2020-09-19 06:02:35', 54660, 1599, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(46,1328,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(46,1997,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(46, 6, '2020-10-16 21:24:19', 41460, 10, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3110,1826,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3110,1234,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3110,1407,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3110,531,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3110, 823, '2020-11-02 11:19:59', 33480, 1615, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(892,997,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(892,796,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(892,2418,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(892,184,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(892, 115, '2020-11-07 05:58:56', 108870, 223, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(270,1151,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(270,1969,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(270,621,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(270,1235,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(270, 35, '2020-11-05 06:42:28', 49420, 73, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1147,592,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1147,2144,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1147, 148, '2020-09-23 01:30:15', 46660, 287, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1829,48,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1829,799,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1829,627,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1829,401,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1829, 307, '2020-09-29 11:10:03', 54900, 597, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2070,2265,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2070,100,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2070,1595,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2070,2156,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2070, 407, '2020-10-28 16:56:17', 41324, 801, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2049,1245,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2049,561,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2049,619,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2049,624,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2049, 396, '2020-10-03 11:14:24', 48670, 778, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2312,1951,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2312,1728,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2312, 498, '2020-09-16 23:44:50', 184185, 972, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2888,1356,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2888,304,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2888, 735, '2020-09-19 16:22:49', 38560, 1435, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(673,268,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(673,1064,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(673,2196,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(673,1201,4);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1112,942,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1112,1337,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1112,309,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1112, 143, '2020-10-30 13:19:48', 79660, 279, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(266,1962,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(266,1628,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(266, 35, '2020-11-07 11:10:04', 200700, 73, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1650,2257,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1650,679,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1650, 239, '2020-10-14 07:23:26', 78300, 465, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3444,2175,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3444, 966, '2020-09-22 13:54:13', 41040, 1909, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2774,1159,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2774,1822,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2774, 689, '2020-10-15 07:47:48', 49660, 1346, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2179,774,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2179,1126,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2179,1966,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2179, 446, '2020-10-02 09:07:28', 79180, 873, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1133,1078,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1133,2368,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1133,1392,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1133,401,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1133, 147, '2020-09-15 12:23:40', 36660, 286, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1695,1452,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1695,721,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1695,2045,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1695,2164,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1695, 257, '2020-11-03 06:42:06', 81440, 498, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2163,104,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2163, 441, '2020-09-28 04:40:03', 88000, 862, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(297,1121,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(297,2383,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(297,1,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(297, 38, '2020-10-25 00:58:05', 52720, 78, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(793,906,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(793,2252,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(793,1246,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(793, 101, '2020-10-26 22:13:31', 48840, 200, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(180,2216,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(180,2133,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(180,1582,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(180,1428,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(180, 23, '2020-09-16 05:24:09', 49440, 46, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2438,512,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2438, 550, '2020-10-15 06:44:22', 59700, 1066, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(91,149,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(91,1518,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(91,718,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(91, 11, '2020-10-07 05:34:59', 65500, 20, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(540,565,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(540,137,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(540,1776,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(540, 67, '2020-09-14 10:41:47', 56760, 134, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2978,2159,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2978,1134,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2978, 768, '2020-11-06 03:21:18', 115800, 1501, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1504,2173,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1504,314,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1504, 193, '2020-10-28 14:12:35', 51880, 367, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(840,2157,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(840,996,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(840,1047,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(840,9,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(840, 107, '2020-10-30 14:54:00', 41580, 207, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1863,1420,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1863,286,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1863,1292,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1863, 321, '2020-10-08 02:20:42', 59460, 627, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(867,1414,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(867,1154,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(867, 111, '2020-10-01 11:02:28', 82540, 214, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3418,1759,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3418,749,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3418,2239,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3418, 952, '2020-09-26 10:55:32', 64700, 1879, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(335,75,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(335, 43, '2020-09-28 23:10:15', 155700, 88, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1438,1326,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1438,2140,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1438,1965,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1438,1699,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1438, 183, '2020-10-27 18:48:39', 139740, 351, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3090,2281,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3090,1180,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3090, 816, '2020-11-02 21:37:13', 64900, 1597, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3159,784,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3159,665,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3159,1610,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3159, 842, '2020-10-15 16:57:16', 53510, 1653, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2981,874,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2981, 770, '2020-10-22 12:21:43', 49800, 1505, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1812,2007,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1812,1580,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1812, 300, '2020-10-05 16:59:44', 32960, 586, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(381,2320,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(381, 48, '2020-09-21 10:15:40', 51200, 97, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2393,1441,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2393,1295,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2393,1732,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2393,853,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2393,1280,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2393,1466,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2393,1641,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2393, 534, '2020-09-22 08:47:35', 75980, 1029, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3066,1682,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3066,360,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3066,1568,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3066, 807, '2020-11-07 09:54:42', 162980, 1584, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2126,1442,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2126,2407,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2126,1979,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2126,2190,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2126, 430, '2020-11-01 06:04:57', 60840, 841, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2261,1592,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2261,1722,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2261, 478, '2020-09-07 17:56:27', 57615, 933, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2580,1516,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2580,1141,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2580,2008,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2580, 606, '2020-09-30 21:59:28', 63820, 1170, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(511,891,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(511,275,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(511,2144,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(511, 63, '2020-09-24 05:46:46', 50160, 126, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(582,2296,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(582,1208,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(582,447,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(582, 73, '2020-10-26 15:21:12', 145050, 142, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(855,1271,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(855,213,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(855,1380,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(855, 109, '2020-10-21 12:12:31', 36972, 211, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1486,1886,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1486,1940,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1486, 191, '2020-10-13 15:53:46', 57880, 363, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(15,123,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(15, 3, '2020-10-17 17:27:09', 67600, 4, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3125,1644,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3125, 828, '2020-11-03 22:53:58', 38400, 1627, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(428,1874,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(428,1067,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(428,842,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(428, 53, '2020-10-16 03:22:38', 33680, 108, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2042,791,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2042,752,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2042,2296,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2042, 393, '2020-10-20 02:03:54', 98460, 773, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(903,1385,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(903,2338,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(903, 117, '2020-10-27 07:54:22', 111980, 226, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(5,1715,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(5,1521,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(5,67,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(5, 1, '2020-11-01 01:54:43', 56820, 1, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3038,2306,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3038,515,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3038, 797, '2020-10-06 18:58:52', 125140, 1563, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1348,565,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1348,494,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1348,1878,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1348, 172, '2020-10-16 20:29:16', 48780, 331, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1170,155,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1170,1067,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1170,484,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1170, 152, '2020-10-29 06:51:45', 67960, 294, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2789,735,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2789,399,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2789,727,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2789, 696, '2020-10-14 10:33:37', 42960, 1360, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1523,56,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1523,1991,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1523,2010,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1523,1835,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1523,2009,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1523, 195, '2020-10-06 23:06:49', 48580, 372, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2720,2133,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2720,432,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2720,1269,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2720,1996,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2720,260,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2720, 665, '2020-09-15 02:46:12', 81820, 1294, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1538,170,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1538, 197, '2020-11-05 04:55:01', 164880, 375, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2451,1254,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2451, 553, '2020-11-06 09:21:37', 33920, 1073, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2852,507,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2852,682,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2852, 720, '2020-10-08 03:20:54', 44980, 1404, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1290,1491,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1290,2189,4);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3351,587,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3351,2264,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3351, 923, '2020-09-17 16:32:29', 57040, 1820, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(586,1694,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(586,2254,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(586, 74, '2020-10-01 05:21:47', 53640, 145, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1196,1224,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1196,1017,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1196,2172,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1196,972,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1196,697,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1196, 154, '2020-09-24 18:05:36', 132410, 296, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1927,1620,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1927,818,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1927,142,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1927, 347, '2020-09-24 15:31:41', 345600, 679, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(282,1207,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(282,702,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(282, 37, '2020-10-13 17:19:43', 53360, 75, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3387,4,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3387,295,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3387,1557,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3387,1231,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3387,1734,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3387, 940, '2020-09-18 11:01:19', 101805, 1855, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(116,1447,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(116,2346,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(116,1740,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(116,2388,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(116,1018,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(116,1093,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(116, 16, '2020-11-01 20:16:45', 46350, 31, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2607,1994,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2607,1661,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2607,263,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2607, 617, '2020-10-11 16:54:40', 67100, 1193, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(637,45,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(637,2408,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(637,744,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(637,23,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(637, 80, '2020-11-07 11:51:07', 79050, 159, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2061,1638,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2061,1334,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2061,2383,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2061, 402, '2020-10-11 05:02:27', 39300, 791, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1600,1543,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1600,1709,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1600, 217, '2020-11-07 05:48:45', 53400, 416, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2068,1950,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2068,1062,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2068,1019,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2068,1840,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2068,901,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2068, 405, '2020-09-09 21:44:31', 350514, 797, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3490,888,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3490, 987, '2020-10-07 13:21:31', 270000, 1952, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1437,393,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1437,1824,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1437,543,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1437, 183, '2020-10-12 18:13:20', 66800, 351, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3238,1391,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3238,1247,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3238,2250,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3238,2351,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3238, 875, '2020-09-12 07:30:23', 55360, 1717, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3095,953,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3095,453,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3095, 817, '2020-11-03 11:52:09', 49050, 1600, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2097,1487,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2097,1702,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2097, 418, '2020-10-04 14:30:09', 76580, 823, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1598,1354,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1598,1676,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1598, 217, '2020-10-25 03:27:48', 59730, 415, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1501,1378,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1501,1355,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1501, 192, '2020-10-09 11:26:14', 49880, 365, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(763,1372,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(763,1173,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(763,265,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(763, 96, '2020-09-07 18:27:39', 91880, 191, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1298,1493,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1298,1724,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1298, 165, '2020-09-27 08:26:31', 86760, 318, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3450,662,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3450, 969, '2020-10-14 06:28:27', 389700, 1917, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1831,89,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1831,2238,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1831, 308, '2020-09-10 23:38:55', 58540, 601, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3214,2330,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3214,2426,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3214,288,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3214, 864, '2020-10-01 23:24:48', 43000, 1696, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3493,503,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3493, 988, '2020-09-08 05:55:22', 148500, 1957, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(312,1340,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(312,525,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(312, 40, '2020-09-15 12:08:36', 51500, 80, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(118,774,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(118,591,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(118,2092,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(118, 16, '2020-10-01 16:15:21', 89540, 29, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2828,612,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2828,1781,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2828, 710, '2020-10-08 17:32:05', 39880, 1387, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3402,1167,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3402,1,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3402, 945, '2020-11-02 21:44:48', 38940, 1865, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(469,801,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(469, 59, '2020-10-23 15:32:55', 39600, 120, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3413,1636,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3413,712,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3413, 950, '2020-09-14 06:03:38', 66000, 1874, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2575,1541,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2575,224,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2575, 604, '2020-10-23 22:45:52', 101100, 1167, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3311,1814,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3311,1820,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3311,1845,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3311, 905, '2020-10-16 03:54:07', 78060, 1783, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1481,570,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1481,834,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1481, 190, '2020-09-08 05:48:32', 39580, 360, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(379,638,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(379,1631,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(379,197,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(379, 48, '2020-10-14 01:29:28', 121720, 97, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2868,1689,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2868,1583,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2868,1286,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2868,1412,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2868,2085,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2868, 727, '2020-09-09 08:22:55', 110080, 1421, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1461,1397,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1461,1280,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1461,952,1);

INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1461, 187, '2020-10-06 20:33:51', 35600, 356, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1113,1769,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1113,1476,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1113,2228,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1113, 143, '2020-10-21 09:13:18', 62810, 279, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(102,422,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(102, 13, '2020-10-31 13:22:53', 47920, 23, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3028,56,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3028,1262,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3028, 792, '2020-09-20 18:13:25', 37920, 1552, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2757,1268,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2757,3,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2757,845,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2757, 682, '2020-10-16 14:59:48', 60260, 1335, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(993,1513,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(993,1654,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(993,587,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(993,175,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(993, 128, '2020-10-01 12:54:48', 49580, 245, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3235,120,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3235,51,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3235, 874, '2020-09-22 07:20:53', 154680, 1715, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(257,1478,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(257,2109,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(257, 33, '2020-10-19 17:41:45', 79960, 70, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3255,2318,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3255,92,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3255, 882, '2020-10-26 01:11:27', 51700, 1735, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1971,608,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1971,1034,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1971,1934,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1971,1677,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1971, 364, '2020-09-16 18:12:11', 65600, 712, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2019,436,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2019, 381, '2020-09-14 02:50:40', 59600, 745, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2016,679,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2016,1745,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2016, 380, '2020-09-14 15:48:13', 77000, 744, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2461,1359,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2461,1695,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2461,2030,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2461, 557, '2020-09-18 18:32:35', 63060, 1081, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2896,1232,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2896,1883,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2896,522,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2896, 738, '2020-10-01 12:06:53', 76280, 1440, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1806,418,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1806,165,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1806, 297, '2020-09-09 07:21:30', 36740, 581, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3212,1865,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3212,354,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3212,1955,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3212,2052,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3212,232,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3212, 863, '2020-10-01 11:43:24', 222220, 1695, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3470,1385,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3470,1604,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3470,357,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3470,1056,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3470, 977, '2020-10-08 20:41:11', 71900, 1928, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(424,1961,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(424, 53, '2020-10-07 21:09:55', 31200, 107, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1218,1800,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1218,197,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1218, 157, '2020-10-20 19:41:50', 151800, 302, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1329,9,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1329, 170, '2020-10-31 01:49:56', 39600, 325, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2130,1471,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2130,1617,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2130, 431, '2020-09-12 00:17:29', 49720, 843, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1689,1021,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1689,895,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1689,482,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1689, 255, '2020-10-17 14:47:57', 476680, 494, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1596,1663,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1596, 216, '2020-09-29 11:49:11', 52900, 412, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3068,871,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3068,2082,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3068,994,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3068,1289,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3068,1194,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3068, 808, '2020-09-14 19:08:20', 62140, 1585, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2344,402,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2344,1954,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2344,1815,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2344,1945,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2344,1320,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2344,1617,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2344, 513, '2020-10-10 13:42:30', 59580, 997, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(861,963,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(861,604,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(861,1354,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(861,601,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(861,1884,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(861, 110, '2020-09-18 07:37:33', 101360, 213, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3324,603,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3324,2071,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3324, 912, '2020-10-23 17:01:15', 61280, 1796, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(220,310,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(220,413,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(220,1594,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(220,108,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(220, 29, '2020-10-01 03:36:47', 61800, 63, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3194,149,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3194,718,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3194, 856, '2020-10-14 13:01:17', 43760, 1681, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(860,235,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(860,1711,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(860, 109, '2020-09-24 09:23:49', 86300, 210, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1114,1153,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1114, 143, '2020-10-08 04:12:43', 42400, 280, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(652,306,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(652,1666,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(652, 81, '2020-09-24 03:17:34', 83400, 161, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2643,187,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2643,2247,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2643,895,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2643, 632, '2020-10-12 07:54:13', 67850, 1222, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(267,2160,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(267,1296,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(267,574,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(267,213,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(267, 35, '2020-10-13 16:58:00', 48180, 72, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1569,1257,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1569,648,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1569, 204, '2020-10-31 14:34:12', 39840, 391, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2786,1655,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2786, 694, '2020-10-09 19:40:11', 51200, 1355, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(623,292,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(623, 78, '2020-09-17 08:12:02', 55200, 154, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(515,570,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(515,122,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(515,1999,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(515, 63, '2020-09-24 20:27:13', 58540, 126, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(756,581,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(756,491,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(756,672,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(756,2042,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(756, 95, '2020-10-20 11:08:56', 79810, 187, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3381,866,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3381,2101,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3381,2058,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3381,484,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3381, 939, '2020-09-15 17:15:27', 83140, 1853, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3062,693,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3062, 805, '2020-10-10 17:19:31', 41400, 1580, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1344,1793,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1344,381,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1344,2096,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1344,1862,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1344, 171, '2020-09-24 15:24:43', 37240, 328, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1553,277,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1553,2214,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1553,1981,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1553,1874,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1553,2244,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1553,1397,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1553, 199, '2020-10-11 13:55:43', 70400, 381, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2109,311,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2109,251,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2109, 422, '2020-09-29 10:25:09', 86200, 827, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1529,143,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1529, 196, '2020-09-16 14:06:25', 239700, 373, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2002,1284,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2002,1398,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2002, 376, '2020-09-20 04:24:41', 67380, 736, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(939,2329,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(939,1692,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(939, 121, '2020-10-23 02:23:50', 78140, 234, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(278,1494,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(278,794,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(278,2059,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(278, 36, '2020-10-31 08:16:23', 40880, 74, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1027,399,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1027,1769,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1027,1959,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1027,906,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1027,1995,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1027, 132, '2020-10-07 01:38:50', 59500, 258, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1330,586,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1330,1334,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1330,1989,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1330,1098,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1330, 170, '2020-11-07 03:40:31', 34100, 325, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1572,601,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1572,1316,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1572,98,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1572, 205, '2020-10-22 13:03:51', 102640, 392, 2, '14:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(874,2000,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(874,2057,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(874,1329,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(874, 112, '2020-10-28 00:36:25', 51680, 218, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3258,1309,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3258,2195,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3258, 882, '2020-10-05 16:45:54', 43980, 1735, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1636,1993,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1636,2116,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1636,2370,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1636,521,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1636, 233, '2020-10-26 06:35:36', 125060, 455, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2819,1676,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2819,1089,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2819, 707, '2020-09-17 03:10:54', 53530, 1381, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(104,1405,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(104,1609,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(104,3,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(104,857,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(104,1706,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(104, 13, '2020-10-16 02:12:51', 56700, 23, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(101,1997,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(101,2258,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(101,497,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(101, 13, '2020-09-13 22:07:06', 63500, 23, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2904,193,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2904, 741, '2020-09-26 02:31:11', 119700, 1446, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3094,2058,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3094,600,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3094,1164,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3094,1941,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3094, 817, '2020-09-17 13:55:13', 58276, 1599, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2349,1504,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2349,338,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2349,107,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2349,2249,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2349, 516, '2020-09-14 14:42:56', 49780, 1003, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(148,2083,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(148,1666,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(148,2018,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(148,1533,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(148,998,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(148,806,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(148, 20, '2020-11-01 06:04:36', 40160, 40, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3051,414,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3051,27,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3051, 802, '2020-09-30 21:53:41', 66560, 1573, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1132,1213,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1132,727,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1132,1339,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1132,269,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1132, 147, '2020-10-01 22:25:44', 75460, 284, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(296,978,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(296,1509,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(296,87,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(296, 38, '2020-10-08 05:03:16', 54340, 78, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1640,1674,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1640, 235, '2020-09-27 02:05:05', 36900, 457, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3321,938,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3321,719,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3321,1951,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3321,1740,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3321,2053,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3321, 911, '2020-09-24 07:41:49', 35800, 1795, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3057,792,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3057,1928,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3057,2243,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3057,82,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3057,760,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3057,603,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3057, 803, '2020-09-24 02:18:43', 54490, 1576, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(139,591,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(139,1187,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(139,571,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(139,214,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(139, 19, '2020-11-07 06:22:13', 55720, 38, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(962,1579,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(962,2032,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(962,1125,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(962, 123, '2020-11-02 01:29:48', 57820, 236, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(250,2320,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(250, 32, '2020-10-28 12:07:15', 51200, 67, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(253,1596,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(253, 33, '2020-09-18 03:36:26', 41400, 70, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3494,1795,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3494,782,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3494,1104,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3494, 988, '2020-09-22 15:55:33', 39720, 1955, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(966,700,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(966,1343,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(966,2143,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(966, 124, '2020-09-26 13:55:27', 58800, 237, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2885,608,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2885,575,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2885,1423,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2885,1515,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2885, 733, '2020-10-10 20:44:40', 41060, 1431, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2849,2206,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2849,1374,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2849,95,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2849, 719, '2020-10-08 19:21:39', 49840, 1401, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3414,515,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3414, 950, '2020-09-30 11:48:56', 88920, 1874, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1545,189,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1545,927,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1545, 198, '2020-09-14 20:31:40', 87720, 379, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1920,1508,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1920,392,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1920,1732,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1920,1952,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1920,392,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1920,418,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1920, 345, '2020-09-24 08:05:21', 73860, 674, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(238,1845,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(238, 31, '2020-10-16 08:15:20', 44640, 66, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(274,2182,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(274,2416,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(274,344,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(274, 35, '2020-09-08 12:57:41', 80440, 72, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(669,148,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(669,1104,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(669,1446,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(669,2002,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(669, 83, '2020-10-01 08:55:46', 40600, 166, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1388,2101,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1388,919,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1388,313,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1388, 177, '2020-10-04 19:03:52', 56820, 340, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2478,161,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2478, 565, '2020-10-07 11:33:23', 85000, 1099, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2650,2039,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2650,1627,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2650, 636, '2020-09-12 02:52:58', 64720, 1233, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2225,1047,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2225,2373,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2225,618,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2225, 464, '2020-10-13 15:50:11', 67880, 904, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2928,1367,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2928,2209,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2928,435,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2928,14,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2928, 750, '2020-10-21 14:16:38', 59920, 1461, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1209,183,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1209,1005,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1209,1795,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1209,1971,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1209,147,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1209, 156, '2020-10-13 11:08:54', 231280, 301, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2618,1704,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2618,1998,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2618,517,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2618,2275,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2618, 622, '2020-10-09 18:42:36', 44760, 1205, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2128,213,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2128,1080,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2128,1915,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2128, 431, '2020-10-29 16:07:52', 33860, 843, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1534,1340,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1534,933,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1534, 196, '2020-10-06 21:54:42', 55600, 373, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3279,385,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3279, 890, '2020-10-10 04:16:15', 55200, 1751, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3505,2325,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3505,2276,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3505, 992, '2020-11-02 07:26:25', 128000, 1963, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1168,2235,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1168,773,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1168,906,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1168, 152, '2020-10-20 08:06:04', 55760, 294, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1696,620,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1696,1264,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1696,1967,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1696, 258, '2020-11-01 14:37:37', 44200, 499, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2936,492,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2936,634,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2936, 754, '2020-09-17 02:46:20', 37400, 1469, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3309,2312,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3309,1180,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3309, 903, '2020-10-10 07:32:09', 65880, 1778, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3285,1379,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3285, 892, '2020-09-26 09:58:15', 43920, 1755, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1072,350,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1072,1360,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1072, 138, '2020-10-02 18:43:03', 43880, 270, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(997,263,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(997, 128, '2020-11-02 16:11:30', 51600, 246, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2403,1538,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2403,594,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2403,2177,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2403, 538, '2020-10-24 08:59:38', 37800, 1039, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2185,1107,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2185,235,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2185, 449, '2020-09-29 10:29:11', 66000, 879, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1566,80,3);

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(460,1094,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(460,1486,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(460,2411,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(460,1138,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(460,1542,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(460, 58, '2020-10-13 02:52:45', 95270, 117, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1040,683,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1040, 134, '2020-09-17 18:33:23', 476000, 262, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1719,1455,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1719,1285,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1719,1167,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1719,892,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1719, 265, '2020-10-23 17:49:49', 31860, 511, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(120,1253,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(120,537,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(120, 16, '2020-09-18 20:08:42', 33740, 29, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(248,1887,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(248,1642,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(248,1412,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(248, 32, '2020-10-27 02:13:39', 45800, 69, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3220,2170,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3220,1229,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3220,2191,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3220,83,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3220,1256,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3220, 866, '2020-10-25 19:37:39', 64400, 1700, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(666,2283,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(666,171,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(666,1809,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(666,1967,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(666, 82, '2020-09-25 04:53:21', 57640, 165, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(746,2033,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(746,2330,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(746,1062,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(746,1062,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(746, 94, '2020-10-10 10:22:28', 60080, 184, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1952,1784,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1952,1925,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1952,1666,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1952, 356, '2020-09-21 22:59:19', 45000, 694, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(819,960,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(819,918,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(819,1731,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(819, 104, '2020-09-12 09:27:39', 65500, 203, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1024,2368,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1024,1471,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1024,1168,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1024,1655,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1024, 131, '2020-10-09 18:38:02', 80260, 255, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3076,2036,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3076,157,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3076,1944,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3076,2214,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3076,1524,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3076, 810, '2020-09-13 10:53:21', 34340, 1587, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(392,2139,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(392,2137,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(392,555,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(392,1830,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(392, 49, '2020-11-05 18:56:48', 54660, 99, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(206,589,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(206,2287,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(206,1570,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(206,2098,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(206, 27, '2020-10-04 02:13:32', 42330, 57, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1709,1855,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1709,2032,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1709,2254,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1709, 262, '2020-09-07 18:49:08', 43080, 506, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(350,127,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(350,2170,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(350,446,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(350, 44, '2020-09-30 07:47:27', 151460, 89, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1045,1945,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1045,2013,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1045,453,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1045, 134, '2020-10-07 01:19:30', 75620, 260, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1403,1366,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1403,2072,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1403,792,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1403,1559,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1403, 179, '2020-10-13 09:24:43', 54200, 344, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3385,2273,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3385,2267,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3385,61,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3385,2177,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3385, 940, '2020-10-02 18:48:54', 39280, 1855, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3283,1670,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3283, 892, '2020-09-24 21:05:13', 164700, 1755, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1853,1007,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1853,647,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1853,2315,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1853,2203,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1853,724,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1853, 317, '2020-11-04 23:08:51', 59668, 620, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2995,811,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2995, 779, '2020-10-20 13:49:38', 47400, 1524, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1405,448,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1405, 179, '2020-09-20 00:14:41', 93800, 345, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(948,2214,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(948,179,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(948, 122, '2020-09-21 22:02:04', 41740, 235, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2915,1918,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2915,1365,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2915,2279,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2915,2138,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2915,186,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2915, 745, '2020-10-08 02:19:13', 72560, 1450, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1354,801,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1354,2187,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1354,275,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1354,986,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1354,2273,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1354,795,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1354, 172, '2020-10-28 05:34:25', 49890, 331, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2199,13,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2199,1191,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2199, 453, '2020-10-12 22:35:45', 42400, 886, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(568,2318,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(568, 71, '2020-11-04 07:05:23', 86400, 139, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1594,710,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1594,950,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1594, 215, '2020-10-29 16:29:36', 43860, 411, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(862,1462,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(862,381,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(862,2023,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(862,2003,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(862, 110, '2020-10-27 13:44:27', 48630, 212, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2457,145,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2457, 555, '2020-09-28 12:17:55', 59700, 1078, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1619,2037,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1619,1447,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1619,1367,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1619,403,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1619, 225, '2020-10-07 15:25:36', 73020, 436, 2, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2326,1270,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2326,2206,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2326,2185,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2326, 505, '2020-10-08 17:56:53', 53820, 987, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3012,2215,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3012,1559,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3012,1775,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3012,2151,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3012, 784, '2020-10-18 17:23:50', 63360, 1536, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3059,427,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3059, 804, '2020-09-15 08:28:53', 159600, 1578, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2567,1344,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2567,2003,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2567,428,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2567, 600, '2020-10-17 21:57:18', 38900, 1160, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2036,2301,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2036,2020,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2036,1147,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2036,1496,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2036, 390, '2020-09-30 03:07:05', 51940, 768, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1720,2176,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1720,2122,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1720,1243,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1720, 265, '2020-11-02 01:09:15', 43240, 511, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1635,2156,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1635,924,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1635,390,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1635, 233, '2020-09-19 13:22:05', 234899, 455, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1128,2291,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1128,969,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1128,1629,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1128, 146, '2020-10-02 07:50:00', 65260, 283, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3339,744,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3339,2257,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3339,1465,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3339,2237,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3339,1385,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3339, 918, '2020-11-01 17:32:53', 57720, 1809, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(11,1859,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(11,77,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(11,1370,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(11,1323,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(11, 2, '2020-09-18 00:31:57', 81620, 3, 3, '17:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(272,1511,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(272,1740,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(272,659,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(272,1989,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(272, 35, '2020-09-20 19:08:11', 53900, 73, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(247,1619,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(247, 32, '2020-10-27 12:36:06', 67200, 69, 3, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1194,35,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1194,2273,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1194,2079,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1194,1787,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1194,136,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1194, 154, '2020-09-09 03:36:41', 263110, 296, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2620,1858,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2620,1190,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2620,2106,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2620,1261,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2620, 623, '2020-10-24 20:54:35', 51120, 1206, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1667,2328,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1667,2397,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1667,508,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1667, 246, '2020-10-20 03:18:07', 59420, 477, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(908,646,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(908,1684,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(908, 117, '2020-10-02 15:17:25', 60180, 226, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1737,613,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1737,1200,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1737, 270, '2020-10-08 16:22:35', 40170, 523, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1219,1670,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1219, 157, '2020-10-04 21:54:18', 219600, 302, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1119,2115,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1119,429,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1119, 144, '2020-09-27 18:42:44', 49650, 281, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2984,1586,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2984,1998,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2984,886,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2984, 772, '2020-10-05 05:23:04', 379660, 1508, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(338,2248,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(338,619,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(338, 43, '2020-10-16 06:31:17', 49170, 87, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3198,508,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3198, 857, '2020-09-15 00:40:03', 49900, 1683, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2856,1196,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2856,1436,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2856,1830,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2856, 723, '2020-09-09 04:26:25', 43040, 1415, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(900,2093,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(900,1521,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(900,364,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(900, 116, '2020-09-19 00:21:34', 71940, 225, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(530,468,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(530,272,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(530, 66, '2020-10-18 21:57:42', 42400, 133, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1241,666,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1241, 159, '2020-09-16 01:27:15', 129600, 304, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3434,1181,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3434,1259,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3434,747,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3434, 962, '2020-10-28 16:48:04', 55220, 1900, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2298,1943,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2298,2158,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2298, 493, '2020-09-21 13:17:07', 39780, 963, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2753,1386,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2753,1185,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2753, 679, '2020-11-04 22:07:37', 39040, 1325, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1871,1072,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1871,942,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1871,565,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1871,2159,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1871,1880,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1871, 324, '2020-09-23 02:27:37', 103980, 632, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2521,2211,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2521,1109,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2521,1543,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2521, 582, '2020-10-26 14:56:36', 65800, 1132, 1, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(365,1327,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(365,1973,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(365,545,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(365, 46, '2020-10-21 11:39:40', 76960, 93, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2292,2076,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2292,1106,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2292,1769,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2292,736,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2292,1656,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2292, 490, '2020-09-30 20:55:44', 54020, 958, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1801,1815,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1801,651,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1801,415,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1801, 296, '2020-10-04 00:52:14', 124380, 580, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2285,2236,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2285,785,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2285,1588,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2285, 488, '2020-10-09 10:38:59', 80320, 953, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1962,1767,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1962,1984,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1962,828,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1962,2184,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1962, 359, '2020-11-07 00:28:44', 40020, 700, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2230,63,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2230,1779,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2230,1913,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2230, 465, '2020-10-19 02:06:12', 32720, 905, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2686,2254,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2686,181,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2686, 653, '2020-09-13 00:37:14', 66000, 1268, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2513,1288,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2513,701,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2513,1146,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2513,2183,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2513, 579, '2020-10-15 17:44:52', 40760, 1129, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1064,2321,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1064,36,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1064, 136, '2020-09-30 18:56:08', 36440, 266, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(583,408,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(583, 73, '2020-09-08 12:47:53', 91200, 142, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(54,284,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(54, 7, '2020-10-14 01:41:26', 115000, 11, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1900,1086,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1900,1105,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1900,1610,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1900,1489,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1900, 334, '2020-10-26 14:37:36', 85540, 650, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(99,326,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(99, 12, '2020-10-31 09:18:38', 178000, 22, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2437,987,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2437,1754,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2437, 549, '2020-10-04 01:32:26', 44080, 1065, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2099,1361,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2099,1114,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2099,1084,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2099,1829,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2099,1381,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2099,916,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2099, 419, '2020-10-04 23:05:56', 51484, 824, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2470,2021,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2470,2,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2470,1463,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2470, 561, '2020-10-02 07:14:21', 39820, 1090, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(779,444,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(779,1732,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(779,1715,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(779, 98, '2020-09-22 18:04:07', 68940, 195, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(328,904,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(328,640,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(328,2024,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(328,1752,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(328, 42, '2020-10-11 15:35:32', 54520, 86, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2729,1287,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2729,307,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2729, 669, '2020-09-09 05:28:02', 158680, 1303, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2359,2291,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2359,1647,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2359, 521, '2020-09-29 00:17:42', 289580, 1010, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2233,27,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2233,1974,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2233,274,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2233, 466, '2020-09-15 02:47:23', 65480, 906, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1416,606,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1416,2338,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1416,1386,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1416, 181, '2020-09-24 07:20:26', 44400, 347, 2, '14:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2453,1711,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2453, 554, '2020-09-19 18:55:57', 39600, 1075, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1142,926,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1142,798,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1142,2353,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1142, 147, '2020-09-28 10:16:12', 70520, 286, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(748,97,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(748, 94, '2020-11-05 12:12:41', 199600, 184, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(600,698,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(600,883,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(600, 76, '2020-09-14 18:36:32', 37340, 149, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(176,1973,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(176,1473,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(176,1183,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(176,1369,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(176,1259,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(176,1495,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(176, 23, '2020-10-17 22:44:21', 74130, 46, 4, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3382,436,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3382, 939, '2020-09-08 07:54:13', 44700, 1853, 3, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(29,1746,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(29,1102,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(29, 5, '2020-10-20 12:19:49', 62740, 9, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1406,1619,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1406, 179, '2020-10-17 05:43:03', 67200, 344, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3411,1473,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3411,2072,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3411, 950, '2020-10-28 03:01:29', 47120, 1873, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2282,1405,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2282,1058,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2282,85,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2282,555,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2282, 487, '2020-10-23 09:29:27', 57900, 952, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1044,1066,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1044,671,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1044,1958,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1044,1320,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1044, 134, '2020-09-30 19:41:46', 52660, 260, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(527,1974,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(527,356,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(527, 65, '2020-09-16 10:43:24', 98220, 128, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2577,1383,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2577,2150,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2577,1182,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2577,1226,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2577, 604, '2020-10-09 06:47:35', 136020, 1168, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1593,686,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1593,1050,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1593,745,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1593,1868,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1593,351,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1593, 214, '2020-10-26 12:58:34', 93500, 408, 5, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(317,1925,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(317,81,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(317,1223,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(317, 41, '2020-10-02 13:26:58', 57920, 82, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1752,156,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1752, 274, '2020-10-27 11:24:27', 155700, 534, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1477,181,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1477, 189, '2020-10-11 04:46:38', 67200, 359, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(594,1774,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(594,897,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(594, 75, '2020-09-10 00:25:20', 95580, 148, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3084,2298,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3084,160,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3084, 814, '2020-09-28 03:17:27', 57740, 1593, 1, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2289,1670,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2289, 490, '2020-11-03 07:44:54', 109800, 958, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3390,2285,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3390,2417,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3390,1523,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3390, 941, '2020-09-30 21:58:43', 46120, 1856, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(446,1651,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(446, 56, '2020-10-31 21:39:00', 39800, 115, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(507,418,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(507,1938,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(507,2044,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(507,2225,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(507, 62, '2020-11-05 01:57:00', 248040, 125, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(919,1422,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(919,107,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(919,1429,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(919, 118, '2020-11-04 02:54:42', 62200, 228, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2853,312,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2853,1861,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2853,874,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2853, 720, '2020-10-20 18:11:31', 160060, 1405, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(57,1823,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(57,1473,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(57,856,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(57, 8, '2020-11-04 21:49:38', 48740, 13, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1604,24,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1604,1806,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1604, 220, '2020-10-23 07:04:12', 63320, 424, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3009,1568,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3009, 783, '2020-11-06 01:22:57', 145040, 1532, 2, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2714,1340,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2714,1210,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2714,2278,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2714,653,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2714,431,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2714, 662, '2020-09-09 17:15:31', 41352, 1287, 1, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2371,977,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2371,176,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2371,2038,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2371,1851,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2371, 526, '2020-10-25 20:21:20', 38040, 1019, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2692,1721,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2692, 655, '2020-10-22 10:03:20', 46500, 1272, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2913,841,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2913,473,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2913, 744, '2020-10-10 16:51:53', 232835, 1449, 6, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3007,229,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3007, 783, '2020-09-23 17:55:47', 180000, 1533, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3203,1096,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3203,642,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3203,2367,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3203,2266,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3203, 859, '2020-10-10 06:37:24', 54740, 1685, 2, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(625,1657,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(625,1784,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(625,21,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(625,906,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(625,1162,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(625, 78, '2020-09-15 23:14:56', 49620, 154, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2944,1807,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2944,58,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2944,382,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2944, 757, '2020-10-11 12:35:26', 39860, 1475, 1, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1771,1432,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1771,1714,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1771,1492,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1771, 282, '2020-09-09 21:06:09', 55100, 550, 3, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2043,13,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2043,703,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2043,1164,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2043, 393, '2020-10-01 21:27:51', 89140, 773, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(740,1948,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(740,1322,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(740,292,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(740, 93, '2020-10-19 22:46:08', 51800, 182, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(330,66,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(330,1274,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(330, 42, '2020-10-29 04:34:26', 59880, 86, 4, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1835,338,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1835, 310, '2020-10-20 04:40:45', 59200, 606, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(87,1651,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(87, 10, '2020-10-07 21:09:25', 59700, 18, 2, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2838,1713,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2838,1782,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2838,100,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2838,1117,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2838, 715, '2020-10-13 21:21:22', 66770, 1395, 5, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(569,504,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(569, 71, '2020-11-04 04:00:01', 142500, 139, 2, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1918,1950,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1918,933,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1918, 344, '2020-09-16 23:48:22', 38364, 672, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(146,1787,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(146,1782,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(146,601,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(146,2079,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(146,1107,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(146,2393,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(146, 20, '2020-09-10 08:25:14', 56340, 40, 5, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1178,2383,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1178,62,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1178, 152, '2020-11-02 11:54:59', 80240, 294, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1000,596,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1000,1008,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1000,1057,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1000, 128, '2020-10-30 20:28:33', 97120, 245, 1, '14:00');

INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1300,1285,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1300,217,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1300,1314,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1300,1842,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1300,69,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1300, 165, '2020-10-02 05:31:52', 116040, 318, 3, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2405,1632,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2405,1457,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2405, 539, '2020-09-21 09:51:10', 57840, 1041, 6, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(646,2176,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(646,1028,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(646,2248,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(646, 81, '2020-10-28 19:35:11', 42820, 162, 6, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3122,1913,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3122,573,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3122,1978,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3122,2388,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3122,1019,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3122,1310,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3122, 826, '2020-09-16 17:25:33', 45830, 1621, 1, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1016,274,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1016,2345,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1016,66,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1016, 130, '2020-10-05 22:14:47', 54820, 251, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(401,118,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(401,1417,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(401,724,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(401,2201,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(401,1953,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(401,1736,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(401, 50, '2020-10-20 16:12:39', 56890, 100, 2, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1453,262,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1453,1414,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1453,1477,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1453,1315,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1453,2112,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1453,616,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1453,91,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1453, 186, '2020-10-06 00:54:16', 124070, 355, 3, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3247,806,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3247,1183,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3247, 879, '2020-10-20 23:06:00', 35360, 1728, 5, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1852,1874,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1852,1459,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1852,1553,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1852,1217,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1852, 317, '2020-10-24 22:43:40', 62810, 619, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(302,78,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(302,2138,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(302,561,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(302,573,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(302,762,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(302,1315,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(302, 39, '2020-09-15 16:39:47', 49440, 79, 5, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(844,184,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(844, 108, '2020-10-27 09:16:41', 64800, 208, 3, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(827,1446,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(827,1586,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(827, 105, '2020-10-04 16:09:34', 53880, 204, 1, '17:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3429,1882,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3429,1136,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3429,1998,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3429,549,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3429,1325,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3429, 958, '2020-10-06 06:12:29', 48580, 1893, 6, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1264,982,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1264,1572,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1264, 162, '2020-09-12 14:44:52', 64540, 311, 5, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2146,1787,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2146,876,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2146,931,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2146, 437, '2020-10-12 05:20:44', 72520, 852, 4, '23:59');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1984,985,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1984,1490,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1984,919,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1984,2001,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(1984,1171,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(1984, 371, '2020-10-19 05:02:56', 45100, 726, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(612,1380,2);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(612,912,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(612,850,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(612,206,2);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(612, 77, '2020-10-04 09:30:22', 194480, 152, 4, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3369,687,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3369,925,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3369, 933, '2020-09-29 06:41:55', 68820, 1841, 6, '14:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2530,735,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2530,1464,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2530,343,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2530, 584, '2020-10-10 18:36:52', 73700, 1135, 6, '10:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2588,690,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2588,171,4);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2588,351,1);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2588,146,1);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2588, 609, '2020-09-22 11:35:27', 42620, 1177, 4, '18:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3477,334,3);
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(3477,343,3);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(3477, 980, '2020-09-30 18:26:09', 77100, 1935, 4, '11:00');
INSERT INTO carts(orders_id, products_id, products_quantity) VALUES(2929,1734,4);
INSERT INTO orders(id, users_seq, time, total_price, credit_cards_seq, delivery_day, delivery_time) VALUES(2929, 750, '2020-10-23 17:49:48', 67600, 1461, 4, '18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(34,1787,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(34,462,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(34,597,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(34,744,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(34,2199,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(34,1986,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(34,142,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(34,5,'2020-09-27 05:37:42',620480,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2443,47,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2443,1856,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2443,1863,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2443,1069,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2443,389,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2443,1020,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2443,551,'2020-10-31 14:20:42',164050,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2050,2016,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2050,1139,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2050,876,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2050,220,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2050,1951,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2050,1896,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2050,1604,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2050,1773,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2050,396,'2020-10-13 16:36:30',196900,1461,6,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3079,84,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3079,1189,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3079,1812,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3079,2378,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3079,1197,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3079,1203,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3079,812,'2020-09-13 14:28:04',231540,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(280,1585,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(280,981,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(280,611,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(280,1635,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(280,2214,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(280,604,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(280,728,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(280,1326,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(280,1228,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(280,36,'2020-09-08 23:31:14',224110,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2626,639,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2626,1311,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2626,2422,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2626,1028,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2626,1556,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2626,1885,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2626,625,'2020-09-09 15:47:21',208215,1461,1,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(690,298,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(690,85,'2020-10-31 09:12:20',91600,1461,1,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1844,1727,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1844,314,'2020-10-25 00:30:28',419400,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2471,263,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2471,1024,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2471,2006,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2471,562,'2020-11-04 12:52:08',124880,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3421,1433,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3421,575,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3421,1130,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3421,634,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3421,2221,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3421,1254,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3421,2314,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3421,923,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3421,2162,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3421,1891,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3421,953,'2020-10-18 19:44:25',143190,1461,1,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2415,672,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2415,958,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2415,1838,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2415,953,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2415,1662,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2415,2108,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2415,1863,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2415,301,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2415,2122,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2415,543,'2020-10-04 21:02:17',101270,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3491,911,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3491,1867,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3491,1289,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3491,234,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3491,370,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3491,987,'2020-11-03 00:30:16',90700,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(878,261,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(878,891,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(878,2301,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(878,1079,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(878,113,'2020-10-16 00:44:22',151140,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(688,1047,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(688,1791,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(688,1768,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(688,1434,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(688,590,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(688,764,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(688,2357,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(688,85,'2020-11-05 00:31:46',158520,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2679,721,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2679,649,'2020-10-14 01:46:33',39600,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1019,855,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1019,1327,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1019,889,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1019,1370,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1019,2174,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1019,131,'2020-10-03 21:42:01',223810,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2532,80,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2532,1734,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2532,585,'2020-10-13 06:09:57',123480,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1338,2272,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1338,1753,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1338,1887,6);

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3320,251,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3320,1710,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3320,707,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3320,910,'2020-09-17 03:42:23',136200,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2152,1335,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2152,403,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2152,1627,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2152,1146,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2152,1579,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2152,438,'2020-09-25 07:41:44',207600,1461,4,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2001,1726,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2001,864,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2001,1208,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2001,376,'2020-11-03 08:06:43',58080,1461,6,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(784,600,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(784,753,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(784,1934,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(784,1785,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(784,720,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(784,99,'2020-10-01 15:39:30',134610,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(692,309,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(692,2311,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(692,92,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(692,225,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(692,85,'2020-09-22 06:10:12',438080,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1507,2402,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1507,1466,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1507,1003,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1507,2407,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1507,1200,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1507,835,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1507,193,'2020-10-07 22:32:07',93110,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1735,2205,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1735,2289,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1735,1206,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1735,2177,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1735,1952,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1735,269,'2020-10-11 10:00:28',65000,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1634,572,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1634,386,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1634,233,'2020-09-13 16:24:23',31240,1461,6,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2369,2167,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2369,1222,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2369,2307,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2369,1521,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2369,525,'2020-09-26 04:30:28',79180,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2973,302,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2973,2050,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2973,176,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2973,1509,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2973,1426,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2973,766,'2020-10-05 03:12:09',124992,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2023,201,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2023,384,'2020-10-26 06:20:17',319600,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(995,801,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(995,1439,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(995,637,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(995,1278,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(995,456,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(995,128,'2020-10-28 02:28:20',250560,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(804,2337,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(804,102,'2020-10-16 05:16:12',89500,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2104,2363,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2104,1617,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2104,1388,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2104,2179,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2104,692,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2104,1354,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2104,420,'2020-10-02 14:40:54',156768,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(888,2124,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(888,1963,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(888,1471,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(888,1267,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(888,346,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(888,2,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(888,239,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(888,2241,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(888,114,'2020-10-11 14:02:17',135940,1461,6,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3473,1580,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3473,58,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3473,251,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3473,978,'2020-10-08 19:41:49',124780,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1137,304,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1137,1038,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1137,644,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1137,2090,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1137,1144,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1137,624,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1137,147,'2020-09-28 12:41:43',211020,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1326,739,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1326,800,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1326,268,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1326,861,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1326,846,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1326,1165,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1326,834,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1326,169,'2020-09-08 04:03:42',168340,1461,2,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1743,227,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1743,575,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1743,714,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1743,1549,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1743,169,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1743,272,'2020-10-26 11:41:41',271980,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1412,1812,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1412,22,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1412,180,'2020-09-09 06:53:26',44960,1461,1,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2246,426,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2246,1538,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2246,2275,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2246,2282,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2246,295,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2246,920,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2246,1764,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2246,1727,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2246,471,'2020-11-04 17:52:10',563990,1461,2,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2802,1140,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2802,700,'2020-10-21 06:55:17',84960,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1581,178,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1581,865,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1581,209,'2020-09-16 03:34:58',227000,1461,2,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(175,1737,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(175,1361,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(175,2243,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(175,22,'2020-10-08 05:09:42',137504,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1791,1564,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1791,2347,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1791,2322,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1791,1136,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1791,291,'2020-11-03 20:11:00',230280,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2280,21,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2280,487,'2020-10-07 08:51:43',99000,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2500,795,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2500,359,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2500,1160,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2500,725,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2500,2285,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2500,1319,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2500,177,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2500,574,'2020-10-19 12:04:56',369020,1461,4,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(704,2036,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(704,1460,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(704,1154,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(704,87,'2020-09-18 02:50:36',96080,1461,4,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2217,782,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2217,2156,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2217,586,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2217,1823,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2217,1565,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2217,460,'2020-09-20 05:49:00',250108,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2860,1564,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2860,1455,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2860,393,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2860,990,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2860,1376,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2860,2092,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2860,1839,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2860,1954,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2860,725,'2020-11-02 19:35:14',184390,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1328,2373,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1328,2129,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1328,667,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1328,169,'2020-09-19 12:11:51',731520,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1763,1394,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1763,2070,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1763,56,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1763,1048,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1763,1736,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1763,1735,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1763,278,'2020-10-11 00:25:08',177690,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1957,2065,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1957,1001,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1957,67,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1957,30,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1957,358,'2020-09-18 07:11:00',183320,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3148,1486,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3148,1103,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3148,854,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3148,502,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3148,838,'2020-09-24 13:02:19',255940,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3138,932,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3138,834,'2020-09-20 01:15:19',59400,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2394,2334,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2394,1578,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2394,98,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2394,534,'2020-11-06 03:51:04',103720,1461,1,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2030,2123,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2030,387,'2020-11-03 04:11:48',38500,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(354,1693,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(354,1824,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(354,1125,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(354,972,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(354,146,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(354,1724,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(354,45,'2020-09-26 01:28:47',148220,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1361,1647,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1361,173,'2020-10-31 10:47:11',139800,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3132,726,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3132,2022,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3132,907,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3132,1812,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3132,2400,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3132,223,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3132,833,'2020-09-25 19:37:12',230440,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(196,502,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(196,26,'2020-10-22 03:21:26',119600,1461,6,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(244,1672,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(244,32,'2020-10-24 20:11:51',149400,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3098,918,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3098,2224,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3098,1127,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3098,2238,3);

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1836,1492,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1836,798,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1836,670,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1836,311,'2020-10-08 07:39:00',141600,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(449,1758,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(449,56,'2020-11-03 18:06:57',155600,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1904,976,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1904,930,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1904,336,'2020-10-07 05:33:39',82680,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1135,1072,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1135,1414,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1135,578,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1135,938,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1135,235,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1135,147,'2020-10-11 19:00:27',227300,1461,2,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(19,1557,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(19,678,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(19,560,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(19,51,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(19,3,'2020-10-11 20:45:46',293320,1461,4,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1294,2318,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1294,164,'2020-11-02 09:19:41',172800,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(442,981,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(442,55,'2020-10-29 11:21:02',26820,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(561,1144,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(561,796,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(561,2400,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(561,749,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(561,1373,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(561,2226,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(561,2294,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(561,2399,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(561,69,'2020-09-26 10:50:23',137520,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2661,1452,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2661,1212,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2661,1875,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2661,85,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2661,1524,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2661,1267,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2661,1150,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2661,36,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2661,404,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2661,639,'2020-10-13 20:12:07',165440,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(344,125,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(344,44,'2020-10-12 16:27:52',53700,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2722,2177,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2722,2364,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2722,665,'2020-09-19 20:29:21',100740,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1508,2115,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1508,2228,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1508,2080,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1508,567,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1508,1226,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1508,193,'2020-10-05 08:18:12',205140,1461,3,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3099,2117,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3099,1562,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3099,2057,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3099,913,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3099,195,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3099,1224,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3099,2031,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3099,2159,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3099,819,'2020-11-07 05:37:29',163110,1461,4,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(232,1702,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(232,638,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(232,2404,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(232,1273,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(232,244,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(232,31,'2020-10-04 10:08:23',254170,1461,4,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2051,415,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2051,397,'2020-09-25 23:51:21',104700,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3041,2232,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3041,763,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3041,2124,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3041,771,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3041,798,'2020-10-18 03:47:09',115360,1461,4,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(657,1296,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(657,1987,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(657,1258,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(657,808,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(657,82,'2020-11-04 17:32:31',109900,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2765,1349,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2765,681,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2765,1168,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2765,921,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2765,685,'2020-10-12 12:01:27',442720,1461,6,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1786,1448,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1786,966,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1786,833,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1786,1058,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1786,320,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1786,48,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1786,289,'2020-10-22 12:57:40',162200,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(613,482,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(613,77,'2020-10-22 01:12:31',580000,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1484,1331,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1484,2006,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1484,909,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1484,190,'2020-09-16 23:58:32',219560,1461,2,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1987,998,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1987,859,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1987,2005,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1987,1753,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1987,365,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1987,1071,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1987,1995,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1987,1079,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1987,372,'2020-09-15 10:03:02',169800,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1378,2108,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1378,1287,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1378,2173,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1378,138,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1378,175,'2020-09-08 21:52:23',217380,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3,376,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3,1,'2020-10-19 03:37:41',44880,1461,6,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3501,1587,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3501,1257,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3501,2108,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3501,1853,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3501,797,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3501,991,'2020-10-20 04:48:32',116890,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3104,1333,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3104,1604,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3104,545,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3104,459,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3104,820,'2020-10-21 09:37:50',138960,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(429,1097,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(429,1805,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(429,419,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(429,1844,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(429,1344,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(429,2384,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(429,1148,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(429,1235,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(429,53,'2020-11-05 08:48:21',155450,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1205,1969,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1205,1575,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1205,2414,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1205,156,'2020-10-28 11:52:17',60000,1461,6,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1753,2220,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1753,623,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1753,1487,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1753,63,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1753,274,'2020-10-20 16:45:12',130810,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3294,1459,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3294,393,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3294,301,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3294,1287,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3294,2142,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3294,2279,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3294,1530,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3294,2055,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3294,2187,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3294,817,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3294,895,'2020-10-12 03:17:56',180780,1461,4,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(316,538,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(316,728,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(316,898,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(316,253,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(316,284,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(316,41,'2020-10-05 22:08:31',435920,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1825,540,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1825,1618,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1825,1319,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1825,1053,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1825,945,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1825,667,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1825,306,'2020-10-22 17:33:53',734350,1461,6,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3504,17,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3504,1724,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3504,1616,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3504,991,'2020-10-12 09:13:21',244704,1461,4,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(360,431,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(360,1031,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(360,483,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(360,46,'2020-09-10 12:55:41',617660,1461,1,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1213,2112,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1213,1627,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1213,1819,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1213,605,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1213,1756,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1213,1251,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1213,156,'2020-10-02 08:18:54',149705,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2085,1773,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2085,1539,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2085,750,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2085,650,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2085,412,'2020-09-22 22:26:18',120880,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2718,237,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2718,377,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2718,664,'2020-09-19 03:57:26',119320,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1800,191,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1800,2185,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1800,2158,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1800,1174,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1800,2220,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1800,619,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1800,335,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1800,295,'2020-09-12 08:20:57',212160,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(842,1151,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(842,2406,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(842,1337,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(842,1942,4);

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(842,1768,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(842,2384,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(842,2362,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(842,107,'2020-09-15 20:21:23',172820,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(42,321,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(42,816,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(42,38,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(42,2094,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(42,1388,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(42,976,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(42,2017,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(42,1315,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(42,1060,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(42,6,'2020-09-12 02:49:07',95480,1461,2,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(523,708,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(523,1664,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(523,65,'2020-10-05 02:29:14',184510,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1797,1617,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1797,5,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1797,2075,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1797,2188,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1797,791,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1797,206,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1797,293,'2020-10-13 18:58:22',286500,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3286,1064,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3286,1523,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3286,30,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3286,909,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3286,892,'2020-10-21 06:58:28',503880,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1915,1873,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1915,1343,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1915,2257,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1915,341,'2020-10-28 22:43:55',50180,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1041,283,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1041,2287,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1041,134,'2020-10-22 09:48:27',111620,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1692,66,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1692,1660,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1692,2322,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1692,1349,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1692,256,'2020-11-03 12:56:07',95580,1461,1,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3036,1335,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3036,910,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3036,253,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3036,795,'2020-10-08 10:33:23',177260,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(631,2096,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(631,2284,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(631,534,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(631,79,'2020-09-07 22:06:08',213480,1461,6,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1287,2212,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1287,1189,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1287,2180,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1287,1674,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1287,164,'2020-09-07 13:22:53',276780,1461,4,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1947,808,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1947,1337,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1947,991,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1947,354,'2020-09-27 08:22:06',57980,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1089,2333,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1089,555,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1089,1101,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1089,140,'2020-10-07 14:05:33',51780,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2115,767,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2115,122,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2115,1241,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2115,999,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2115,425,'2020-11-02 19:44:13',114200,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(641,1350,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(641,598,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(641,834,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(641,80,'2020-11-07 05:05:03',34180,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1847,1141,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1847,951,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1847,2090,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1847,159,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1847,1527,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1847,1901,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1847,1597,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1847,544,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1847,315,'2020-10-21 13:38:12',245280,1461,4,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(107,1518,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(107,1562,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(107,1170,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(107,1406,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(107,14,'2020-10-06 23:35:04',62480,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3365,1584,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3365,2263,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3365,332,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3365,931,'2020-11-01 04:29:45',107960,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2674,1671,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2674,647,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2674,953,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2674,248,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2674,646,'2020-10-14 00:48:07',188940,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2182,1188,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2182,1552,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2182,303,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2182,113,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2182,448,'2020-09-30 00:50:39',394780,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2132,2198,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2132,1494,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2132,1303,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2132,1587,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2132,1539,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2132,1473,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2132,1207,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2132,1175,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2132,256,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2132,432,'2020-11-04 23:33:33',276968,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2869,2261,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2869,1074,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2869,1450,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2869,727,'2020-10-08 15:22:48',84320,1461,4,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3097,2107,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3097,654,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3097,1400,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3097,204,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3097,818,'2020-10-16 04:30:01',236780,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2232,1871,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2232,1287,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2232,1365,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2232,522,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2232,214,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2232,465,'2020-10-12 07:19:14',193160,1461,4,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1302,1236,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1302,308,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1302,165,'2020-09-27 00:46:00',319320,1461,1,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(168,1567,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(168,21,'2020-10-25 14:42:52',310800,1461,1,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2277,1026,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2277,2004,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2277,557,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2277,844,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2277,1732,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2277,2379,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2277,1026,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2277,1762,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2277,486,'2020-09-30 12:37:00',301480,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1933,481,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1933,1837,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1933,2172,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1933,61,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1933,1995,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1933,1507,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1933,349,'2020-09-25 23:52:12',87720,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1190,2132,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1190,1116,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1190,1015,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1190,305,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1190,1634,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1190,154,'2020-10-26 07:51:23',160720,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1872,1218,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1872,1530,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1872,2012,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1872,2065,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1872,324,'2020-09-28 01:38:41',107040,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(608,2046,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(608,1532,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(608,2032,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(608,889,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(608,104,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(608,77,'2020-09-20 02:23:41',361720,1461,6,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(927,1170,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(927,2020,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(927,2357,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(927,120,'2020-09-13 23:52:51',101120,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2377,1058,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2377,1783,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2377,558,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2377,1036,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2377,528,'2020-10-03 01:49:10',196140,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3406,2096,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3406,1629,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3406,99,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3406,948,'2020-10-21 20:18:05',77700,1461,2,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1748,1588,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1748,1549,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1748,1009,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1748,1217,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1748,826,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1748,2007,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1748,273,'2020-10-06 08:48:15',210820,1461,5,'14:00');

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3287,409,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3287,1660,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3287,1556,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3287,1954,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3287,520,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3287,396,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3287,893,'2020-09-20 09:55:40',136350,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2096,1595,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2096,2430,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2096,1228,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2096,418,'2020-10-26 20:41:32',141060,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(528,1724,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(528,1083,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(528,685,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(528,760,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(528,624,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(528,66,'2020-10-23 08:53:54',241090,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2339,250,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2339,446,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2339,511,'2020-09-19 14:36:27',206740,1461,4,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1856,1785,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1856,1941,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1856,2194,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1856,1937,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1856,1289,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1856,2059,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1856,319,'2020-10-18 08:01:53',87892,1461,6,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3011,107,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3011,2207,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3011,10,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3011,788,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3011,606,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3011,168,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3011,784,'2020-10-14 05:12:08',296988,1461,4,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1189,512,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1189,1210,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1189,1576,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1189,153,'2020-10-22 21:37:53',92600,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(291,915,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(291,1453,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(291,111,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(291,1161,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(291,38,'2020-10-05 17:11:31',175460,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1046,812,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1046,353,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1046,2253,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1046,729,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1046,139,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1046,134,'2020-09-30 11:12:48',162800,1461,4,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(932,518,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(932,1033,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(932,307,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(932,120,'2020-09-11 20:47:49',277080,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1951,1003,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1951,1693,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1951,251,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1951,1322,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1951,598,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1951,356,'2020-10-24 16:46:11',190700,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(313,2268,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(313,2359,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(313,1353,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(313,1658,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(313,2108,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(313,1748,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(313,40,'2020-09-16 06:59:03',200080,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2946,2080,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2946,605,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2946,614,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2946,2115,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2946,1747,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2946,757,'2020-10-02 16:35:23',351510,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1469,289,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1469,188,'2020-09-14 18:09:47',137700,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1351,1593,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1351,1760,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1351,527,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1351,77,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1351,172,'2020-09-30 17:29:49',96160,1461,6,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2976,895,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2976,2050,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2976,1639,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2976,970,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2976,1899,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2976,768,'2020-10-13 22:16:46',192460,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(768,2084,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(768,2224,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(768,97,'2020-09-09 17:32:59',48500,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2715,474,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2715,14,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2715,46,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2715,966,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2715,663,'2020-10-20 14:14:02',186780,1461,6,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(497,98,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(497,1810,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(497,280,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(497,61,'2020-09-20 11:20:07',167560,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(790,2237,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(790,1359,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(790,100,'2020-10-14 23:15:54',47340,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3060,1183,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3060,1110,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3060,1710,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3060,804,'2020-09-12 10:17:39',117600,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,942,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,1343,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,396,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,563,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,951,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,2396,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,2412,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,368,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,988,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,387,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1165,185,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1165,151,'2020-09-18 08:01:54',354510,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1372,919,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1372,484,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1372,340,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1372,159,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1372,165,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1372,174,'2020-10-25 20:31:21',119860,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(571,613,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(571,1735,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(571,962,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(571,1972,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(571,71,'2020-10-23 09:03:13',75160,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2004,1773,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2004,1851,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2004,897,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2004,2087,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2004,377,'2020-10-19 04:09:18',107840,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1414,2375,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1414,1836,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1414,131,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1414,180,'2020-10-09 18:13:36',318800,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1206,316,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1206,1783,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1206,907,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1206,156,'2020-09-10 17:46:21',76240,1461,1,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(773,1045,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(773,2025,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(773,6,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(773,230,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(773,1385,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(773,1612,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(773,2214,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(773,1007,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(773,1955,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(773,894,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(773,97,'2020-11-04 13:03:53',182920,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3183,2014,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3183,2320,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3183,1799,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3183,1815,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3183,517,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3183,1788,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3183,1935,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3183,851,'2020-10-07 20:05:39',107270,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2695,1400,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2695,1109,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2695,1429,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2695,891,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2695,1194,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2695,655,'2020-09-19 05:30:50',120760,1461,2,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(650,1087,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(650,2071,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(650,81,'2020-09-08 18:56:46',114920,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1842,836,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1842,2096,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1842,314,'2020-11-05 09:35:15',76680,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3175,831,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3175,817,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3175,1269,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3175,2115,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3175,849,'2020-10-03 23:22:53',84150,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2832,353,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2832,2392,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2832,2141,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2832,942,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2832,1145,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2832,1067,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2832,213,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2832,434,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2832,1447,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2832,713,'2020-11-03 18:34:29',141560,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(239,2241,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(239,31,'2020-10-12 05:56:38',83400,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2663,760,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2663,2164,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2663,2283,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2663,258,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2663,641,'2020-10-04 05:17:15',101570,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2295,1514,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2295,1844,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2295,498,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2295,1266,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2295,1923,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2295,1535,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2295,127,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2295,491,'2020-10-01 14:05:46',183040,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(26,599,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(26,757,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(26,2353,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(26,2418,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(26,1886,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(26,4,'2020-09-16 16:40:55',111640,1461,6,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3185,204,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3185,853,'2020-10-31 20:29:15',144500,1461,6,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1671,2223,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1671,139,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1671,563,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1671,247,'2020-10-12 06:40:16',139300,1461,2,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(463,1332,2);

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2839,2052,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2839,890,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2839,2035,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2839,692,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2839,716,'2020-09-14 08:04:04',130200,1461,4,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1225,1540,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1225,709,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1225,1088,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1225,1308,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1225,399,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1225,157,'2020-10-23 15:41:43',225120,1461,6,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(205,1078,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(205,27,'2020-10-02 06:33:22',34720,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1772,1949,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1772,2262,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1772,552,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1772,1791,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1772,924,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1772,599,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1772,1621,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1772,283,'2020-10-31 06:38:39',230724,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(234,1229,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(234,1,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(234,2291,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(234,652,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(234,31,'2020-09-14 23:08:43',151180,1461,1,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,2052,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,733,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,771,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,990,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,2419,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,2391,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,2101,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,2369,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,1441,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,1076,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,2301,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1899,13,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1899,333,'2020-10-14 00:43:05',259340,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(787,1693,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(787,100,'2020-10-29 14:01:39',59400,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1707,950,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1707,2372,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1707,1555,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1707,766,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1707,117,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1707,608,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1707,2329,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1707,292,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1707,262,'2020-10-20 12:53:42',191880,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3496,1948,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3496,525,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3496,2380,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3496,1891,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3496,1860,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3496,736,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3496,83,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3496,989,'2020-09-16 05:02:43',198840,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1174,635,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1174,2015,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1174,2117,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1174,152,'2020-09-07 17:48:58',103700,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(973,2246,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(973,2316,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(973,1088,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(973,107,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(973,2401,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(973,740,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(973,125,'2020-10-07 13:38:27',181700,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1959,262,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1959,389,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1959,652,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1959,358,'2020-10-08 18:23:26',166680,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2959,1381,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2959,452,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2959,194,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2959,802,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2959,1319,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2959,762,'2020-10-09 18:27:58',163600,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3343,2033,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3343,508,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3343,920,'2020-10-08 00:25:18',153840,1461,1,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2546,1523,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2546,1375,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2546,128,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2546,593,'2020-10-16 17:11:19',265440,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(813,1126,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(813,190,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(813,1445,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(813,498,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(813,104,'2020-11-04 12:33:24',176300,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(111,468,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(111,1830,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(111,855,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(111,14,'2020-09-20 21:27:46',62480,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(273,696,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(273,935,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(273,2111,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(273,319,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(273,35,'2020-10-06 19:28:47',208160,1461,2,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(492,301,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(492,61,'2020-10-13 00:39:41',199080,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3518,1422,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3518,391,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3518,996,'2020-10-04 10:53:46',198720,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2187,1368,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2187,1194,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2187,1037,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2187,1391,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2187,1486,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2187,2162,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2187,112,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2187,450,'2020-11-05 16:28:45',412480,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1455,3,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1455,795,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1455,1705,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1455,622,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1455,26,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1455,813,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1455,186,'2020-10-01 17:57:26',147160,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(695,103,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(695,85,'2020-10-28 19:14:05',74500,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3120,1368,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3120,445,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3120,1004,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3120,593,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3120,1200,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3120,1453,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3120,743,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3120,826,'2020-10-21 18:32:36',169895,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3430,1588,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3430,1288,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3430,2354,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3430,959,'2020-09-18 08:55:16',108100,1461,1,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2669,739,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2669,642,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2669,1589,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2669,432,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2669,317,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2669,1411,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2669,2023,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2669,1005,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2669,2088,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2669,374,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2669,644,'2020-09-22 13:55:15',220160,1461,6,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3358,904,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3358,1789,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3358,1124,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3358,751,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3358,926,'2020-10-27 01:25:43',71960,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2559,31,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2559,68,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2559,596,'2020-10-11 23:59:37',301960,1461,2,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3391,476,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3391,493,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3391,543,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3391,1857,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3391,1297,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3391,1941,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3391,829,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3391,644,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3391,261,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3391,942,'2020-11-01 15:28:46',199672,1461,4,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(618,1287,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(618,423,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(618,1374,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(618,2006,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(618,78,'2020-10-01 11:40:06',83720,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2751,1618,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2751,2143,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2751,678,'2020-10-13 15:51:00',62380,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(969,872,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(969,1591,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(969,124,'2020-11-04 00:37:23',129080,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1851,1727,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1851,317,'2020-09-15 19:18:35',349500,1461,4,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2557,971,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2557,828,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2557,1172,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2557,1361,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2557,774,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2557,1077,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2557,640,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2557,596,'2020-11-01 13:48:15',149772,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(707,435,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(707,1228,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(707,87,'2020-10-12 08:46:34',139120,1461,1,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1792,524,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1792,927,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1792,2328,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1792,2215,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1792,1152,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1792,291,'2020-09-27 13:21:58',208400,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(443,961,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(443,243,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(443,297,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(443,55,'2020-10-06 22:52:58',331660,1461,1,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1505,891,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1505,1368,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1505,1405,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1505,2397,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1505,102,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1505,231,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1505,2237,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1505,1712,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1505,193,'2020-09-25 17:22:28',164680,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(890,1574,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(890,1222,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(890,232,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(890,115,'2020-10-28 22:30:54',226980,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(854,695,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(854,182,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(854,1491,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(854,1909,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(854,482,5);

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1065,1791,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1065,276,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1065,1753,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1065,137,'2020-11-01 01:46:47',85940,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(574,1675,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(574,1944,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(574,1476,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(574,1130,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(574,71,'2020-10-26 19:28:13',199680,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2426,918,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2426,1955,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2426,2429,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2426,2197,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2426,2381,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2426,654,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2426,2256,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2426,75,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2426,547,'2020-10-15 12:59:51',412240,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3006,1126,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3006,2397,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3006,1022,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3006,2192,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3006,756,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3006,2067,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3006,1089,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3006,782,'2020-10-29 22:48:07',198212,1461,4,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3233,510,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3233,874,'2020-11-05 12:42:45',47400,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1463,57,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1463,1803,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1463,2347,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1463,2125,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1463,187,'2020-09-18 17:31:34',169300,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2124,1010,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2124,293,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2124,1467,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2124,680,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2124,1077,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2124,1454,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2124,2201,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2124,430,'2020-11-04 14:26:44',121070,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(44,1052,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(44,1307,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(44,357,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(44,1603,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(44,1908,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(44,190,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(44,6,'2020-09-12 20:43:58',241921,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(877,1773,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(877,1948,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(877,2051,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(877,1197,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(877,1558,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(877,2074,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(877,2184,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(877,81,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(877,1074,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(877,113,'2020-09-27 10:58:47',231420,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3188,2406,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3188,130,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3188,854,'2020-10-31 11:18:53',663000,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3405,1353,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3405,1562,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3405,947,'2020-11-05 18:24:28',98800,1461,4,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1751,609,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1751,953,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1751,1043,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1751,396,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1751,1217,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1751,2389,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1751,519,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1751,274,'2020-10-25 07:29:16',157900,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3236,873,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3236,2419,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3236,396,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3236,1678,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3236,969,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3236,2108,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3236,875,'2020-10-17 21:44:45',85540,1461,6,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1496,1627,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1496,670,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1496,127,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1496,149,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1496,192,'2020-11-04 17:43:27',161700,1461,1,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3395,2151,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3395,1461,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3395,1563,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3395,1762,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3395,943,'2020-10-11 13:00:19',313420,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3033,2246,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3033,1402,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3033,609,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3033,2271,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3033,1059,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3033,1188,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3033,2409,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3033,774,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3033,174,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3033,794,'2020-10-12 21:16:06',117540,1461,4,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3141,1607,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3141,130,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3141,836,'2020-09-30 13:57:38',394980,1461,1,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1515,1255,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1515,1363,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1515,2110,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1515,144,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1515,194,'2020-11-02 00:26:13',140120,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,1406,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,2312,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,28,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,427,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,2035,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,364,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,237,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,1381,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,1464,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,1270,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(441,1228,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(441,55,'2020-10-16 09:42:13',349500,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1104,1943,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1104,2175,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1104,2420,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1104,1679,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1104,143,'2020-09-14 18:43:03',189860,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(92,2188,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(92,2218,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(92,146,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(92,834,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(92,753,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(92,11,'2020-10-17 01:54:03',162300,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2336,1813,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2336,1242,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2336,510,'2020-10-13 22:41:59',31760,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(231,872,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(231,1969,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(231,344,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(231,30,'2020-09-26 16:09:08',73840,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(14,2267,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(14,1199,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(14,52,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(14,3,'2020-09-28 16:16:07',112140,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(454,1159,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(454,1670,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(454,57,'2020-10-14 23:12:59',194580,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(38,1642,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(38,1620,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(38,983,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(38,114,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(38,5,'2020-10-23 13:15:19',230020,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2516,744,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2516,137,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2516,1320,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2516,1201,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2516,1904,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2516,800,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2516,2307,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2516,2202,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2516,297,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2516,580,'2020-09-26 23:11:44',426260,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3415,1707,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3415,843,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3415,1837,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3415,724,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3415,1114,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3415,2407,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3415,2101,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3415,1912,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3415,951,'2020-09-07 12:57:37',173490,1461,1,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(985,234,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(985,2085,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(985,126,'2020-10-13 14:35:21',139740,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1687,60,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1687,254,'2020-10-13 11:34:47',159600,1461,1,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1489,2073,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1489,1803,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1489,482,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1489,191,'2020-09-11 15:40:03',172280,1461,3,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2870,2130,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2870,915,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2870,851,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2870,1739,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2870,728,'2020-09-13 12:31:25',106980,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1854,1884,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1854,1669,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1854,318,'2020-10-10 16:25:27',162320,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2992,436,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2992,1018,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2992,782,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2992,777,'2020-10-08 10:39:53',94560,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3149,1927,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3149,347,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3149,417,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3149,969,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3149,514,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3149,307,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3149,838,'2020-09-18 00:38:19',225100,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2756,575,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2756,1879,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2756,2183,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2756,814,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2756,681,'2020-09-27 17:25:05',98480,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3463,2108,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3463,1209,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3463,1610,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3463,2073,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3463,1479,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3463,2368,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3463,1222,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3463,137,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3463,2248,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3463,973,'2020-10-28 09:31:43',152440,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1776,311,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1776,2361,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1776,284,'2020-10-22 15:51:26',206000,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2512,650,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2512,411,6);

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1120,1228,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1120,145,'2020-10-13 23:05:28',144000,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(964,1378,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(964,53,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(964,766,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(964,867,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(964,123,'2020-10-02 13:01:33',396780,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2960,497,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2960,283,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2960,763,'2020-10-30 11:04:33',197400,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1925,1984,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1925,986,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1925,1234,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1925,1688,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1925,271,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1925,346,'2020-10-15 19:55:39',135690,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2338,2415,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2338,1135,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2338,2180,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2338,585,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2338,423,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2338,510,'2020-10-25 15:51:32',166760,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1878,443,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1878,327,'2020-11-06 10:16:28',159125,1461,2,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2460,1989,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2460,667,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2460,556,'2020-10-06 03:35:12',431720,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(438,1698,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(438,54,'2020-09-09 08:55:23',125700,1461,6,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,1400,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,2285,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,792,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,570,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,1142,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,993,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,960,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,1680,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,2344,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,873,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,1978,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,1945,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,109,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,1085,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(439,282,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(439,54,'2020-09-14 13:34:53',257440,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2142,2331,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2142,280,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2142,435,'2020-10-20 06:53:16',110720,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1732,2149,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1732,1278,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1732,269,'2020-10-30 10:00:32',33040,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1197,849,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1197,2148,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1197,1227,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1197,154,'2020-10-30 13:01:17',40670,1461,4,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3128,521,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3128,2137,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3128,38,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3128,1514,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3128,1945,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3128,762,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3128,831,'2020-09-17 07:24:41',190860,1461,2,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3433,678,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3433,886,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3433,961,'2020-09-17 02:20:57',373000,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2783,1315,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2783,826,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2783,174,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2783,693,'2020-09-18 11:24:26',100300,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2305,2249,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2305,496,'2020-10-13 18:40:59',87200,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(100,442,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(100,906,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(100,72,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(100,1007,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(100,13,'2020-10-25 02:11:06',150200,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2619,935,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2619,1054,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2619,627,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2619,2103,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2619,733,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2619,1897,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2619,1342,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2619,623,'2020-10-02 10:31:31',140380,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(371,1063,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(371,558,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(371,2124,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(371,1144,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(371,1328,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(371,47,'2020-11-03 23:52:16',165040,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1955,313,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1955,472,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1955,357,'2020-10-03 22:15:33',266640,1461,6,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1611,112,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1611,835,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1611,1361,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1611,519,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1611,404,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1611,1595,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1611,1737,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1611,222,'2020-09-28 04:04:32',177804,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3270,1809,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3270,2279,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3270,1547,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3270,165,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3270,887,'2020-11-01 06:25:09',96620,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(195,1865,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(195,12,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(195,26,'2020-09-16 22:31:12',153200,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3163,1820,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3163,679,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3163,1409,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3163,850,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3163,1420,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3163,2010,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3163,886,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3163,844,'2020-10-23 21:54:46',486660,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3158,1143,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3158,1521,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3158,81,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3158,2035,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3158,422,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3158,1692,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3158,842,'2020-11-03 05:37:05',201420,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(550,1303,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(550,1457,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(550,559,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(550,1868,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(550,263,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(550,904,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(550,535,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(550,359,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(550,68,'2020-10-24 07:30:26',180560,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2881,1592,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2881,1204,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2881,1582,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2881,110,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2881,2213,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2881,928,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2881,732,'2020-10-30 06:03:46',162460,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2983,2138,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2983,28,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2983,1482,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2983,463,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2983,771,'2020-10-26 07:42:30',110300,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3407,1456,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3407,1328,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3407,948,'2020-11-05 22:47:04',48640,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3182,113,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3182,851,'2020-10-05 12:06:49',269400,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2317,777,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2317,126,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2317,501,'2020-10-25 07:27:54',183200,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(251,2086,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(251,468,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(251,1532,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(251,32,'2020-11-02 06:37:02',143980,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2422,1815,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2422,806,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2422,1570,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2422,59,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2422,545,'2020-09-09 14:35:53',389320,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(420,282,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(420,1441,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(420,774,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(420,2128,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(420,52,'2020-09-08 09:45:14',83580,1461,4,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2821,2080,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2821,707,'2020-09-25 19:05:27',114000,1461,2,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2192,1174,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2192,1399,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2192,376,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2192,88,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2192,451,'2020-09-30 18:29:50',183240,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2912,1549,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2912,2225,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2912,744,'2020-10-18 18:27:33',334000,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2421,1490,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2421,137,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2421,2026,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2421,2062,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2421,956,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2421,1611,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2421,424,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2421,2282,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2421,2292,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2421,1294,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2421,545,'2020-10-13 00:04:20',177890,1461,6,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3053,667,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3053,802,'2020-11-07 06:54:28',139000,1461,6,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1279,642,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1279,266,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1279,163,'2020-10-20 19:13:17',188280,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3072,1917,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3072,1988,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3072,809,'2020-11-02 15:11:54',45440,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,1919,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,923,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,2402,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,115,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,1757,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,2051,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,1816,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,2038,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,296,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,2017,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,593,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,1002,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(152,264,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(152,20,'2020-09-22 04:55:29',226920,1461,2,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3044,430,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3044,2101,1);

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1820,679,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1820,1371,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1820,2304,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1820,1616,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1820,304,'2020-10-17 09:14:06',288044,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2071,888,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2071,408,'2020-09-16 05:53:48',675000,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(66,1985,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(66,2026,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(66,615,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(66,669,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(66,346,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(66,1893,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(66,2123,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(66,46,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(66,9,'2020-09-14 08:48:15',552990,1461,4,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3075,689,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3075,956,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3075,1254,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3075,288,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3075,1087,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3075,501,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3075,810,'2020-11-05 11:00:37',87180,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(525,715,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(525,662,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(525,65,'2020-09-25 03:12:23',783390,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(998,540,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(998,938,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(998,1076,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(998,1366,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(998,980,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(998,128,'2020-10-15 06:09:33',102900,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3300,308,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3300,898,'2020-10-09 01:30:08',149700,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2194,1359,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2194,106,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2194,1628,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2194,451,'2020-09-29 08:45:11',316220,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1926,254,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1926,346,'2020-10-15 20:40:34',219000,1461,1,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1441,1039,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1441,572,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1441,2232,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1441,790,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1441,1590,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1441,160,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1441,1560,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1441,184,'2020-09-11 04:23:35',209600,1461,4,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2024,979,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2024,1718,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2024,1534,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2024,146,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2024,385,'2020-09-11 08:56:35',116820,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1377,996,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1377,2186,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1377,175,'2020-10-02 15:40:08',44736,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2452,2069,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2452,2363,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2452,553,'2020-10-01 01:11:19',72880,1461,6,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(506,1171,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(506,692,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(506,1484,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(506,2208,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(506,1287,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(506,1061,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(506,62,'2020-11-05 20:40:48',81600,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2664,2105,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2664,2019,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2664,1360,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2664,2206,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2664,1703,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2664,641,'2020-09-11 21:04:09',142860,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2930,694,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2930,1890,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2930,2360,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2930,751,'2020-11-06 02:07:54',96640,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(138,69,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(138,1510,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(138,184,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(138,1073,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(138,749,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(138,19,'2020-10-09 21:16:04',211930,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1756,1967,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1756,1431,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1756,2240,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1756,275,'2020-11-02 08:43:13',82820,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2527,2234,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2527,1609,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2527,1882,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2527,1444,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2527,584,'2020-10-30 08:52:41',77400,1461,4,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2711,44,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2711,180,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2711,26,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2711,2384,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2711,586,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2711,657,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2711,2218,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2711,661,'2020-09-18 00:04:36',155000,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2727,924,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2727,1809,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2727,1072,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2727,598,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2727,1596,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2727,668,'2020-09-14 19:11:16',64582,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(967,227,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(967,452,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(967,1871,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(967,2082,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(967,124,'2020-10-05 04:16:21',111120,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(362,1657,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(362,1931,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(362,245,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(362,1070,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(362,595,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(362,1532,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(362,10,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(362,690,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(362,1054,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(362,46,'2020-11-05 08:47:51',118260,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(31,1399,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(31,1459,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(31,2304,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(31,1451,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(31,387,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(31,5,'2020-10-10 03:50:29',92240,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2107,533,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2107,517,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2107,421,'2020-09-28 03:53:07',36720,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(105,601,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(105,556,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(105,2292,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(105,2237,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(105,1213,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(105,979,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(105,2370,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(105,1674,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(105,13,'2020-10-23 06:33:19',252020,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(579,88,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(579,247,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(579,72,'2020-09-17 18:33:42',161400,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3474,1031,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3474,978,'2020-10-23 03:42:24',29700,1461,4,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3102,2271,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3102,51,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3102,820,'2020-10-03 16:13:04',323280,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,368,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,1026,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,1769,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,1274,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,2266,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,632,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,1991,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,2378,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,2253,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,843,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(427,1859,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(427,53,'2020-10-26 19:20:07',157250,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2548,91,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2548,793,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2548,2073,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2548,1430,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2548,593,'2020-09-14 23:39:19',60508,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1614,1530,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1614,105,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1614,1817,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1614,2037,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1614,2058,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1614,217,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1614,223,'2020-09-26 21:01:11',124420,1461,1,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2444,1370,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2444,1522,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2444,1108,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2444,1889,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2444,122,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2444,814,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2444,551,'2020-09-11 08:27:00',178760,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2397,2240,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2397,535,'2020-09-22 20:52:27',88800,1461,4,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(245,1564,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(245,1737,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(245,1055,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(245,1990,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(245,1317,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(245,128,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(245,32,'2020-09-28 11:50:33',158600,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2244,544,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2244,140,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2244,471,'2020-10-29 15:47:53',232300,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(677,1917,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(677,1568,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(677,285,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(677,84,'2020-11-04 21:54:46',408440,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1815,1160,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1815,636,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1815,2270,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1815,979,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1815,301,'2020-10-28 14:19:27',206240,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2954,394,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2954,263,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2954,149,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2954,840,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2954,641,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2954,521,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2954,761,'2020-10-16 02:18:44',276700,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(444,1546,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(444,180,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(444,18,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(444,2176,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(444,32,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(444,1728,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(444,55,'2020-09-14 12:17:08',408175,1461,2,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1210,1924,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1210,271,6);

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1517,1627,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1517,2299,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1517,194,'2020-11-01 19:41:27',65740,1461,4,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3131,827,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3131,1318,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3131,1219,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3131,1409,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3131,2380,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3131,1245,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3131,858,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3131,1581,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3131,833,'2020-09-16 21:58:57',130840,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1011,347,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1011,807,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1011,1289,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1011,253,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1011,129,'2020-10-31 18:52:04',283870,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3386,1719,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3386,1769,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3386,1072,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3386,1075,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3386,1948,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3386,229,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3386,940,'2020-10-13 07:37:18',295760,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3242,1508,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3242,381,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3242,2235,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3242,877,'2020-09-19 23:13:51',59400,1461,3,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(795,1168,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(795,1239,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(795,2229,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(795,1425,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(795,1845,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(795,2109,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(795,101,'2020-09-09 15:39:58',163280,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1678,1409,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1678,951,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1678,1817,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1678,2237,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1678,1798,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1678,105,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1678,2065,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1678,1749,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1678,251,'2020-10-03 15:22:26',425650,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1892,1562,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1892,1413,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1892,821,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1892,559,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1892,2278,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1892,1304,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1892,98,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1892,331,'2020-09-27 04:31:00',233748,1461,6,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(777,1621,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(777,98,'2020-09-25 00:25:23',108000,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2474,1328,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2474,1239,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2474,350,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2474,563,'2020-09-15 23:02:47',78080,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(876,2105,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(876,766,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(876,531,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(876,500,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(876,1383,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(876,2157,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(876,2161,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(876,216,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(876,112,'2020-10-03 06:54:03',230400,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1965,1091,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1965,1401,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1965,220,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1965,2253,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1965,1078,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1965,360,'2020-09-21 01:03:53',87920,1461,4,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(983,2371,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(983,1138,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(983,1596,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(983,1096,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(983,2350,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(983,1534,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(983,1276,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(983,126,'2020-10-24 09:59:20',107000,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(74,960,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(74,2215,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(74,1370,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(74,9,'2020-10-01 00:31:38',39480,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3245,1481,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3245,801,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3245,1100,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3245,1428,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3245,1209,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3245,636,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3245,777,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3245,878,'2020-10-27 20:44:31',206880,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2750,1014,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2750,2328,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2750,1467,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2750,1043,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2750,1692,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2750,678,'2020-11-03 16:08:05',163460,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2202,2040,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2202,1526,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2202,1140,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2202,2028,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2202,1364,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2202,787,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2202,2088,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2202,9,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2202,1385,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2202,455,'2020-11-06 06:40:34',108080,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(798,777,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(798,101,'2020-10-03 15:11:39',249500,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2439,1651,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2439,2221,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2439,838,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2439,2379,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2439,575,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2439,2266,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2439,312,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2439,550,'2020-09-19 14:16:26',199400,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1254,1080,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1254,1487,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1254,160,'2020-10-29 03:44:54',40820,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1578,2386,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1578,2217,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1578,2236,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1578,425,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1578,976,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1578,758,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1578,208,'2020-11-07 10:12:43',150300,1461,6,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(483,1363,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(483,1107,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(483,1288,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(483,60,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(483,60,'2020-09-23 19:43:10',363620,1461,1,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2412,1705,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2412,867,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2412,541,'2020-10-05 01:47:21',352900,1461,1,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3244,1417,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3244,2009,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3244,1742,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3244,878,'2020-11-06 05:16:32',110800,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(896,699,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(896,116,'2020-09-24 09:00:17',1900000,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(241,170,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(241,1249,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(241,36,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(241,1116,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(241,31,'2020-10-26 17:34:26',133320,1461,1,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2361,1659,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2361,1218,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2361,278,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2361,522,'2020-09-09 13:30:50',111480,1461,2,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2741,293,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2741,2323,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2741,591,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2741,1214,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2741,2288,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2741,1523,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2741,2171,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2741,554,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2741,424,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2741,675,'2020-11-04 10:31:41',206860,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(950,980,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(950,35,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(950,885,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(950,122,'2020-10-06 02:45:16',829140,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1292,1171,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1292,47,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1292,1137,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1292,680,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1292,1761,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1292,164,'2020-10-24 19:08:12',197380,1461,3,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2008,866,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2008,1,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2008,378,'2020-10-30 13:17:27',115500,1461,5,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2247,2291,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2247,1860,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2247,1470,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2247,321,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2247,805,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2247,472,'2020-09-27 02:06:04',199380,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3513,1298,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3513,994,'2020-10-15 16:11:02',83880,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(386,634,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(386,1924,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(386,250,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(386,1521,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(386,1998,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(386,189,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(386,309,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(386,49,'2020-10-26 20:35:08',150720,1461,2,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1306,418,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1306,166,'2020-09-09 12:19:49',100680,1461,1,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1317,1469,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1317,2271,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1317,1104,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1317,823,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1317,1909,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1317,753,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1317,883,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1317,1810,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1317,167,'2020-10-23 06:26:31',168430,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,2314,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,1460,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,2125,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,1291,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,950,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,1639,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,2013,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,1813,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,807,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,364,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,255,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,1878,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,1972,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2201,1656,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2201,454,'2020-09-26 17:39:27',202860,1461,5,'23:59');

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2274,1820,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2274,485,'2020-09-23 21:37:05',173660,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(363,878,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(363,1795,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(363,45,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(363,1938,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(363,1070,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(363,1456,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(363,1099,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(363,685,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(363,46,'2020-10-07 16:44:10',213230,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1155,2102,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1155,650,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1155,626,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1155,2393,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1155,1293,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1155,1392,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1155,1842,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1155,1009,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1155,149,'2020-09-14 17:28:33',111940,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2742,1450,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2742,211,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2742,675,'2020-09-24 21:56:26',233120,1461,5,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(720,1105,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(720,121,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(720,1149,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(720,711,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(720,2136,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(720,90,'2020-10-04 20:22:52',235860,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(161,583,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(161,1465,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(161,317,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(161,21,'2020-10-06 23:53:03',103640,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1528,726,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1528,196,'2020-09-22 01:24:31',112800,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2367,768,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2367,2128,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2367,1054,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2367,2005,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2367,1657,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2367,1875,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2367,375,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2367,190,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2367,524,'2020-10-21 09:24:58',210200,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2826,1343,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2826,1577,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2826,1662,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2826,1787,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2826,2214,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2826,306,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2826,710,'2020-10-13 06:29:54',99680,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(142,100,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(142,2088,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(142,652,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(142,19,'2020-09-12 02:23:22',124600,1461,6,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(803,1276,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(803,1326,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(803,1595,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(803,243,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(803,598,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(803,310,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(803,827,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(803,585,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(803,576,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(803,102,'2020-09-11 10:54:02',180740,1461,4,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2876,2053,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2876,2056,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2876,137,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2876,1445,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2876,1881,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2876,1573,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2876,977,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2876,730,'2020-09-25 19:53:13',163470,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1250,1337,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1250,2236,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1250,394,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1250,625,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1250,1345,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1250,160,'2020-11-06 02:20:55',186020,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1360,792,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1360,345,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1360,1666,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1360,173,'2020-10-11 15:57:28',54820,1461,2,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1537,928,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1537,1405,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1537,2413,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1537,1423,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1537,477,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1537,1787,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1537,2069,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1537,1645,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1537,196,'2020-11-01 14:17:10',230700,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1017,2203,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1017,478,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1017,130,'2020-10-21 05:52:22',88152,1461,4,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3026,863,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3026,203,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3026,891,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3026,1985,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3026,2267,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3026,792,'2020-10-10 02:55:37',125100,1461,6,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1976,1526,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1976,1891,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1976,655,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1976,1635,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1976,1522,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1976,598,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1976,1444,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1976,1479,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1976,776,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1976,366,'2020-10-30 05:11:55',189490,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2373,2095,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2373,791,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2373,603,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2373,1963,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2373,1905,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2373,527,'2020-11-06 17:45:23',79120,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1937,262,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1937,806,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1937,1146,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1937,1580,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1937,42,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1937,566,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1937,684,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1937,350,'2020-10-06 23:21:30',218520,1461,2,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(663,1911,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(663,597,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(663,14,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(663,2006,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(663,82,'2020-10-14 01:18:56',194860,1461,2,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2895,2212,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2895,294,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2895,132,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2895,1053,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2895,2405,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2895,65,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2895,738,'2020-10-27 05:49:58',540980,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1691,1622,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1691,1488,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1691,1029,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1691,1543,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1691,382,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1691,255,'2020-09-11 01:52:37',156480,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2603,1289,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2603,212,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2603,1628,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2603,2309,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2603,2199,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2603,1473,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2603,628,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2603,1963,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2603,1331,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2603,616,'2020-10-30 19:49:18',167580,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(859,1855,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(859,1973,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(859,5,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(859,425,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(859,703,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(859,783,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(859,109,'2020-09-09 18:38:08',103570,1461,5,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3274,2329,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3274,1773,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3274,612,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3274,1355,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3274,1691,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3274,888,'2020-10-11 09:59:23',71620,1461,3,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(829,888,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(829,106,'2020-09-07 19:36:53',810000,1461,2,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1616,1177,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1616,926,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1616,1580,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1616,437,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1616,217,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1616,224,'2020-10-16 04:52:29',104580,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2807,1563,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2807,2253,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2807,1349,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2807,540,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2807,507,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2807,455,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2807,701,'2020-10-16 17:11:45',208050,1461,4,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1173,515,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1173,152,'2020-09-15 11:13:58',88920,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2069,184,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2069,406,'2020-09-24 11:28:36',324000,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(771,110,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(771,97,'2020-09-23 18:07:22',71400,1461,4,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(212,1351,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(212,454,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(212,29,'2020-11-07 07:27:07',503100,1461,4,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(843,418,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(843,2301,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(843,871,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(843,2300,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(843,1171,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(843,107,'2020-09-21 07:53:19',119600,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1203,2358,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1203,2020,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1203,1447,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1203,1720,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1203,2416,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1203,1528,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1203,1167,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1203,1782,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1203,155,'2020-09-20 08:33:59',156220,1461,6,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1305,1559,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1305,112,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1305,1292,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1305,1177,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1305,947,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1305,166,'2020-10-12 20:09:12',115140,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3436,1538,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3436,498,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3436,962,'2020-10-03 19:42:13',73400,1461,1,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(7,1840,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(7,102,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(7,1087,4);

INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(307,841,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(307,517,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(307,1811,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(307,2331,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(307,127,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(307,960,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(307,304,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(307,39,'2020-09-27 03:15:42',164590,1461,6,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2591,2180,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2591,1743,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2591,1198,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2591,2310,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2591,2280,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2591,1383,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2591,610,'2020-10-20 12:16:27',226076,1461,1,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1494,2041,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1494,2329,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1494,340,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1494,2281,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1494,192,'2020-11-04 08:37:17',105680,1461,6,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2725,1331,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2725,671,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2725,1626,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2725,607,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2725,666,'2020-11-03 21:46:04',133380,1461,2,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,2426,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,1848,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,10,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,590,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,1917,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,1892,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,997,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,1433,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,745,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,342,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,659,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2687,2318,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2687,653,'2020-10-06 12:50:30',221720,1461,1,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2795,2263,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2795,201,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2795,697,'2020-11-01 14:57:18',254600,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1672,739,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1672,550,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1672,656,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1672,1677,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1672,248,'2020-11-04 15:55:46',74540,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(566,777,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(566,70,'2020-09-11 15:07:07',199600,1461,5,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1864,1367,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1864,1829,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1864,1592,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1864,3,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1864,864,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1864,321,'2020-10-01 05:53:09',73700,1461,5,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(69,1265,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(69,1262,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(69,1856,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(69,1526,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(69,79,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(69,1796,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(69,247,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(69,9,'2020-10-03 19:31:16',141380,1461,1,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(9,1008,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(9,912,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(9,313,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(9,2029,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(9,2100,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(9,560,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(9,17,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(9,2,'2020-10-22 00:09:53',162020,1461,4,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2613,2393,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2613,2231,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2613,467,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2613,1858,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2613,684,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2613,620,'2020-10-22 09:16:51',196680,1461,4,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3115,801,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3115,1039,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3115,2115,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3115,1337,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3115,2072,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3115,824,'2020-09-24 13:55:38',118480,1461,6,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2455,2132,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2455,340,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2455,478,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2455,555,'2020-10-08 00:49:01',184260,1461,1,'18:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2985,99,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2985,502,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2985,773,'2020-10-31 00:53:13',215200,1461,2,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2224,1107,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2224,291,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2224,1646,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2224,22,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2224,625,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2224,990,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2224,2405,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2224,1883,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2224,719,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2224,666,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2224,463,'2020-09-24 19:27:29',234210,1461,6,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3023,263,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3023,1109,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3023,2411,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3023,2179,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3023,212,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3023,790,'2020-11-01 16:53:15',159488,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3114,1525,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3114,1042,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3114,2235,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3114,824,'2020-09-26 02:32:05',104400,1461,3,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(923,1682,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(923,2408,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(923,1057,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(923,956,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(923,71,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(923,119,'2020-11-05 01:55:15',466000,1461,3,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2205,1413,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2205,1804,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2205,1440,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(2205,207,1);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(2205,456,'2020-10-16 09:17:47',65400,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(988,17,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(988,127,'2020-09-25 08:48:24',39920,1461,1,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1686,1721,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1686,2415,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1686,1496,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1686,606,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1686,1104,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1686,2058,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1686,1236,2);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1686,254,'2020-10-18 23:38:31',185140,1461,6,'23:59');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3219,1297,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3219,910,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3219,1306,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3219,22,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3219,2143,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3219,1974,4);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(3219,1633,4);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(3219,866,'2020-09-18 18:37:45',133700,1461,3,'17:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1868,1171,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(1868,155,3);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(1868,322,'2020-10-26 11:24:18',43940,1461,6,'11:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(225,1239,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(225,2399,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(225,30,'2020-10-29 06:41:26',36300,1461,5,'14:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(271,2382,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(271,1100,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(271,1279,5);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(271,522,3);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(271,1438,2);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(271,2225,5);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(271,35,'2020-10-28 16:00:43',620510,1461,6,'10:00');
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(911,950,1);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(911,1119,6);
INSERT INTO carts(orders_id,products_id,products_quantity)VALUES(911,1432,6);
INSERT INTO orders(id, users_seq,time, total_price, credit_cards_seq, delivery_day, delivery_time)VALUES(911,118,'2020-10-21 07:07:16',210660,1461,4,'23:59');